// Printed from the descriptors in the google-antigravity v0.1.20 wheel
// (google/antigravity/proto/genai_json_annotations_pb2.py) by testdata/protoextract.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: google/antigravity/proto/genai_json_annotations.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JsonType int32

const (
	JsonType_JSON_TYPE_UNSPECIFIED JsonType = 0
	JsonType_JSON_TYPE_OBJECT      JsonType = 1
	JsonType_JSON_TYPE_ARRAY       JsonType = 2
	JsonType_JSON_TYPE_VALUE       JsonType = 3
)

// Enum value maps for JsonType.
var (
	JsonType_name = map[int32]string{
		0: "JSON_TYPE_UNSPECIFIED",
		1: "JSON_TYPE_OBJECT",
		2: "JSON_TYPE_ARRAY",
		3: "JSON_TYPE_VALUE",
	}
	JsonType_value = map[string]int32{
		"JSON_TYPE_UNSPECIFIED": 0,
		"JSON_TYPE_OBJECT":      1,
		"JSON_TYPE_ARRAY":       2,
		"JSON_TYPE_VALUE":       3,
	}
)

func (x JsonType) Enum() *JsonType {
	p := new(JsonType)
	*p = x
	return p
}

func (x JsonType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JsonType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_antigravity_proto_genai_json_annotations_proto_enumTypes[0].Descriptor()
}

func (JsonType) Type() protoreflect.EnumType {
	return &file_google_antigravity_proto_genai_json_annotations_proto_enumTypes[0]
}

func (x JsonType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type StaticJsonField struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key         *string                `protobuf:"bytes,1,opt,name=key"`
	xxx_hidden_Value       *string                `protobuf:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StaticJsonField) Reset() {
	*x = StaticJsonField{}
	mi := &file_google_antigravity_proto_genai_json_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticJsonField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticJsonField) ProtoMessage() {}

func (x *StaticJsonField) ProtoReflect() protoreflect.Message {
	mi := &file_google_antigravity_proto_genai_json_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StaticJsonField) GetKey() string {
	if x != nil {
		if x.xxx_hidden_Key != nil {
			return *x.xxx_hidden_Key
		}
		return ""
	}
	return ""
}

func (x *StaticJsonField) GetValue() string {
	if x != nil {
		if x.xxx_hidden_Value != nil {
			return *x.xxx_hidden_Value
		}
		return ""
	}
	return ""
}

func (x *StaticJsonField) SetKey(v string) {
	x.xxx_hidden_Key = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *StaticJsonField) SetValue(v string) {
	x.xxx_hidden_Value = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *StaticJsonField) HasKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StaticJsonField) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StaticJsonField) ClearKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Key = nil
}

func (x *StaticJsonField) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Value = nil
}

type StaticJsonField_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key   *string
	Value *string
}

func (b0 StaticJsonField_builder) Build() *StaticJsonField {
	m0 := &StaticJsonField{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Key != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Key = b.Key
	}
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Value = b.Value
	}
	return m0
}

var file_google_antigravity_proto_genai_json_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         525000029,
		Name:          "gaos.parsing.is_union",
		Tag:           "varint,525000029,opt,name=is_union",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         525000030,
		Name:          "gaos.parsing.subtype_source",
		Tag:           "varint,525000030,opt,name=subtype_source",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         525000031,
		Name:          "gaos.parsing.is_required",
		Tag:           "varint,525000031,opt,name=is_required",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         525000032,
		Name:          "gaos.parsing.union_name",
		Tag:           "bytes,525000032,opt,name=union_name",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         525000215,
		Name:          "gaos.parsing.json_discriminator",
		Tag:           "bytes,525000215,opt,name=json_discriminator",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         525000216,
		Name:          "gaos.parsing.json_discriminator_value",
		Tag:           "bytes,525000216,opt,name=json_discriminator_value",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         525000217,
		Name:          "gaos.parsing.subtype_source_field",
		Tag:           "varint,525000217,opt,name=subtype_source_field",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         525000218,
		Name:          "gaos.parsing.json_only_discriminator",
		Tag:           "bytes,525000218,opt,name=json_only_discriminator",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         525000219,
		Name:          "gaos.parsing.additional_properties",
		Tag:           "varint,525000219,opt,name=additional_properties",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         525000220,
		Name:          "gaos.parsing.json_discriminator_values",
		Tag:           "bytes,525000220,rep,name=json_discriminator_values",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         525000221,
		Name:          "gaos.parsing.add_union_value",
		Tag:           "bytes,525000221,rep,name=add_union_value",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         525000222,
		Name:          "gaos.parsing.flexible_map",
		Tag:           "varint,525000222,opt,name=flexible_map",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         525000227,
		Name:          "gaos.parsing.sub_content_name",
		Tag:           "bytes,525000227,opt,name=sub_content_name",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         535802949,
		Name:          "gaos.parsing.enum_value_name",
		Tag:           "bytes,535802949,opt,name=enum_value_name",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*StaticJsonField)(nil),
		Field:         535801962,
		Name:          "gaos.parsing.add_static_field",
		Tag:           "bytes,535801962,opt,name=add_static_field",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*JsonType)(nil),
		Field:         535801963,
		Name:          "gaos.parsing.message_json_type",
		Tag:           "varint,535801963,opt,name=message_json_type,enum=gaos.parsing.JsonType",
		Filename:      "google/antigravity/proto/genai_json_annotations.proto",
	},
}

// Extension fields to descriptorpb.OneofOptions.
var (
	// optional bool is_union = 525000029;
	E_IsUnion = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[0]
	// optional bool subtype_source = 525000030;
	E_SubtypeSource = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[1]
	// optional bool is_required = 525000031;
	E_IsRequired = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[2]
	// optional string union_name = 525000032;
	E_UnionName = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[3]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string json_discriminator = 525000215;
	E_JsonDiscriminator = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[4]
	// optional string json_discriminator_value = 525000216;
	E_JsonDiscriminatorValue = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[5]
	// optional bool subtype_source_field = 525000217;
	E_SubtypeSourceField = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[6]
	// optional string json_only_discriminator = 525000218;
	E_JsonOnlyDiscriminator = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[7]
	// optional bool additional_properties = 525000219;
	E_AdditionalProperties = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[8]
	// repeated string json_discriminator_values = 525000220;
	E_JsonDiscriminatorValues = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[9]
	// repeated string add_union_value = 525000221;
	E_AddUnionValue = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[10]
	// optional bool flexible_map = 525000222;
	E_FlexibleMap = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[11]
	// optional string sub_content_name = 525000227;
	E_SubContentName = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[12]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional string enum_value_name = 535802949;
	E_EnumValueName = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[13]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional gaos.parsing.StaticJsonField add_static_field = 535801962;
	E_AddStaticField = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[14]
	// optional gaos.parsing.JsonType message_json_type = 535801963;
	E_MessageJsonType = &file_google_antigravity_proto_genai_json_annotations_proto_extTypes[15]
)

var File_google_antigravity_proto_genai_json_annotations_proto protoreflect.FileDescriptor

const file_google_antigravity_proto_genai_json_annotations_proto_rawDesc = "" +
	"\n" +
	"5google/antigravity/proto/genai_json_annotations.proto\x12\fgaos.parsing\x1a google/protobuf/descriptor.proto\"9\n" +
	"\x0fStaticJsonField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value*e\n" +
	"\bJsonType\x12\x19\n" +
	"\x15JSON_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10JSON_TYPE_OBJECT\x10\x01\x12\x13\n" +
	"\x0fJSON_TYPE_ARRAY\x10\x02\x12\x13\n" +
	"\x0fJSON_TYPE_VALUE\x10\x03:<\n" +
	"\bis_union\x12\x1d.google.protobuf.OneofOptions\x18ݺ\xab\xfa\x01 \x01(\bR\aisUnion:H\n" +
	"\x0esubtype_source\x12\x1d.google.protobuf.OneofOptions\x18\u07ba\xab\xfa\x01 \x01(\bR\rsubtypeSource:B\n" +
	"\vis_required\x12\x1d.google.protobuf.OneofOptions\x18ߺ\xab\xfa\x01 \x01(\bR\n" +
	"isRequired:@\n" +
	"\n" +
	"union_name\x12\x1d.google.protobuf.OneofOptions\x18ຫ\xfa\x01 \x01(\tR\tunionName:P\n" +
	"\x12json_discriminator\x12\x1d.google.protobuf.FieldOptions\x18\x97\xbc\xab\xfa\x01 \x01(\tR\x11jsonDiscriminator:[\n" +
	"\x18json_discriminator_value\x12\x1d.google.protobuf.FieldOptions\x18\x98\xbc\xab\xfa\x01 \x01(\tR\x16jsonDiscriminatorValue:S\n" +
	"\x14subtype_source_field\x12\x1d.google.protobuf.FieldOptions\x18\x99\xbc\xab\xfa\x01 \x01(\bR\x12subtypeSourceField:Y\n" +
	"\x17json_only_discriminator\x12\x1d.google.protobuf.FieldOptions\x18\x9a\xbc\xab\xfa\x01 \x01(\tR\x15jsonOnlyDiscriminator:V\n" +
	"\x15additional_properties\x12\x1d.google.protobuf.FieldOptions\x18\x9b\xbc\xab\xfa\x01 \x01(\bR\x14additionalProperties:]\n" +
	"\x19json_discriminator_values\x12\x1d.google.protobuf.FieldOptions\x18\x9c\xbc\xab\xfa\x01 \x03(\tR\x17jsonDiscriminatorValues:I\n" +
	"\x0fadd_union_value\x12\x1d.google.protobuf.FieldOptions\x18\x9d\xbc\xab\xfa\x01 \x03(\tR\raddUnionValue:D\n" +
	"\fflexible_map\x12\x1d.google.protobuf.FieldOptions\x18\x9e\xbc\xab\xfa\x01 \x01(\bR\vflexibleMap:K\n" +
	"\x10sub_content_name\x12\x1d.google.protobuf.FieldOptions\x18\xa3\xbc\xab\xfa\x01 \x01(\tR\x0esubContentName:M\n" +
	"\x0fenum_value_name\x12!.google.protobuf.EnumValueOptions\x18\xc5\xe8\xbe\xff\x01 \x01(\tR\renumValueName:l\n" +
	"\x10add_static_field\x12\x1f.google.protobuf.MessageOptions\x18\xea\xe0\xbe\xff\x01 \x01(\v2\x1d.gaos.parsing.StaticJsonFieldR\x0eaddStaticField:g\n" +
	"\x11message_json_type\x12\x1f.google.protobuf.MessageOptions\x18\xeb\xe0\xbe\xff\x01 \x01(\x0e2\x16.gaos.parsing.JsonTypeR\x0fmessageJsonTypeB\xaa\x01\n" +
	"\x10com.gaos.parsingB\x19GenaiJsonAnnotationsProtoZ,github.com/ironpark/gelati/agy/internal/wire\xa2\x02\x03GPX\xaa\x02\fGaos.Parsing\xca\x02\fGaos\\Parsing\xe2\x02\x18Gaos\\Parsing\\GPBMetadata\xea\x02\rGaos::Parsingb\beditionsp\xe9\a"

var file_google_antigravity_proto_genai_json_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_antigravity_proto_genai_json_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_antigravity_proto_genai_json_annotations_proto_goTypes = []any{
	(JsonType)(0),                         // 0: gaos.parsing.JsonType
	(*StaticJsonField)(nil),               // 1: gaos.parsing.StaticJsonField
	(*descriptorpb.OneofOptions)(nil),     // 2: google.protobuf.OneofOptions
	(*descriptorpb.FieldOptions)(nil),     // 3: google.protobuf.FieldOptions
	(*descriptorpb.EnumValueOptions)(nil), // 4: google.protobuf.EnumValueOptions
	(*descriptorpb.MessageOptions)(nil),   // 5: google.protobuf.MessageOptions
}
var file_google_antigravity_proto_genai_json_annotations_proto_depIdxs = []int32{
	2,  // 0: gaos.parsing.is_union:extendee -> google.protobuf.OneofOptions
	2,  // 1: gaos.parsing.subtype_source:extendee -> google.protobuf.OneofOptions
	2,  // 2: gaos.parsing.is_required:extendee -> google.protobuf.OneofOptions
	2,  // 3: gaos.parsing.union_name:extendee -> google.protobuf.OneofOptions
	3,  // 4: gaos.parsing.json_discriminator:extendee -> google.protobuf.FieldOptions
	3,  // 5: gaos.parsing.json_discriminator_value:extendee -> google.protobuf.FieldOptions
	3,  // 6: gaos.parsing.subtype_source_field:extendee -> google.protobuf.FieldOptions
	3,  // 7: gaos.parsing.json_only_discriminator:extendee -> google.protobuf.FieldOptions
	3,  // 8: gaos.parsing.additional_properties:extendee -> google.protobuf.FieldOptions
	3,  // 9: gaos.parsing.json_discriminator_values:extendee -> google.protobuf.FieldOptions
	3,  // 10: gaos.parsing.add_union_value:extendee -> google.protobuf.FieldOptions
	3,  // 11: gaos.parsing.flexible_map:extendee -> google.protobuf.FieldOptions
	3,  // 12: gaos.parsing.sub_content_name:extendee -> google.protobuf.FieldOptions
	4,  // 13: gaos.parsing.enum_value_name:extendee -> google.protobuf.EnumValueOptions
	5,  // 14: gaos.parsing.add_static_field:extendee -> google.protobuf.MessageOptions
	5,  // 15: gaos.parsing.message_json_type:extendee -> google.protobuf.MessageOptions
	1,  // 16: gaos.parsing.add_static_field:type_name -> gaos.parsing.StaticJsonField
	0,  // 17: gaos.parsing.message_json_type:type_name -> gaos.parsing.JsonType
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	16, // [16:18] is the sub-list for extension type_name
	0,  // [0:16] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_google_antigravity_proto_genai_json_annotations_proto_init() }
func file_google_antigravity_proto_genai_json_annotations_proto_init() {
	if File_google_antigravity_proto_genai_json_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_antigravity_proto_genai_json_annotations_proto_rawDesc), len(file_google_antigravity_proto_genai_json_annotations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 16,
			NumServices:   0,
		},
		GoTypes:           file_google_antigravity_proto_genai_json_annotations_proto_goTypes,
		DependencyIndexes: file_google_antigravity_proto_genai_json_annotations_proto_depIdxs,
		EnumInfos:         file_google_antigravity_proto_genai_json_annotations_proto_enumTypes,
		MessageInfos:      file_google_antigravity_proto_genai_json_annotations_proto_msgTypes,
		ExtensionInfos:    file_google_antigravity_proto_genai_json_annotations_proto_extTypes,
	}.Build()
	File_google_antigravity_proto_genai_json_annotations_proto = out.File
	file_google_antigravity_proto_genai_json_annotations_proto_goTypes = nil
	file_google_antigravity_proto_genai_json_annotations_proto_depIdxs = nil
}
