// Code generated by testdata/gen_types.py from the google-antigravity v0.1.20
// proto definitions (google/antigravity/proto/content.proto). DO NOT EDIT.

package wire

// ImageContentMimeType mirrors the genai.ImageContent.MimeType enum.
type ImageContentMimeType string

// ImageContentMimeType values.
const (
	ImageContentMimeTypeUnspecified        ImageContentMimeType = "TYPE_UNSPECIFIED"
	ImageContentMimeTypePng                ImageContentMimeType = "TYPE_PNG"
	ImageContentMimeTypeJpeg               ImageContentMimeType = "TYPE_JPEG"
	ImageContentMimeTypeWebp               ImageContentMimeType = "TYPE_WEBP"
	ImageContentMimeTypeHeic               ImageContentMimeType = "TYPE_HEIC"
	ImageContentMimeTypeHeif               ImageContentMimeType = "TYPE_HEIF"
	ImageContentMimeTypeGif                ImageContentMimeType = "TYPE_GIF"
	ImageContentMimeTypeBmp                ImageContentMimeType = "TYPE_BMP"
	ImageContentMimeTypeTiff               ImageContentMimeType = "TYPE_TIFF"
	ImageContentMimeTypeVideoFrameJpeg2000 ImageContentMimeType = "TYPE_VIDEO_FRAME_JPEG2000"
	ImageContentMimeTypeVideoJpeg2000      ImageContentMimeType = "TYPE_VIDEO_JPEG2000"
)

var imageContentMimeTypeNames = map[int32]string{0: "TYPE_UNSPECIFIED", 1: "TYPE_PNG", 2: "TYPE_JPEG", 3: "TYPE_WEBP", 4: "TYPE_HEIC", 5: "TYPE_HEIF", 7: "TYPE_GIF", 8: "TYPE_BMP", 9: "TYPE_TIFF", 10: "TYPE_VIDEO_FRAME_JPEG2000", 11: "TYPE_VIDEO_JPEG2000"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e ImageContentMimeType) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *ImageContentMimeType) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), imageContentMimeTypeNames)
}

// MediaResolution mirrors the genai.MediaResolution enum.
type MediaResolution string

// MediaResolution values.
const (
	MediaResolutionUnspecified MediaResolution = "MEDIA_RESOLUTION_UNSPECIFIED"
	MediaResolutionLow         MediaResolution = "LOW"
	MediaResolutionMedium      MediaResolution = "MEDIUM"
	MediaResolutionHigh        MediaResolution = "HIGH"
	MediaResolutionUltraHigh   MediaResolution = "ULTRA_HIGH"
)

var mediaResolutionNames = map[int32]string{0: "MEDIA_RESOLUTION_UNSPECIFIED", 1: "LOW", 2: "MEDIUM", 3: "HIGH", 4: "ULTRA_HIGH"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e MediaResolution) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *MediaResolution) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), mediaResolutionNames)
}

// AudioContentMimeType mirrors the genai.AudioContent.MimeType enum.
type AudioContentMimeType string

// AudioContentMimeType values.
const (
	AudioContentMimeTypeUnspecified     AudioContentMimeType = "TYPE_UNSPECIFIED"
	AudioContentMimeTypeWav             AudioContentMimeType = "TYPE_WAV"
	AudioContentMimeTypeMp3             AudioContentMimeType = "TYPE_MP3"
	AudioContentMimeTypeAiff            AudioContentMimeType = "TYPE_AIFF"
	AudioContentMimeTypeAac             AudioContentMimeType = "TYPE_AAC"
	AudioContentMimeTypeOgg             AudioContentMimeType = "TYPE_OGG"
	AudioContentMimeTypeFlac            AudioContentMimeType = "TYPE_FLAC"
	AudioContentMimeTypeMpeg            AudioContentMimeType = "TYPE_MPEG"
	AudioContentMimeTypeM4a             AudioContentMimeType = "TYPE_M4A"
	AudioContentMimeTypeL16             AudioContentMimeType = "TYPE_L16"
	AudioContentMimeTypeS16le           AudioContentMimeType = "TYPE_S16LE"
	AudioContentMimeTypeOpus            AudioContentMimeType = "TYPE_OPUS"
	AudioContentMimeTypeAlaw            AudioContentMimeType = "TYPE_ALAW"
	AudioContentMimeTypeMulaw           AudioContentMimeType = "TYPE_MULAW"
	AudioContentMimeTypeVideoAudioS16le AudioContentMimeType = "TYPE_VIDEO_AUDIO_S16LE"
	AudioContentMimeTypeWebm            AudioContentMimeType = "TYPE_WEBM"
)

var audioContentMimeTypeNames = map[int32]string{0: "TYPE_UNSPECIFIED", 1: "TYPE_WAV", 2: "TYPE_MP3", 3: "TYPE_AIFF", 4: "TYPE_AAC", 5: "TYPE_OGG", 6: "TYPE_FLAC", 7: "TYPE_MPEG", 8: "TYPE_M4A", 9: "TYPE_L16", 10: "TYPE_S16LE", 11: "TYPE_OPUS", 12: "TYPE_ALAW", 13: "TYPE_MULAW", 14: "TYPE_VIDEO_AUDIO_S16LE", 15: "TYPE_WEBM"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e AudioContentMimeType) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *AudioContentMimeType) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), audioContentMimeTypeNames)
}

// DocumentContentMimeType mirrors the genai.DocumentContent.MimeType enum.
type DocumentContentMimeType string

// DocumentContentMimeType values.
const (
	DocumentContentMimeTypeUnspecified DocumentContentMimeType = "TYPE_UNSPECIFIED"
	DocumentContentMimeTypePdf         DocumentContentMimeType = "TYPE_PDF"
	DocumentContentMimeTypeCsv         DocumentContentMimeType = "TYPE_CSV"
)

var documentContentMimeTypeNames = map[int32]string{0: "TYPE_UNSPECIFIED", 1: "TYPE_PDF", 2: "TYPE_CSV"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e DocumentContentMimeType) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *DocumentContentMimeType) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), documentContentMimeTypeNames)
}

// VideoContentProcessing mirrors the genai.VideoContent.Processing enum.
type VideoContentProcessing string

// VideoContentProcessing values.
const (
	VideoContentProcessingUnspecified VideoContentProcessing = "PROCESSING_UNSPECIFIED"
	VideoContentProcessingStatic      VideoContentProcessing = "STATIC"
	VideoContentProcessingAgentic     VideoContentProcessing = "AGENTIC"
)

var videoContentProcessingNames = map[int32]string{0: "PROCESSING_UNSPECIFIED", 1: "STATIC", 2: "AGENTIC"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e VideoContentProcessing) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *VideoContentProcessing) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), videoContentProcessingNames)
}

// VideoContentMimeType mirrors the genai.VideoContent.MimeType enum.
type VideoContentMimeType string

// VideoContentMimeType values.
const (
	VideoContentMimeTypeUnspecified VideoContentMimeType = "TYPE_UNSPECIFIED"
	VideoContentMimeTypeMp4         VideoContentMimeType = "TYPE_MP4"
	VideoContentMimeTypeMpeg        VideoContentMimeType = "TYPE_MPEG"
	VideoContentMimeTypeMpg         VideoContentMimeType = "TYPE_MPG"
	VideoContentMimeTypeMov         VideoContentMimeType = "TYPE_MOV"
	VideoContentMimeTypeAvi         VideoContentMimeType = "TYPE_AVI"
	VideoContentMimeTypeXFlv        VideoContentMimeType = "TYPE_X_FLV"
	VideoContentMimeTypeWebm        VideoContentMimeType = "TYPE_WEBM"
	VideoContentMimeTypeWmv         VideoContentMimeType = "TYPE_WMV"
	VideoContentMimeType3gpp        VideoContentMimeType = "TYPE_3GPP"
	VideoContentMimeTypeYtBeyond    VideoContentMimeType = "TYPE_YT_BEYOND"
	VideoContentMimeTypeJpeg2000    VideoContentMimeType = "TYPE_JPEG2000"
)

var videoContentMimeTypeNames = map[int32]string{0: "TYPE_UNSPECIFIED", 1: "TYPE_MP4", 2: "TYPE_MPEG", 3: "TYPE_MPG", 4: "TYPE_MOV", 5: "TYPE_AVI", 6: "TYPE_X_FLV", 7: "TYPE_WEBM", 8: "TYPE_WMV", 9: "TYPE_3GPP", 10: "TYPE_YT_BEYOND", 11: "TYPE_JPEG2000"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e VideoContentMimeType) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *VideoContentMimeType) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), videoContentMimeTypeNames)
}

// CodeExecutionCallContentCodeExecutionCallArgumentsLanguage mirrors the genai.CodeExecutionCallContent.CodeExecutionCallArguments.Language enum.
type CodeExecutionCallContentCodeExecutionCallArgumentsLanguage string

// CodeExecutionCallContentCodeExecutionCallArgumentsLanguage values.
const (
	CodeExecutionCallContentCodeExecutionCallArgumentsLanguageUnspecified CodeExecutionCallContentCodeExecutionCallArgumentsLanguage = "LANGUAGE_UNSPECIFIED"
	CodeExecutionCallContentCodeExecutionCallArgumentsLanguagePython      CodeExecutionCallContentCodeExecutionCallArgumentsLanguage = "PYTHON"
)

var codeExecutionCallContentCodeExecutionCallArgumentsLanguageNames = map[int32]string{0: "LANGUAGE_UNSPECIFIED", 1: "PYTHON"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e CodeExecutionCallContentCodeExecutionCallArgumentsLanguage) MarshalJSON() ([]byte, error) {
	return marshalEnum(string(e))
}

// UnmarshalJSON accepts the value name or its number.
func (e *CodeExecutionCallContentCodeExecutionCallArgumentsLanguage) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), codeExecutionCallContentCodeExecutionCallArgumentsLanguageNames)
}

// GoogleSearchSearchType mirrors the genai.GoogleSearch.SearchType enum.
type GoogleSearchSearchType string

// GoogleSearchSearchType values.
const (
	GoogleSearchSearchTypeUnspecified GoogleSearchSearchType = "SEARCH_TYPE_UNSPECIFIED"
	GoogleSearchSearchTypeWebSearch   GoogleSearchSearchType = "SEARCH_TYPE_WEB_SEARCH"
	GoogleSearchSearchTypeImageSearch GoogleSearchSearchType = "SEARCH_TYPE_IMAGE_SEARCH"
)

var googleSearchSearchTypeNames = map[int32]string{0: "SEARCH_TYPE_UNSPECIFIED", 1: "SEARCH_TYPE_WEB_SEARCH", 2: "SEARCH_TYPE_IMAGE_SEARCH"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e GoogleSearchSearchType) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *GoogleSearchSearchType) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), googleSearchSearchTypeNames)
}

// URLContextResultContentURLContextResultStatus mirrors the genai.UrlContextResultContent.UrlContextResult.Status enum.
type URLContextResultContentURLContextResultStatus string

// URLContextResultContentURLContextResultStatus values.
const (
	URLContextResultContentURLContextResultStatusUnspecified URLContextResultContentURLContextResultStatus = "STATUS_UNSPECIFIED"
	URLContextResultContentURLContextResultStatusSuccess     URLContextResultContentURLContextResultStatus = "SUCCESS"
	URLContextResultContentURLContextResultStatusError       URLContextResultContentURLContextResultStatus = "ERROR"
	URLContextResultContentURLContextResultStatusPaywall     URLContextResultContentURLContextResultStatus = "PAYWALL"
	URLContextResultContentURLContextResultStatusUnsafe      URLContextResultContentURLContextResultStatus = "UNSAFE"
)

var uRLContextResultContentURLContextResultStatusNames = map[int32]string{0: "STATUS_UNSPECIFIED", 1: "SUCCESS", 2: "ERROR", 3: "PAYWALL", 4: "UNSAFE"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e URLContextResultContentURLContextResultStatus) MarshalJSON() ([]byte, error) {
	return marshalEnum(string(e))
}

// UnmarshalJSON accepts the value name or its number.
func (e *URLContextResultContentURLContextResultStatus) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), uRLContextResultContentURLContextResultStatusNames)
}

// Struct mirrors the genai.Struct message.
type Struct struct {
	Fields []*Field `json:"fields,omitempty"`
}

// GetFields returns Fields, or nil when x is nil.
func (x *Struct) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Field mirrors the genai.Field message.
type Field struct {
	Name  *string `json:"name,omitempty"`
	Value *Value  `json:"value,omitempty"`
}

// GetName returns Name, or the zero value when unset.
func (x *Field) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetValue returns Value, or nil when x is nil.
func (x *Field) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// Value mirrors the genai.Value message.
// At most one of the kind oneof fields (NullValue, NumberValue, StringValue, BoolValue, StructValue, ListValue, ContentValue, FunctionValue) is set.
type Value struct {
	NullValue     *NullValue `json:"nullValue,omitempty"`     // oneof kind
	NumberValue   *float64   `json:"numberValue,omitempty"`   // oneof kind
	StringValue   *string    `json:"stringValue,omitempty"`   // oneof kind
	BoolValue     *bool      `json:"boolValue,omitempty"`     // oneof kind
	StructValue   *Struct    `json:"structValue,omitempty"`   // oneof kind
	ListValue     *ListValue `json:"listValue,omitempty"`     // oneof kind
	ContentValue  *Content   `json:"contentValue,omitempty"`  // oneof kind
	FunctionValue *Function  `json:"functionValue,omitempty"` // oneof kind
}

// GetNullValue returns NullValue, or the zero value when unset.
func (x *Value) GetNullValue() NullValue {
	if x != nil && x.NullValue != nil {
		return *x.NullValue
	}
	return ""
}

// GetNumberValue returns NumberValue, or the zero value when unset.
func (x *Value) GetNumberValue() float64 {
	if x != nil && x.NumberValue != nil {
		return *x.NumberValue
	}
	return 0
}

// GetStringValue returns StringValue, or the zero value when unset.
func (x *Value) GetStringValue() string {
	if x != nil && x.StringValue != nil {
		return *x.StringValue
	}
	return ""
}

// GetBoolValue returns BoolValue, or the zero value when unset.
func (x *Value) GetBoolValue() bool {
	if x != nil && x.BoolValue != nil {
		return *x.BoolValue
	}
	return false
}

// GetStructValue returns StructValue, or nil when x is nil.
func (x *Value) GetStructValue() *Struct {
	if x != nil {
		return x.StructValue
	}
	return nil
}

// GetListValue returns ListValue, or nil when x is nil.
func (x *Value) GetListValue() *ListValue {
	if x != nil {
		return x.ListValue
	}
	return nil
}

// GetContentValue returns ContentValue, or nil when x is nil.
func (x *Value) GetContentValue() *Content {
	if x != nil {
		return x.ContentValue
	}
	return nil
}

// GetFunctionValue returns FunctionValue, or nil when x is nil.
func (x *Value) GetFunctionValue() *Function {
	if x != nil {
		return x.FunctionValue
	}
	return nil
}

// ListValue mirrors the genai.ListValue message.
type ListValue struct {
	Values []*Value `json:"values,omitempty"`
}

// GetValues returns Values, or nil when x is nil.
func (x *ListValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

// Content mirrors the genai.Content message.
// At most one of the type oneof fields (Text, Image, Audio, Document, Video, Thought, ToolCall, ToolResult) is set.
type Content struct {
	Thought    *ThoughtContent    `json:"thought,omitempty"`    // oneof type
	Text       *TextContent       `json:"text,omitempty"`       // oneof type
	Image      *ImageContent      `json:"image,omitempty"`      // oneof type
	Audio      *AudioContent      `json:"audio,omitempty"`      // oneof type
	Document   *DocumentContent   `json:"document,omitempty"`   // oneof type
	Video      *VideoContent      `json:"video,omitempty"`      // oneof type
	ToolCall   *ToolCallContent   `json:"toolCall,omitempty"`   // oneof type
	ToolResult *ToolResultContent `json:"toolResult,omitempty"` // oneof type
}

// GetThought returns Thought, or nil when x is nil.
func (x *Content) GetThought() *ThoughtContent {
	if x != nil {
		return x.Thought
	}
	return nil
}

// GetText returns Text, or nil when x is nil.
func (x *Content) GetText() *TextContent {
	if x != nil {
		return x.Text
	}
	return nil
}

// GetImage returns Image, or nil when x is nil.
func (x *Content) GetImage() *ImageContent {
	if x != nil {
		return x.Image
	}
	return nil
}

// GetAudio returns Audio, or nil when x is nil.
func (x *Content) GetAudio() *AudioContent {
	if x != nil {
		return x.Audio
	}
	return nil
}

// GetDocument returns Document, or nil when x is nil.
func (x *Content) GetDocument() *DocumentContent {
	if x != nil {
		return x.Document
	}
	return nil
}

// GetVideo returns Video, or nil when x is nil.
func (x *Content) GetVideo() *VideoContent {
	if x != nil {
		return x.Video
	}
	return nil
}

// GetToolCall returns ToolCall, or nil when x is nil.
func (x *Content) GetToolCall() *ToolCallContent {
	if x != nil {
		return x.ToolCall
	}
	return nil
}

// GetToolResult returns ToolResult, or nil when x is nil.
func (x *Content) GetToolResult() *ToolResultContent {
	if x != nil {
		return x.ToolResult
	}
	return nil
}

// TextContent mirrors the genai.TextContent message.
type TextContent struct {
	Text        *string                  `json:"text,omitempty"`
	Annotations []*TextContentAnnotation `json:"annotations,omitempty"`
}

// GetText returns Text, or the zero value when unset.
func (x *TextContent) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

// GetAnnotations returns Annotations, or nil when x is nil.
func (x *TextContent) GetAnnotations() []*TextContentAnnotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// TextContentAnnotation mirrors the genai.TextContent.Annotation message.
// At most one of the type oneof fields (URLCitation, FileCitation, PlaceCitation, WordInfo, SpeechMetadata) is set.
type TextContentAnnotation struct {
	StartIndex     *int32            `json:"startIndex,omitempty"`
	EndIndex       *int32            `json:"endIndex,omitempty"`
	URLCitation    *URLCitation      `json:"urlCitation,omitempty"`    // oneof type
	FileCitation   *FileCitation     `json:"fileCitation,omitempty"`   // oneof type
	PlaceCitation  *PlaceCitation    `json:"placeCitation,omitempty"`  // oneof type
	WordInfo       *WordInfo         `json:"wordInfo,omitempty"`       // oneof type
	SpeechMetadata *SpeechAnnotation `json:"speechMetadata,omitempty"` // oneof type
}

// GetStartIndex returns StartIndex, or the zero value when unset.
func (x *TextContentAnnotation) GetStartIndex() int32 {
	if x != nil && x.StartIndex != nil {
		return *x.StartIndex
	}
	return 0
}

// GetEndIndex returns EndIndex, or the zero value when unset.
func (x *TextContentAnnotation) GetEndIndex() int32 {
	if x != nil && x.EndIndex != nil {
		return *x.EndIndex
	}
	return 0
}

// GetURLCitation returns URLCitation, or nil when x is nil.
func (x *TextContentAnnotation) GetURLCitation() *URLCitation {
	if x != nil {
		return x.URLCitation
	}
	return nil
}

// GetFileCitation returns FileCitation, or nil when x is nil.
func (x *TextContentAnnotation) GetFileCitation() *FileCitation {
	if x != nil {
		return x.FileCitation
	}
	return nil
}

// GetPlaceCitation returns PlaceCitation, or nil when x is nil.
func (x *TextContentAnnotation) GetPlaceCitation() *PlaceCitation {
	if x != nil {
		return x.PlaceCitation
	}
	return nil
}

// GetWordInfo returns WordInfo, or nil when x is nil.
func (x *TextContentAnnotation) GetWordInfo() *WordInfo {
	if x != nil {
		return x.WordInfo
	}
	return nil
}

// GetSpeechMetadata returns SpeechMetadata, or nil when x is nil.
func (x *TextContentAnnotation) GetSpeechMetadata() *SpeechAnnotation {
	if x != nil {
		return x.SpeechMetadata
	}
	return nil
}

// URLCitation mirrors the genai.UrlCitation message.
type URLCitation struct {
	URL   *string `json:"url,omitempty"`
	Title *string `json:"title,omitempty"`
}

// GetURL returns URL, or the zero value when unset.
func (x *URLCitation) GetURL() string {
	if x != nil && x.URL != nil {
		return *x.URL
	}
	return ""
}

// GetTitle returns Title, or the zero value when unset.
func (x *URLCitation) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

// FileCitation mirrors the genai.FileCitation message.
type FileCitation struct {
	DocumentURI    *string `json:"documentUri,omitempty"`
	FileName       *string `json:"fileName,omitempty"`
	Source         *string `json:"source,omitempty"`
	CustomMetadata *Struct `json:"customMetadata,omitempty"`
	PageNumber     *int32  `json:"pageNumber,omitempty"`
	MediaID        *string `json:"mediaId,omitempty"`
}

// GetDocumentURI returns DocumentURI, or the zero value when unset.
func (x *FileCitation) GetDocumentURI() string {
	if x != nil && x.DocumentURI != nil {
		return *x.DocumentURI
	}
	return ""
}

// GetFileName returns FileName, or the zero value when unset.
func (x *FileCitation) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

// GetSource returns Source, or the zero value when unset.
func (x *FileCitation) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

// GetCustomMetadata returns CustomMetadata, or nil when x is nil.
func (x *FileCitation) GetCustomMetadata() *Struct {
	if x != nil {
		return x.CustomMetadata
	}
	return nil
}

// GetPageNumber returns PageNumber, or the zero value when unset.
func (x *FileCitation) GetPageNumber() int32 {
	if x != nil && x.PageNumber != nil {
		return *x.PageNumber
	}
	return 0
}

// GetMediaID returns MediaID, or the zero value when unset.
func (x *FileCitation) GetMediaID() string {
	if x != nil && x.MediaID != nil {
		return *x.MediaID
	}
	return ""
}

// PlaceCitation mirrors the genai.PlaceCitation message.
type PlaceCitation struct {
	PlaceID        *string          `json:"placeId,omitempty"`
	Name           *string          `json:"name,omitempty"`
	URL            *string          `json:"url,omitempty"`
	ReviewSnippets []*ReviewSnippet `json:"reviewSnippets,omitempty"`
}

// GetPlaceID returns PlaceID, or the zero value when unset.
func (x *PlaceCitation) GetPlaceID() string {
	if x != nil && x.PlaceID != nil {
		return *x.PlaceID
	}
	return ""
}

// GetName returns Name, or the zero value when unset.
func (x *PlaceCitation) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetURL returns URL, or the zero value when unset.
func (x *PlaceCitation) GetURL() string {
	if x != nil && x.URL != nil {
		return *x.URL
	}
	return ""
}

// GetReviewSnippets returns ReviewSnippets, or nil when x is nil.
func (x *PlaceCitation) GetReviewSnippets() []*ReviewSnippet {
	if x != nil {
		return x.ReviewSnippets
	}
	return nil
}

// ReviewSnippet mirrors the genai.ReviewSnippet message.
type ReviewSnippet struct {
	Title    *string `json:"title,omitempty"`
	URL      *string `json:"url,omitempty"`
	ReviewID *string `json:"reviewId,omitempty"`
}

// GetTitle returns Title, or the zero value when unset.
func (x *ReviewSnippet) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

// GetURL returns URL, or the zero value when unset.
func (x *ReviewSnippet) GetURL() string {
	if x != nil && x.URL != nil {
		return *x.URL
	}
	return ""
}

// GetReviewID returns ReviewID, or the zero value when unset.
func (x *ReviewSnippet) GetReviewID() string {
	if x != nil && x.ReviewID != nil {
		return *x.ReviewID
	}
	return ""
}

// WordInfo mirrors the genai.WordInfo message.
type WordInfo struct {
	Text        *string   `json:"text,omitempty"`
	StartOffset *Duration `json:"startOffset,omitempty"`
	EndOffset   *Duration `json:"endOffset,omitempty"`
	Speaker     *string   `json:"speaker,omitempty"`
}

// GetText returns Text, or the zero value when unset.
func (x *WordInfo) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

// GetStartOffset returns StartOffset, or nil when x is nil.
func (x *WordInfo) GetStartOffset() *Duration {
	if x != nil {
		return x.StartOffset
	}
	return nil
}

// GetEndOffset returns EndOffset, or nil when x is nil.
func (x *WordInfo) GetEndOffset() *Duration {
	if x != nil {
		return x.EndOffset
	}
	return nil
}

// GetSpeaker returns Speaker, or the zero value when unset.
func (x *WordInfo) GetSpeaker() string {
	if x != nil && x.Speaker != nil {
		return *x.Speaker
	}
	return ""
}

// SpeechAnnotation mirrors the genai.SpeechAnnotation message.
type SpeechAnnotation struct {
	Speaker *string `json:"speaker,omitempty"`
	Style   *string `json:"style,omitempty"`
}

// GetSpeaker returns Speaker, or the zero value when unset.
func (x *SpeechAnnotation) GetSpeaker() string {
	if x != nil && x.Speaker != nil {
		return *x.Speaker
	}
	return ""
}

// GetStyle returns Style, or the zero value when unset.
func (x *SpeechAnnotation) GetStyle() string {
	if x != nil && x.Style != nil {
		return *x.Style
	}
	return ""
}

// ImageContent mirrors the genai.ImageContent message.
// At most one of the data_or_uri oneof fields (Data, URI) is set.
type ImageContent struct {
	MimeType       *ImageContentMimeType `json:"legacy_mime_type_enum,omitempty" proto:"mime_type"`
	Data           []byte                `json:"data,omitzero"` // oneof data_or_uri
	Resolution     *MediaResolution      `json:"resolution,omitempty"`
	URI            *string               `json:"uri,omitempty"` // oneof data_or_uri
	MimeTypeString *string               `json:"mimeTypeString,omitempty"`
}

// GetMimeType returns MimeType, or the zero value when unset.
func (x *ImageContent) GetMimeType() ImageContentMimeType {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

// GetData returns Data, or nil when x is nil.
func (x *ImageContent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetResolution returns Resolution, or the zero value when unset.
func (x *ImageContent) GetResolution() MediaResolution {
	if x != nil && x.Resolution != nil {
		return *x.Resolution
	}
	return ""
}

// GetURI returns URI, or the zero value when unset.
func (x *ImageContent) GetURI() string {
	if x != nil && x.URI != nil {
		return *x.URI
	}
	return ""
}

// GetMimeTypeString returns MimeTypeString, or the zero value when unset.
func (x *ImageContent) GetMimeTypeString() string {
	if x != nil && x.MimeTypeString != nil {
		return *x.MimeTypeString
	}
	return ""
}

// AudioContent mirrors the genai.AudioContent message.
// At most one of the data_or_uri oneof fields (Data, URI) is set.
type AudioContent struct {
	MimeType       *AudioContentMimeType `json:"legacy_mime_type_enum,omitempty" proto:"mime_type"`
	Data           []byte                `json:"data,omitzero"` // oneof data_or_uri
	URI            *string               `json:"uri,omitempty"` // oneof data_or_uri
	Channels       *int32                `json:"channels,omitempty"`
	SampleRate     *int32                `json:"sampleRate,omitempty"`
	MimeTypeString *string               `json:"mimeTypeString,omitempty"`
}

// GetMimeType returns MimeType, or the zero value when unset.
func (x *AudioContent) GetMimeType() AudioContentMimeType {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

// GetData returns Data, or nil when x is nil.
func (x *AudioContent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetURI returns URI, or the zero value when unset.
func (x *AudioContent) GetURI() string {
	if x != nil && x.URI != nil {
		return *x.URI
	}
	return ""
}

// GetChannels returns Channels, or the zero value when unset.
func (x *AudioContent) GetChannels() int32 {
	if x != nil && x.Channels != nil {
		return *x.Channels
	}
	return 0
}

// GetSampleRate returns SampleRate, or the zero value when unset.
func (x *AudioContent) GetSampleRate() int32 {
	if x != nil && x.SampleRate != nil {
		return *x.SampleRate
	}
	return 0
}

// GetMimeTypeString returns MimeTypeString, or the zero value when unset.
func (x *AudioContent) GetMimeTypeString() string {
	if x != nil && x.MimeTypeString != nil {
		return *x.MimeTypeString
	}
	return ""
}

// DocumentContent mirrors the genai.DocumentContent message.
// At most one of the data_or_uri oneof fields (Data, URI) is set.
type DocumentContent struct {
	MimeType       *DocumentContentMimeType `json:"legacy_mime_type_enum,omitempty" proto:"mime_type"`
	Data           []byte                   `json:"data,omitzero"` // oneof data_or_uri
	URI            *string                  `json:"uri,omitempty"` // oneof data_or_uri
	MimeTypeString *string                  `json:"mimeTypeString,omitempty"`
}

// GetMimeType returns MimeType, or the zero value when unset.
func (x *DocumentContent) GetMimeType() DocumentContentMimeType {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

// GetData returns Data, or nil when x is nil.
func (x *DocumentContent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetURI returns URI, or the zero value when unset.
func (x *DocumentContent) GetURI() string {
	if x != nil && x.URI != nil {
		return *x.URI
	}
	return ""
}

// GetMimeTypeString returns MimeTypeString, or the zero value when unset.
func (x *DocumentContent) GetMimeTypeString() string {
	if x != nil && x.MimeTypeString != nil {
		return *x.MimeTypeString
	}
	return ""
}

// VideoContent mirrors the genai.VideoContent message.
// At most one of the data_or_uri oneof fields (Data, URI) is set.
// At most one of the processing oneof fields (ProcessingType, ProcessingConfig) is set.
type VideoContent struct {
	MimeType         *VideoContentMimeType        `json:"legacy_mime_type_enum,omitempty" proto:"mime_type"`
	Data             []byte                       `json:"data,omitzero"` // oneof data_or_uri
	Resolution       *MediaResolution             `json:"resolution,omitempty"`
	URI              *string                      `json:"uri,omitempty"` // oneof data_or_uri
	MimeTypeString   *string                      `json:"mimeTypeString,omitempty"`
	Name             *string                      `json:"name,omitempty"`
	ProcessingType   *VideoContentProcessing      `json:"processingType,omitempty"`   // oneof processing
	ProcessingConfig *VideoContentMediaProcessing `json:"processingConfig,omitempty"` // oneof processing
}

// GetMimeType returns MimeType, or the zero value when unset.
func (x *VideoContent) GetMimeType() VideoContentMimeType {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

// GetData returns Data, or nil when x is nil.
func (x *VideoContent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetResolution returns Resolution, or the zero value when unset.
func (x *VideoContent) GetResolution() MediaResolution {
	if x != nil && x.Resolution != nil {
		return *x.Resolution
	}
	return ""
}

// GetURI returns URI, or the zero value when unset.
func (x *VideoContent) GetURI() string {
	if x != nil && x.URI != nil {
		return *x.URI
	}
	return ""
}

// GetMimeTypeString returns MimeTypeString, or the zero value when unset.
func (x *VideoContent) GetMimeTypeString() string {
	if x != nil && x.MimeTypeString != nil {
		return *x.MimeTypeString
	}
	return ""
}

// GetName returns Name, or the zero value when unset.
func (x *VideoContent) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetProcessingType returns ProcessingType, or the zero value when unset.
func (x *VideoContent) GetProcessingType() VideoContentProcessing {
	if x != nil && x.ProcessingType != nil {
		return *x.ProcessingType
	}
	return ""
}

// GetProcessingConfig returns ProcessingConfig, or nil when x is nil.
func (x *VideoContent) GetProcessingConfig() *VideoContentMediaProcessing {
	if x != nil {
		return x.ProcessingConfig
	}
	return nil
}

// VideoContentMediaProcessing mirrors the genai.VideoContent.MediaProcessing message.
// At most one of the type oneof fields (Static) is set.
type VideoContentMediaProcessing struct {
	Static *VideoContentStaticMediaProcessing `json:"static,omitempty"` // oneof type
}

// GetStatic returns Static, or nil when x is nil.
func (x *VideoContentMediaProcessing) GetStatic() *VideoContentStaticMediaProcessing {
	if x != nil {
		return x.Static
	}
	return nil
}

// VideoContentStaticMediaProcessing mirrors the genai.VideoContent.StaticMediaProcessing message.
type VideoContentStaticMediaProcessing struct {
	StartOffset *Duration `json:"startOffset,omitempty"`
	EndOffset   *Duration `json:"endOffset,omitempty"`
	Fps         *float64  `json:"fps,omitempty"`
}

// GetStartOffset returns StartOffset, or nil when x is nil.
func (x *VideoContentStaticMediaProcessing) GetStartOffset() *Duration {
	if x != nil {
		return x.StartOffset
	}
	return nil
}

// GetEndOffset returns EndOffset, or nil when x is nil.
func (x *VideoContentStaticMediaProcessing) GetEndOffset() *Duration {
	if x != nil {
		return x.EndOffset
	}
	return nil
}

// GetFps returns Fps, or the zero value when unset.
func (x *VideoContentStaticMediaProcessing) GetFps() float64 {
	if x != nil && x.Fps != nil {
		return *x.Fps
	}
	return 0
}

// ThoughtContent mirrors the genai.ThoughtContent message.
type ThoughtContent struct {
	Signature []byte                   `json:"signature,omitzero"`
	Summary   []*ThoughtSummaryContent `json:"summary,omitempty"`
}

// GetSignature returns Signature, or nil when x is nil.
func (x *ThoughtContent) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// GetSummary returns Summary, or nil when x is nil.
func (x *ThoughtContent) GetSummary() []*ThoughtSummaryContent {
	if x != nil {
		return x.Summary
	}
	return nil
}

// ThoughtSummaryContent mirrors the genai.ThoughtSummaryContent message.
// At most one of the type oneof fields (Text, Image) is set.
type ThoughtSummaryContent struct {
	Text  *TextContent  `json:"text,omitempty"`  // oneof type
	Image *ImageContent `json:"image,omitempty"` // oneof type
}

// GetText returns Text, or nil when x is nil.
func (x *ThoughtSummaryContent) GetText() *TextContent {
	if x != nil {
		return x.Text
	}
	return nil
}

// GetImage returns Image, or nil when x is nil.
func (x *ThoughtSummaryContent) GetImage() *ImageContent {
	if x != nil {
		return x.Image
	}
	return nil
}

// ToolCallContent mirrors the genai.ToolCallContent message.
// At most one of the type oneof fields (FunctionCall, CodeExecutionCall, URLContextCall, MCPServerToolCall, GoogleSearchCall, FileSearchCall, GoogleMapsCall) is set.
type ToolCallContent struct {
	ID                *string                   `json:"id,omitempty"`
	FunctionCall      *FunctionCallContent      `json:"functionCall,omitempty"`      // oneof type
	CodeExecutionCall *CodeExecutionCallContent `json:"codeExecutionCall,omitempty"` // oneof type
	URLContextCall    *URLContextCallContent    `json:"urlContextCall,omitempty"`    // oneof type
	MCPServerToolCall *MCPServerToolCallContent `json:"mcpServerToolCall,omitempty"` // oneof type
	GoogleSearchCall  *GoogleSearchCallContent  `json:"googleSearchCall,omitempty"`  // oneof type
	FileSearchCall    *FileSearchCallContent    `json:"fileSearchCall,omitempty"`    // oneof type
	Signature         []byte                    `json:"signature,omitzero"`
	GoogleMapsCall    *GoogleMapsCallContent    `json:"googleMapsCall,omitempty"` // oneof type
}

// GetID returns ID, or the zero value when unset.
func (x *ToolCallContent) GetID() string {
	if x != nil && x.ID != nil {
		return *x.ID
	}
	return ""
}

// GetFunctionCall returns FunctionCall, or nil when x is nil.
func (x *ToolCallContent) GetFunctionCall() *FunctionCallContent {
	if x != nil {
		return x.FunctionCall
	}
	return nil
}

// GetCodeExecutionCall returns CodeExecutionCall, or nil when x is nil.
func (x *ToolCallContent) GetCodeExecutionCall() *CodeExecutionCallContent {
	if x != nil {
		return x.CodeExecutionCall
	}
	return nil
}

// GetURLContextCall returns URLContextCall, or nil when x is nil.
func (x *ToolCallContent) GetURLContextCall() *URLContextCallContent {
	if x != nil {
		return x.URLContextCall
	}
	return nil
}

// GetMCPServerToolCall returns MCPServerToolCall, or nil when x is nil.
func (x *ToolCallContent) GetMCPServerToolCall() *MCPServerToolCallContent {
	if x != nil {
		return x.MCPServerToolCall
	}
	return nil
}

// GetGoogleSearchCall returns GoogleSearchCall, or nil when x is nil.
func (x *ToolCallContent) GetGoogleSearchCall() *GoogleSearchCallContent {
	if x != nil {
		return x.GoogleSearchCall
	}
	return nil
}

// GetFileSearchCall returns FileSearchCall, or nil when x is nil.
func (x *ToolCallContent) GetFileSearchCall() *FileSearchCallContent {
	if x != nil {
		return x.FileSearchCall
	}
	return nil
}

// GetSignature returns Signature, or nil when x is nil.
func (x *ToolCallContent) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// GetGoogleMapsCall returns GoogleMapsCall, or nil when x is nil.
func (x *ToolCallContent) GetGoogleMapsCall() *GoogleMapsCallContent {
	if x != nil {
		return x.GoogleMapsCall
	}
	return nil
}

// FunctionCallContent mirrors the genai.FunctionCallContent message.
type FunctionCallContent struct {
	Name      *string `json:"name,omitempty"`
	Arguments *Struct `json:"arguments,omitempty"`
}

// GetName returns Name, or the zero value when unset.
func (x *FunctionCallContent) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetArguments returns Arguments, or nil when x is nil.
func (x *FunctionCallContent) GetArguments() *Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// CodeExecutionCallContent mirrors the genai.CodeExecutionCallContent message.
type CodeExecutionCallContent struct {
	Arguments *CodeExecutionCallContentCodeExecutionCallArguments `json:"arguments,omitempty"`
}

// GetArguments returns Arguments, or nil when x is nil.
func (x *CodeExecutionCallContent) GetArguments() *CodeExecutionCallContentCodeExecutionCallArguments {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// CodeExecutionCallContentCodeExecutionCallArguments mirrors the genai.CodeExecutionCallContent.CodeExecutionCallArguments message.
type CodeExecutionCallContentCodeExecutionCallArguments struct {
	Language *CodeExecutionCallContentCodeExecutionCallArgumentsLanguage `json:"language,omitempty"`
	Code     *string                                                     `json:"code,omitempty"`
}

// GetLanguage returns Language, or the zero value when unset.
func (x *CodeExecutionCallContentCodeExecutionCallArguments) GetLanguage() CodeExecutionCallContentCodeExecutionCallArgumentsLanguage {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

// GetCode returns Code, or the zero value when unset.
func (x *CodeExecutionCallContentCodeExecutionCallArguments) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

// URLContextCallContent mirrors the genai.UrlContextCallContent message.
type URLContextCallContent struct {
	Arguments *URLContextCallContentURLContextCallArguments `json:"arguments,omitempty"`
}

// GetArguments returns Arguments, or nil when x is nil.
func (x *URLContextCallContent) GetArguments() *URLContextCallContentURLContextCallArguments {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// URLContextCallContentURLContextCallArguments mirrors the genai.UrlContextCallContent.UrlContextCallArguments message.
type URLContextCallContentURLContextCallArguments struct {
	Urls []string `json:"urls,omitempty"`
}

// GetUrls returns Urls, or nil when x is nil.
func (x *URLContextCallContentURLContextCallArguments) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

// MCPServerToolCallContent mirrors the genai.McpServerToolCallContent message.
type MCPServerToolCallContent struct {
	Name       *string `json:"name,omitempty"`
	ServerName *string `json:"serverName,omitempty"`
	Arguments  *Struct `json:"arguments,omitempty"`
}

// GetName returns Name, or the zero value when unset.
func (x *MCPServerToolCallContent) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetServerName returns ServerName, or the zero value when unset.
func (x *MCPServerToolCallContent) GetServerName() string {
	if x != nil && x.ServerName != nil {
		return *x.ServerName
	}
	return ""
}

// GetArguments returns Arguments, or nil when x is nil.
func (x *MCPServerToolCallContent) GetArguments() *Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// GoogleSearchCallContent mirrors the genai.GoogleSearchCallContent message.
type GoogleSearchCallContent struct {
	Arguments  *GoogleSearchCallContentGoogleSearchCallArguments `json:"arguments,omitempty"`
	SearchType *GoogleSearchSearchType                           `json:"searchType,omitempty"`
}

// GetArguments returns Arguments, or nil when x is nil.
func (x *GoogleSearchCallContent) GetArguments() *GoogleSearchCallContentGoogleSearchCallArguments {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// GetSearchType returns SearchType, or the zero value when unset.
func (x *GoogleSearchCallContent) GetSearchType() GoogleSearchSearchType {
	if x != nil && x.SearchType != nil {
		return *x.SearchType
	}
	return ""
}

// GoogleSearchCallContentGoogleSearchCallArguments mirrors the genai.GoogleSearchCallContent.GoogleSearchCallArguments message.
type GoogleSearchCallContentGoogleSearchCallArguments struct {
	Queries []string `json:"queries,omitempty"`
}

// GetQueries returns Queries, or nil when x is nil.
func (x *GoogleSearchCallContentGoogleSearchCallArguments) GetQueries() []string {
	if x != nil {
		return x.Queries
	}
	return nil
}

// FileSearchCallContent mirrors the genai.FileSearchCallContent message.
type FileSearchCallContent struct {
}

// GoogleMapsCallContent mirrors the genai.GoogleMapsCallContent message.
type GoogleMapsCallContent struct {
	Arguments *GoogleMapsCallContentGoogleMapsCallArguments `json:"arguments,omitempty"`
}

// GetArguments returns Arguments, or nil when x is nil.
func (x *GoogleMapsCallContent) GetArguments() *GoogleMapsCallContentGoogleMapsCallArguments {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// GoogleMapsCallContentGoogleMapsCallArguments mirrors the genai.GoogleMapsCallContent.GoogleMapsCallArguments message.
type GoogleMapsCallContentGoogleMapsCallArguments struct {
	Queries []string `json:"queries,omitempty"`
}

// GetQueries returns Queries, or nil when x is nil.
func (x *GoogleMapsCallContentGoogleMapsCallArguments) GetQueries() []string {
	if x != nil {
		return x.Queries
	}
	return nil
}

// ToolResultContent mirrors the genai.ToolResultContent message.
// At most one of the type oneof fields (FunctionResult, CodeExecutionResult, URLContextResult, GoogleSearchResult, MCPServerToolResult, FileSearchResult, GoogleMapsResult) is set.
type ToolResultContent struct {
	FunctionResult      *FunctionResultContent      `json:"functionResult,omitempty"`      // oneof type
	CodeExecutionResult *CodeExecutionResultContent `json:"codeExecutionResult,omitempty"` // oneof type
	URLContextResult    *URLContextResultContent    `json:"urlContextResult,omitempty"`    // oneof type
	GoogleSearchResult  *GoogleSearchResultContent  `json:"googleSearchResult,omitempty"`  // oneof type
	MCPServerToolResult *MCPServerToolResultContent `json:"mcpServerToolResult,omitempty"` // oneof type
	FileSearchResult    *FileSearchResultContent    `json:"fileSearchResult,omitempty"`    // oneof type
	CallID              *string                     `json:"callId,omitempty"`
	Signature           []byte                      `json:"signature,omitzero"`
	GoogleMapsResult    *GoogleMapsResultContent    `json:"googleMapsResult,omitempty"` // oneof type
}

// GetFunctionResult returns FunctionResult, or nil when x is nil.
func (x *ToolResultContent) GetFunctionResult() *FunctionResultContent {
	if x != nil {
		return x.FunctionResult
	}
	return nil
}

// GetCodeExecutionResult returns CodeExecutionResult, or nil when x is nil.
func (x *ToolResultContent) GetCodeExecutionResult() *CodeExecutionResultContent {
	if x != nil {
		return x.CodeExecutionResult
	}
	return nil
}

// GetURLContextResult returns URLContextResult, or nil when x is nil.
func (x *ToolResultContent) GetURLContextResult() *URLContextResultContent {
	if x != nil {
		return x.URLContextResult
	}
	return nil
}

// GetGoogleSearchResult returns GoogleSearchResult, or nil when x is nil.
func (x *ToolResultContent) GetGoogleSearchResult() *GoogleSearchResultContent {
	if x != nil {
		return x.GoogleSearchResult
	}
	return nil
}

// GetMCPServerToolResult returns MCPServerToolResult, or nil when x is nil.
func (x *ToolResultContent) GetMCPServerToolResult() *MCPServerToolResultContent {
	if x != nil {
		return x.MCPServerToolResult
	}
	return nil
}

// GetFileSearchResult returns FileSearchResult, or nil when x is nil.
func (x *ToolResultContent) GetFileSearchResult() *FileSearchResultContent {
	if x != nil {
		return x.FileSearchResult
	}
	return nil
}

// GetCallID returns CallID, or the zero value when unset.
func (x *ToolResultContent) GetCallID() string {
	if x != nil && x.CallID != nil {
		return *x.CallID
	}
	return ""
}

// GetSignature returns Signature, or nil when x is nil.
func (x *ToolResultContent) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// GetGoogleMapsResult returns GoogleMapsResult, or nil when x is nil.
func (x *ToolResultContent) GetGoogleMapsResult() *GoogleMapsResultContent {
	if x != nil {
		return x.GoogleMapsResult
	}
	return nil
}

// FunctionResultContent mirrors the genai.FunctionResultContent message.
// At most one of the result oneof fields (StructResult, ContentList, StringResult) is set.
type FunctionResultContent struct {
	IsError      *bool                         `json:"isError,omitempty"`
	StructResult *Struct                       `json:"structResult,omitempty"` // oneof result
	StringResult *string                       `json:"stringResult,omitempty"` // oneof result
	Name         *string                       `json:"name,omitempty"`
	ContentList  *FunctionResultSubcontentList `json:"contentList,omitempty"` // oneof result
}

// GetIsError returns IsError, or the zero value when unset.
func (x *FunctionResultContent) GetIsError() bool {
	if x != nil && x.IsError != nil {
		return *x.IsError
	}
	return false
}

// GetStructResult returns StructResult, or nil when x is nil.
func (x *FunctionResultContent) GetStructResult() *Struct {
	if x != nil {
		return x.StructResult
	}
	return nil
}

// GetStringResult returns StringResult, or the zero value when unset.
func (x *FunctionResultContent) GetStringResult() string {
	if x != nil && x.StringResult != nil {
		return *x.StringResult
	}
	return ""
}

// GetName returns Name, or the zero value when unset.
func (x *FunctionResultContent) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetContentList returns ContentList, or nil when x is nil.
func (x *FunctionResultContent) GetContentList() *FunctionResultSubcontentList {
	if x != nil {
		return x.ContentList
	}
	return nil
}

// FunctionResultSubcontentList mirrors the genai.FunctionResultSubcontentList message.
type FunctionResultSubcontentList struct {
	Contents []*FunctionResultSubcontent `json:"contents,omitempty"`
}

// GetContents returns Contents, or nil when x is nil.
func (x *FunctionResultSubcontentList) GetContents() []*FunctionResultSubcontent {
	if x != nil {
		return x.Contents
	}
	return nil
}

// FunctionResultSubcontent mirrors the genai.FunctionResultSubcontent message.
// At most one of the type oneof fields (Text, Image) is set.
type FunctionResultSubcontent struct {
	Text  *TextContent  `json:"text,omitempty"`  // oneof type
	Image *ImageContent `json:"image,omitempty"` // oneof type
}

// GetText returns Text, or nil when x is nil.
func (x *FunctionResultSubcontent) GetText() *TextContent {
	if x != nil {
		return x.Text
	}
	return nil
}

// GetImage returns Image, or nil when x is nil.
func (x *FunctionResultSubcontent) GetImage() *ImageContent {
	if x != nil {
		return x.Image
	}
	return nil
}

// CodeExecutionResultContent mirrors the genai.CodeExecutionResultContent message.
type CodeExecutionResultContent struct {
	Result  *string `json:"result,omitempty"`
	IsError *bool   `json:"isError,omitempty"`
}

// GetResult returns Result, or the zero value when unset.
func (x *CodeExecutionResultContent) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

// GetIsError returns IsError, or the zero value when unset.
func (x *CodeExecutionResultContent) GetIsError() bool {
	if x != nil && x.IsError != nil {
		return *x.IsError
	}
	return false
}

// URLContextResultContent mirrors the genai.UrlContextResultContent message.
type URLContextResultContent struct {
	Result  []*URLContextResultContentURLContextResult `json:"result,omitempty"`
	IsError *bool                                      `json:"isError,omitempty"`
}

// GetResult returns Result, or nil when x is nil.
func (x *URLContextResultContent) GetResult() []*URLContextResultContentURLContextResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// GetIsError returns IsError, or the zero value when unset.
func (x *URLContextResultContent) GetIsError() bool {
	if x != nil && x.IsError != nil {
		return *x.IsError
	}
	return false
}

// URLContextResultContentURLContextResult mirrors the genai.UrlContextResultContent.UrlContextResult message.
type URLContextResultContentURLContextResult struct {
	URL    *string                                        `json:"url,omitempty"`
	Status *URLContextResultContentURLContextResultStatus `json:"status,omitempty"`
}

// GetURL returns URL, or the zero value when unset.
func (x *URLContextResultContentURLContextResult) GetURL() string {
	if x != nil && x.URL != nil {
		return *x.URL
	}
	return ""
}

// GetStatus returns Status, or the zero value when unset.
func (x *URLContextResultContentURLContextResult) GetStatus() URLContextResultContentURLContextResultStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

// GoogleSearchResultContent mirrors the genai.GoogleSearchResultContent message.
type GoogleSearchResultContent struct {
	Result  []*GoogleSearchResultContentGoogleSearchResult `json:"result,omitempty"`
	IsError *bool                                          `json:"isError,omitempty"`
}

// GetResult returns Result, or nil when x is nil.
func (x *GoogleSearchResultContent) GetResult() []*GoogleSearchResultContentGoogleSearchResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// GetIsError returns IsError, or the zero value when unset.
func (x *GoogleSearchResultContent) GetIsError() bool {
	if x != nil && x.IsError != nil {
		return *x.IsError
	}
	return false
}

// GoogleSearchResultContentGoogleSearchResult mirrors the genai.GoogleSearchResultContent.GoogleSearchResult message.
type GoogleSearchResultContentGoogleSearchResult struct {
	SearchSuggestions *string `json:"searchSuggestions,omitempty"`
}

// GetSearchSuggestions returns SearchSuggestions, or the zero value when unset.
func (x *GoogleSearchResultContentGoogleSearchResult) GetSearchSuggestions() string {
	if x != nil && x.SearchSuggestions != nil {
		return *x.SearchSuggestions
	}
	return ""
}

// MCPServerToolResultContent mirrors the genai.McpServerToolResultContent message.
// At most one of the result oneof fields (StructResult, ContentList, StringResult) is set.
type MCPServerToolResultContent struct {
	Name         *string                       `json:"name,omitempty"`
	ServerName   *string                       `json:"serverName,omitempty"`
	StructResult *Struct                       `json:"structResult,omitempty"` // oneof result
	StringResult *string                       `json:"stringResult,omitempty"` // oneof result
	ContentList  *FunctionResultSubcontentList `json:"contentList,omitempty"`  // oneof result
}

// GetName returns Name, or the zero value when unset.
func (x *MCPServerToolResultContent) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetServerName returns ServerName, or the zero value when unset.
func (x *MCPServerToolResultContent) GetServerName() string {
	if x != nil && x.ServerName != nil {
		return *x.ServerName
	}
	return ""
}

// GetStructResult returns StructResult, or nil when x is nil.
func (x *MCPServerToolResultContent) GetStructResult() *Struct {
	if x != nil {
		return x.StructResult
	}
	return nil
}

// GetStringResult returns StringResult, or the zero value when unset.
func (x *MCPServerToolResultContent) GetStringResult() string {
	if x != nil && x.StringResult != nil {
		return *x.StringResult
	}
	return ""
}

// GetContentList returns ContentList, or nil when x is nil.
func (x *MCPServerToolResultContent) GetContentList() *FunctionResultSubcontentList {
	if x != nil {
		return x.ContentList
	}
	return nil
}

// FileSearchResultContent mirrors the genai.FileSearchResultContent message.
type FileSearchResultContent struct {
	Result []*FileSearchResultContentFileSearchResult `json:"result,omitempty"`
}

// GetResult returns Result, or nil when x is nil.
func (x *FileSearchResultContent) GetResult() []*FileSearchResultContentFileSearchResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// FileSearchResultContentFileSearchResult mirrors the genai.FileSearchResultContent.FileSearchResult message.
type FileSearchResultContentFileSearchResult struct {
}

// GoogleMapsResultContent mirrors the genai.GoogleMapsResultContent message.
type GoogleMapsResultContent struct {
	Result []*GoogleMapsResultContentGoogleMapsResult `json:"result,omitempty"`
}

// GetResult returns Result, or nil when x is nil.
func (x *GoogleMapsResultContent) GetResult() []*GoogleMapsResultContentGoogleMapsResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// GoogleMapsResultContentGoogleMapsResult mirrors the genai.GoogleMapsResultContent.GoogleMapsResult message.
type GoogleMapsResultContentGoogleMapsResult struct {
	Places             []*GoogleMapsResultContentGoogleMapsResultPlaces `json:"places,omitempty"`
	WidgetContextToken *string                                          `json:"widgetContextToken,omitempty"`
}

// GetPlaces returns Places, or nil when x is nil.
func (x *GoogleMapsResultContentGoogleMapsResult) GetPlaces() []*GoogleMapsResultContentGoogleMapsResultPlaces {
	if x != nil {
		return x.Places
	}
	return nil
}

// GetWidgetContextToken returns WidgetContextToken, or the zero value when unset.
func (x *GoogleMapsResultContentGoogleMapsResult) GetWidgetContextToken() string {
	if x != nil && x.WidgetContextToken != nil {
		return *x.WidgetContextToken
	}
	return ""
}

// GoogleMapsResultContentGoogleMapsResultPlaces mirrors the genai.GoogleMapsResultContent.GoogleMapsResult.Places message.
type GoogleMapsResultContentGoogleMapsResultPlaces struct {
	PlaceID        *string          `json:"placeId,omitempty"`
	Name           *string          `json:"name,omitempty"`
	URL            *string          `json:"url,omitempty"`
	ReviewSnippets []*ReviewSnippet `json:"reviewSnippets,omitempty"`
}

// GetPlaceID returns PlaceID, or the zero value when unset.
func (x *GoogleMapsResultContentGoogleMapsResultPlaces) GetPlaceID() string {
	if x != nil && x.PlaceID != nil {
		return *x.PlaceID
	}
	return ""
}

// GetName returns Name, or the zero value when unset.
func (x *GoogleMapsResultContentGoogleMapsResultPlaces) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetURL returns URL, or the zero value when unset.
func (x *GoogleMapsResultContentGoogleMapsResultPlaces) GetURL() string {
	if x != nil && x.URL != nil {
		return *x.URL
	}
	return ""
}

// GetReviewSnippets returns ReviewSnippets, or nil when x is nil.
func (x *GoogleMapsResultContentGoogleMapsResultPlaces) GetReviewSnippets() []*ReviewSnippet {
	if x != nil {
		return x.ReviewSnippets
	}
	return nil
}

// Function mirrors the genai.Function message.
type Function struct {
	Name             *string `json:"name,omitempty"`
	Description      *string `json:"description,omitempty"`
	Parameters       *Value  `json:"parameters,omitempty"`
	Response         *Value  `json:"response,omitempty"`
	DeferLoading     *bool   `json:"deferLoading,omitempty"`
	ShortDescription *string `json:"shortDescription,omitempty"`
}

// GetName returns Name, or the zero value when unset.
func (x *Function) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetDescription returns Description, or the zero value when unset.
func (x *Function) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// GetParameters returns Parameters, or nil when x is nil.
func (x *Function) GetParameters() *Value {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// GetResponse returns Response, or nil when x is nil.
func (x *Function) GetResponse() *Value {
	if x != nil {
		return x.Response
	}
	return nil
}

// GetDeferLoading returns DeferLoading, or the zero value when unset.
func (x *Function) GetDeferLoading() bool {
	if x != nil && x.DeferLoading != nil {
		return *x.DeferLoading
	}
	return false
}

// GetShortDescription returns ShortDescription, or the zero value when unset.
func (x *Function) GetShortDescription() string {
	if x != nil && x.ShortDescription != nil {
		return *x.ShortDescription
	}
	return ""
}
