// Code generated by testdata/gen_types.py from the google-antigravity v0.1.20
// proto definitions (google/antigravity/proto/localharness.proto). DO NOT EDIT.

package wire

// LifecycleHook mirrors the antigravity.localharness.LifecycleHook enum.
type LifecycleHook string

// LifecycleHook values.
const (
	LifecycleHookUnspecified    LifecycleHook = "LIFECYCLE_HOOK_UNSPECIFIED"
	LifecycleHookOnSessionStart LifecycleHook = "LIFECYCLE_HOOK_ON_SESSION_START"
	LifecycleHookOnSessionEnd   LifecycleHook = "LIFECYCLE_HOOK_ON_SESSION_END"
	LifecycleHookPreTurn        LifecycleHook = "LIFECYCLE_HOOK_PRE_TURN"
	LifecycleHookPostTurn       LifecycleHook = "LIFECYCLE_HOOK_POST_TURN"
	LifecycleHookPreTool        LifecycleHook = "LIFECYCLE_HOOK_PRE_TOOL"
	LifecycleHookPostTool       LifecycleHook = "LIFECYCLE_HOOK_POST_TOOL"
	LifecycleHookOnToolError    LifecycleHook = "LIFECYCLE_HOOK_ON_TOOL_ERROR"
	LifecycleHookOnCompaction   LifecycleHook = "LIFECYCLE_HOOK_ON_COMPACTION"
	LifecycleHookStop           LifecycleHook = "LIFECYCLE_HOOK_STOP"
)

var lifecycleHookNames = map[int32]string{0: "LIFECYCLE_HOOK_UNSPECIFIED", 1: "LIFECYCLE_HOOK_ON_SESSION_START", 2: "LIFECYCLE_HOOK_ON_SESSION_END", 3: "LIFECYCLE_HOOK_PRE_TURN", 4: "LIFECYCLE_HOOK_POST_TURN", 5: "LIFECYCLE_HOOK_PRE_TOOL", 6: "LIFECYCLE_HOOK_POST_TOOL", 7: "LIFECYCLE_HOOK_ON_TOOL_ERROR", 8: "LIFECYCLE_HOOK_ON_COMPACTION", 9: "LIFECYCLE_HOOK_STOP"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e LifecycleHook) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *LifecycleHook) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), lifecycleHookNames)
}

// PreTurnResultDecision mirrors the antigravity.localharness.PreTurnResult.Decision enum.
type PreTurnResultDecision string

// PreTurnResultDecision values.
const (
	PreTurnResultDecisionUnspecified PreTurnResultDecision = "DECISION_UNSPECIFIED"
	PreTurnResultDecisionAllow       PreTurnResultDecision = "ALLOW"
	PreTurnResultDecisionDeny        PreTurnResultDecision = "DENY"
)

var preTurnResultDecisionNames = map[int32]string{0: "DECISION_UNSPECIFIED", 1: "ALLOW", 2: "DENY"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e PreTurnResultDecision) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *PreTurnResultDecision) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), preTurnResultDecisionNames)
}

// PreToolResultDecision mirrors the antigravity.localharness.PreToolResult.Decision enum.
type PreToolResultDecision string

// PreToolResultDecision values.
const (
	PreToolResultDecisionUnspecified PreToolResultDecision = "DECISION_UNSPECIFIED"
	PreToolResultDecisionAllow       PreToolResultDecision = "ALLOW"
	PreToolResultDecisionDeny        PreToolResultDecision = "DENY"
)

var preToolResultDecisionNames = map[int32]string{0: "DECISION_UNSPECIFIED", 1: "ALLOW", 2: "DENY"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e PreToolResultDecision) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *PreToolResultDecision) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), preToolResultDecisionNames)
}

// StopResultDecision mirrors the antigravity.localharness.StopResult.Decision enum.
type StopResultDecision string

// StopResultDecision values.
const (
	StopResultDecisionUnspecified StopResultDecision = "DECISION_UNSPECIFIED"
	StopResultDecisionAllowStop   StopResultDecision = "ALLOW_STOP"
	StopResultDecisionContinue    StopResultDecision = "CONTINUE"
)

var stopResultDecisionNames = map[int32]string{0: "DECISION_UNSPECIFIED", 1: "ALLOW_STOP", 2: "CONTINUE"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e StopResultDecision) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *StopResultDecision) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), stopResultDecisionNames)
}

// PolicyEvaluationOutcome mirrors the antigravity.localharness.PolicyEvaluationOutcome enum.
type PolicyEvaluationOutcome string

// PolicyEvaluationOutcome values.
const (
	PolicyEvaluationOutcomeUnspecified PolicyEvaluationOutcome = "POLICY_EVALUATION_OUTCOME_UNSPECIFIED"
	PolicyEvaluationOutcomeAllow       PolicyEvaluationOutcome = "POLICY_EVALUATION_OUTCOME_ALLOW"
	PolicyEvaluationOutcomeDeny        PolicyEvaluationOutcome = "POLICY_EVALUATION_OUTCOME_DENY"
	PolicyEvaluationOutcomeNoMatch     PolicyEvaluationOutcome = "POLICY_EVALUATION_OUTCOME_NO_MATCH"
)

var policyEvaluationOutcomeNames = map[int32]string{0: "POLICY_EVALUATION_OUTCOME_UNSPECIFIED", 1: "POLICY_EVALUATION_OUTCOME_ALLOW", 2: "POLICY_EVALUATION_OUTCOME_DENY", 3: "POLICY_EVALUATION_OUTCOME_NO_MATCH"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e PolicyEvaluationOutcome) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *PolicyEvaluationOutcome) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), policyEvaluationOutcomeNames)
}

// CallHookResponse mirrors the antigravity.localharness.CallHookResponse message.
// At most one of the result oneof fields (PreTurnResult, PreToolResult, EmptyResult, ErrorMessage, OnToolErrorResult, StopResult) is set.
type CallHookResponse struct {
	RequestID         *string            `json:"requestId,omitempty"`
	PreTurnResult     *PreTurnResult     `json:"preTurnResult,omitempty"`     // oneof result
	PreToolResult     *PreToolResult     `json:"preToolResult,omitempty"`     // oneof result
	EmptyResult       *EmptyResult       `json:"emptyResult,omitempty"`       // oneof result
	ErrorMessage      *string            `json:"errorMessage,omitempty"`      // oneof result
	OnToolErrorResult *OnToolErrorResult `json:"onToolErrorResult,omitempty"` // oneof result
	StopResult        *StopResult        `json:"stopResult,omitempty"`        // oneof result
}

// GetRequestID returns RequestID, or the zero value when unset.
func (x *CallHookResponse) GetRequestID() string {
	if x != nil && x.RequestID != nil {
		return *x.RequestID
	}
	return ""
}

// GetPreTurnResult returns PreTurnResult, or nil when x is nil.
func (x *CallHookResponse) GetPreTurnResult() *PreTurnResult {
	if x != nil {
		return x.PreTurnResult
	}
	return nil
}

// GetPreToolResult returns PreToolResult, or nil when x is nil.
func (x *CallHookResponse) GetPreToolResult() *PreToolResult {
	if x != nil {
		return x.PreToolResult
	}
	return nil
}

// GetEmptyResult returns EmptyResult, or nil when x is nil.
func (x *CallHookResponse) GetEmptyResult() *EmptyResult {
	if x != nil {
		return x.EmptyResult
	}
	return nil
}

// GetErrorMessage returns ErrorMessage, or the zero value when unset.
func (x *CallHookResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// GetOnToolErrorResult returns OnToolErrorResult, or nil when x is nil.
func (x *CallHookResponse) GetOnToolErrorResult() *OnToolErrorResult {
	if x != nil {
		return x.OnToolErrorResult
	}
	return nil
}

// GetStopResult returns StopResult, or nil when x is nil.
func (x *CallHookResponse) GetStopResult() *StopResult {
	if x != nil {
		return x.StopResult
	}
	return nil
}

// PreTurnResult mirrors the antigravity.localharness.PreTurnResult message.
type PreTurnResult struct {
	Decision *PreTurnResultDecision `json:"decision,omitempty"`
	Reason   *string                `json:"reason,omitempty"`
}

// GetDecision returns Decision, or the zero value when unset.
func (x *PreTurnResult) GetDecision() PreTurnResultDecision {
	if x != nil && x.Decision != nil {
		return *x.Decision
	}
	return ""
}

// GetReason returns Reason, or the zero value when unset.
func (x *PreTurnResult) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

// PreToolResult mirrors the antigravity.localharness.PreToolResult message.
type PreToolResult struct {
	Decision     *PreToolResultDecision `json:"decision,omitempty"`
	Reason       *string                `json:"reason,omitempty"`
	ModifiedArgs *Struct                `json:"modifiedArgs,omitempty"`
}

// GetDecision returns Decision, or the zero value when unset.
func (x *PreToolResult) GetDecision() PreToolResultDecision {
	if x != nil && x.Decision != nil {
		return *x.Decision
	}
	return ""
}

// GetReason returns Reason, or the zero value when unset.
func (x *PreToolResult) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

// GetModifiedArgs returns ModifiedArgs, or nil when x is nil.
func (x *PreToolResult) GetModifiedArgs() *Struct {
	if x != nil {
		return x.ModifiedArgs
	}
	return nil
}

// EmptyResult mirrors the antigravity.localharness.EmptyResult message.
type EmptyResult struct {
}

// OnToolErrorResult mirrors the antigravity.localharness.OnToolErrorResult message.
type OnToolErrorResult struct {
	CustomErrorMessage *string `json:"customErrorMessage,omitempty"`
}

// GetCustomErrorMessage returns CustomErrorMessage, or the zero value when unset.
func (x *OnToolErrorResult) GetCustomErrorMessage() string {
	if x != nil && x.CustomErrorMessage != nil {
		return *x.CustomErrorMessage
	}
	return ""
}

// StopResult mirrors the antigravity.localharness.StopResult message.
type StopResult struct {
	Decision *StopResultDecision `json:"decision,omitempty"`
	Reason   *string             `json:"reason,omitempty"`
}

// GetDecision returns Decision, or the zero value when unset.
func (x *StopResult) GetDecision() StopResultDecision {
	if x != nil && x.Decision != nil {
		return *x.Decision
	}
	return ""
}

// GetReason returns Reason, or the zero value when unset.
func (x *StopResult) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

// PolicyDecisionResponse mirrors the antigravity.localharness.PolicyDecisionResponse message.
type PolicyDecisionResponse struct {
	RequestID  *string                  `json:"requestId,omitempty"`
	Outcome    *PolicyEvaluationOutcome `json:"outcome,omitempty"`
	DenyReason *string                  `json:"denyReason,omitempty"`
}

// GetRequestID returns RequestID, or the zero value when unset.
func (x *PolicyDecisionResponse) GetRequestID() string {
	if x != nil && x.RequestID != nil {
		return *x.RequestID
	}
	return ""
}

// GetOutcome returns Outcome, or the zero value when unset.
func (x *PolicyDecisionResponse) GetOutcome() PolicyEvaluationOutcome {
	if x != nil && x.Outcome != nil {
		return *x.Outcome
	}
	return ""
}

// GetDenyReason returns DenyReason, or the zero value when unset.
func (x *PolicyDecisionResponse) GetDenyReason() string {
	if x != nil && x.DenyReason != nil {
		return *x.DenyReason
	}
	return ""
}

// CallHookRequest mirrors the antigravity.localharness.CallHookRequest message.
// At most one of the args oneof fields (PreTurnArgs, PostTurnArgs, PreToolArgs, PostToolArgs, OnToolErrorArgs, OnCompactionArgs, StopArgs) is set.
type CallHookRequest struct {
	RequestID        *string           `json:"requestId,omitempty"`
	Name             *string           `json:"name,omitempty"`
	PreTurnArgs      *PreTurnArgs      `json:"preTurnArgs,omitempty"`  // oneof args
	PostTurnArgs     *PostTurnArgs     `json:"postTurnArgs,omitempty"` // oneof args
	PreToolArgs      *PreToolArgs      `json:"preToolArgs,omitempty"`  // oneof args
	PostToolArgs     *PostToolArgs     `json:"postToolArgs,omitempty"` // oneof args
	Type             *LifecycleHook    `json:"type,omitempty"`
	OnToolErrorArgs  *OnToolErrorArgs  `json:"onToolErrorArgs,omitempty"`  // oneof args
	OnCompactionArgs *OnCompactionArgs `json:"onCompactionArgs,omitempty"` // oneof args
	StopArgs         *StopArgs         `json:"stopArgs,omitempty"`         // oneof args
	ClientID         *string           `json:"clientId,omitempty"`
}

// GetRequestID returns RequestID, or the zero value when unset.
func (x *CallHookRequest) GetRequestID() string {
	if x != nil && x.RequestID != nil {
		return *x.RequestID
	}
	return ""
}

// GetName returns Name, or the zero value when unset.
func (x *CallHookRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetPreTurnArgs returns PreTurnArgs, or nil when x is nil.
func (x *CallHookRequest) GetPreTurnArgs() *PreTurnArgs {
	if x != nil {
		return x.PreTurnArgs
	}
	return nil
}

// GetPostTurnArgs returns PostTurnArgs, or nil when x is nil.
func (x *CallHookRequest) GetPostTurnArgs() *PostTurnArgs {
	if x != nil {
		return x.PostTurnArgs
	}
	return nil
}

// GetPreToolArgs returns PreToolArgs, or nil when x is nil.
func (x *CallHookRequest) GetPreToolArgs() *PreToolArgs {
	if x != nil {
		return x.PreToolArgs
	}
	return nil
}

// GetPostToolArgs returns PostToolArgs, or nil when x is nil.
func (x *CallHookRequest) GetPostToolArgs() *PostToolArgs {
	if x != nil {
		return x.PostToolArgs
	}
	return nil
}

// GetType returns Type, or the zero value when unset.
func (x *CallHookRequest) GetType() LifecycleHook {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

// GetOnToolErrorArgs returns OnToolErrorArgs, or nil when x is nil.
func (x *CallHookRequest) GetOnToolErrorArgs() *OnToolErrorArgs {
	if x != nil {
		return x.OnToolErrorArgs
	}
	return nil
}

// GetOnCompactionArgs returns OnCompactionArgs, or nil when x is nil.
func (x *CallHookRequest) GetOnCompactionArgs() *OnCompactionArgs {
	if x != nil {
		return x.OnCompactionArgs
	}
	return nil
}

// GetStopArgs returns StopArgs, or nil when x is nil.
func (x *CallHookRequest) GetStopArgs() *StopArgs {
	if x != nil {
		return x.StopArgs
	}
	return nil
}

// GetClientID returns ClientID, or the zero value when unset.
func (x *CallHookRequest) GetClientID() string {
	if x != nil && x.ClientID != nil {
		return *x.ClientID
	}
	return ""
}

// PreTurnArgs mirrors the antigravity.localharness.PreTurnArgs message.
type PreTurnArgs struct {
	UserInput    *UserInput `json:"userInput,omitempty"`
	TrajectoryID *string    `json:"trajectoryId,omitempty"`
}

// GetUserInput returns UserInput, or nil when x is nil.
func (x *PreTurnArgs) GetUserInput() *UserInput {
	if x != nil {
		return x.UserInput
	}
	return nil
}

// GetTrajectoryID returns TrajectoryID, or the zero value when unset.
func (x *PreTurnArgs) GetTrajectoryID() string {
	if x != nil && x.TrajectoryID != nil {
		return *x.TrajectoryID
	}
	return ""
}

// PostTurnArgs mirrors the antigravity.localharness.PostTurnArgs message.
type PostTurnArgs struct {
	ResponseText *string `json:"responseText,omitempty"`
	TrajectoryID *string `json:"trajectoryId,omitempty"`
}

// GetResponseText returns ResponseText, or the zero value when unset.
func (x *PostTurnArgs) GetResponseText() string {
	if x != nil && x.ResponseText != nil {
		return *x.ResponseText
	}
	return ""
}

// GetTrajectoryID returns TrajectoryID, or the zero value when unset.
func (x *PostTurnArgs) GetTrajectoryID() string {
	if x != nil && x.TrajectoryID != nil {
		return *x.TrajectoryID
	}
	return ""
}

// PreToolArgs mirrors the antigravity.localharness.PreToolArgs message.
type PreToolArgs struct {
	ToolName      *string `json:"toolName,omitempty"`
	ArgumentsJSON *string `json:"argumentsJson,omitempty"`
	ServerName    *string `json:"serverName,omitempty"`
	CallID        *string `json:"callId,omitempty"`
	TrajectoryID  *string `json:"trajectoryId,omitempty"`
	StepIndex     *uint32 `json:"stepIndex,omitempty"`
}

// GetToolName returns ToolName, or the zero value when unset.
func (x *PreToolArgs) GetToolName() string {
	if x != nil && x.ToolName != nil {
		return *x.ToolName
	}
	return ""
}

// GetArgumentsJSON returns ArgumentsJSON, or the zero value when unset.
func (x *PreToolArgs) GetArgumentsJSON() string {
	if x != nil && x.ArgumentsJSON != nil {
		return *x.ArgumentsJSON
	}
	return ""
}

// GetServerName returns ServerName, or the zero value when unset.
func (x *PreToolArgs) GetServerName() string {
	if x != nil && x.ServerName != nil {
		return *x.ServerName
	}
	return ""
}

// GetCallID returns CallID, or the zero value when unset.
func (x *PreToolArgs) GetCallID() string {
	if x != nil && x.CallID != nil {
		return *x.CallID
	}
	return ""
}

// GetTrajectoryID returns TrajectoryID, or the zero value when unset.
func (x *PreToolArgs) GetTrajectoryID() string {
	if x != nil && x.TrajectoryID != nil {
		return *x.TrajectoryID
	}
	return ""
}

// GetStepIndex returns StepIndex, or the zero value when unset.
func (x *PreToolArgs) GetStepIndex() uint32 {
	if x != nil && x.StepIndex != nil {
		return *x.StepIndex
	}
	return 0
}

// PostToolArgs mirrors the antigravity.localharness.PostToolArgs message.
type PostToolArgs struct {
	ToolName     *string `json:"toolName,omitempty"`
	Result       *string `json:"result,omitempty"`
	Error        *string `json:"error,omitempty"`
	ServerName   *string `json:"serverName,omitempty"`
	CallID       *string `json:"callId,omitempty"`
	TrajectoryID *string `json:"trajectoryId,omitempty"`
	StepIndex    *uint32 `json:"stepIndex,omitempty"`
}

// GetToolName returns ToolName, or the zero value when unset.
func (x *PostToolArgs) GetToolName() string {
	if x != nil && x.ToolName != nil {
		return *x.ToolName
	}
	return ""
}

// GetResult returns Result, or the zero value when unset.
func (x *PostToolArgs) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

// GetError returns Error, or the zero value when unset.
func (x *PostToolArgs) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// GetServerName returns ServerName, or the zero value when unset.
func (x *PostToolArgs) GetServerName() string {
	if x != nil && x.ServerName != nil {
		return *x.ServerName
	}
	return ""
}

// GetCallID returns CallID, or the zero value when unset.
func (x *PostToolArgs) GetCallID() string {
	if x != nil && x.CallID != nil {
		return *x.CallID
	}
	return ""
}

// GetTrajectoryID returns TrajectoryID, or the zero value when unset.
func (x *PostToolArgs) GetTrajectoryID() string {
	if x != nil && x.TrajectoryID != nil {
		return *x.TrajectoryID
	}
	return ""
}

// GetStepIndex returns StepIndex, or the zero value when unset.
func (x *PostToolArgs) GetStepIndex() uint32 {
	if x != nil && x.StepIndex != nil {
		return *x.StepIndex
	}
	return 0
}

// OnToolErrorArgs mirrors the antigravity.localharness.OnToolErrorArgs message.
type OnToolErrorArgs struct {
	ToolName     *string `json:"toolName,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	ServerName   *string `json:"serverName,omitempty"`
	CallID       *string `json:"callId,omitempty"`
	TrajectoryID *string `json:"trajectoryId,omitempty"`
	StepIndex    *uint32 `json:"stepIndex,omitempty"`
}

// GetToolName returns ToolName, or the zero value when unset.
func (x *OnToolErrorArgs) GetToolName() string {
	if x != nil && x.ToolName != nil {
		return *x.ToolName
	}
	return ""
}

// GetErrorMessage returns ErrorMessage, or the zero value when unset.
func (x *OnToolErrorArgs) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// GetServerName returns ServerName, or the zero value when unset.
func (x *OnToolErrorArgs) GetServerName() string {
	if x != nil && x.ServerName != nil {
		return *x.ServerName
	}
	return ""
}

// GetCallID returns CallID, or the zero value when unset.
func (x *OnToolErrorArgs) GetCallID() string {
	if x != nil && x.CallID != nil {
		return *x.CallID
	}
	return ""
}

// GetTrajectoryID returns TrajectoryID, or the zero value when unset.
func (x *OnToolErrorArgs) GetTrajectoryID() string {
	if x != nil && x.TrajectoryID != nil {
		return *x.TrajectoryID
	}
	return ""
}

// GetStepIndex returns StepIndex, or the zero value when unset.
func (x *OnToolErrorArgs) GetStepIndex() uint32 {
	if x != nil && x.StepIndex != nil {
		return *x.StepIndex
	}
	return 0
}

// OnCompactionArgs mirrors the antigravity.localharness.OnCompactionArgs message.
type OnCompactionArgs struct {
	TrajectoryID *string `json:"trajectoryId,omitempty"`
	StepIndex    *uint32 `json:"stepIndex,omitempty"`
	Summary      *string `json:"summary,omitempty"`
}

// GetTrajectoryID returns TrajectoryID, or the zero value when unset.
func (x *OnCompactionArgs) GetTrajectoryID() string {
	if x != nil && x.TrajectoryID != nil {
		return *x.TrajectoryID
	}
	return ""
}

// GetStepIndex returns StepIndex, or the zero value when unset.
func (x *OnCompactionArgs) GetStepIndex() uint32 {
	if x != nil && x.StepIndex != nil {
		return *x.StepIndex
	}
	return 0
}

// GetSummary returns Summary, or the zero value when unset.
func (x *OnCompactionArgs) GetSummary() string {
	if x != nil && x.Summary != nil {
		return *x.Summary
	}
	return ""
}

// StopArgs mirrors the antigravity.localharness.StopArgs message.
type StopArgs struct {
	ResponseText      *string                          `json:"responseText,omitempty"`
	TrajectoryID      *string                          `json:"trajectoryId,omitempty"`
	ContinuationCount *int32                           `json:"continuationCount,omitempty"`
	StopReason        *TrajectoryStateUpdateStopReason `json:"stopReason,omitempty"`
	ErrorMessage      *string                          `json:"errorMessage,omitempty"`
}

// GetResponseText returns ResponseText, or the zero value when unset.
func (x *StopArgs) GetResponseText() string {
	if x != nil && x.ResponseText != nil {
		return *x.ResponseText
	}
	return ""
}

// GetTrajectoryID returns TrajectoryID, or the zero value when unset.
func (x *StopArgs) GetTrajectoryID() string {
	if x != nil && x.TrajectoryID != nil {
		return *x.TrajectoryID
	}
	return ""
}

// GetContinuationCount returns ContinuationCount, or the zero value when unset.
func (x *StopArgs) GetContinuationCount() int32 {
	if x != nil && x.ContinuationCount != nil {
		return *x.ContinuationCount
	}
	return 0
}

// GetStopReason returns StopReason, or the zero value when unset.
func (x *StopArgs) GetStopReason() TrajectoryStateUpdateStopReason {
	if x != nil && x.StopReason != nil {
		return *x.StopReason
	}
	return ""
}

// GetErrorMessage returns ErrorMessage, or the zero value when unset.
func (x *StopArgs) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// PolicyDecisionRequest mirrors the antigravity.localharness.PolicyDecisionRequest message.
type PolicyDecisionRequest struct {
	RequestID *string      `json:"requestId,omitempty"`
	RuleID    *string      `json:"ruleId,omitempty"`
	ToolArgs  *PreToolArgs `json:"toolArgs,omitempty"`
	Reason    *string      `json:"reason,omitempty"`
}

// GetRequestID returns RequestID, or the zero value when unset.
func (x *PolicyDecisionRequest) GetRequestID() string {
	if x != nil && x.RequestID != nil {
		return *x.RequestID
	}
	return ""
}

// GetRuleID returns RuleID, or the zero value when unset.
func (x *PolicyDecisionRequest) GetRuleID() string {
	if x != nil && x.RuleID != nil {
		return *x.RuleID
	}
	return ""
}

// GetToolArgs returns ToolArgs, or nil when x is nil.
func (x *PolicyDecisionRequest) GetToolArgs() *PreToolArgs {
	if x != nil {
		return x.ToolArgs
	}
	return nil
}

// GetReason returns Reason, or the zero value when unset.
func (x *PolicyDecisionRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}
