// Code generated by testdata/gen_types.py from the google-antigravity v0.1.20
// proto definitions (google/antigravity/proto/localharness.proto). DO NOT EDIT.

package wire

// TrajectoryStateUpdateState mirrors the antigravity.localharness.TrajectoryStateUpdate.State enum.
type TrajectoryStateUpdateState string

// TrajectoryStateUpdateState values.
const (
	TrajectoryStateUpdateStateUnspecified     TrajectoryStateUpdateState = "STATE_UNSPECIFIED"
	TrajectoryStateUpdateStateRunning         TrajectoryStateUpdateState = "STATE_RUNNING"
	TrajectoryStateUpdateStateFullyIdle       TrajectoryStateUpdateState = "STATE_FULLY_IDLE"
	TrajectoryStateUpdateStateCancelled       TrajectoryStateUpdateState = "STATE_CANCELLED"
	TrajectoryStateUpdateStateWaitingForTasks TrajectoryStateUpdateState = "STATE_WAITING_FOR_TASKS"
)

var trajectoryStateUpdateStateNames = map[int32]string{0: "STATE_UNSPECIFIED", 1: "STATE_RUNNING", 2: "STATE_FULLY_IDLE", 3: "STATE_CANCELLED", 4: "STATE_WAITING_FOR_TASKS"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e TrajectoryStateUpdateState) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *TrajectoryStateUpdateState) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), trajectoryStateUpdateStateNames)
}

// TrajectoryStateUpdateStopReason mirrors the antigravity.localharness.TrajectoryStateUpdate.StopReason enum.
type TrajectoryStateUpdateStopReason string

// TrajectoryStateUpdateStopReason values.
const (
	TrajectoryStateUpdateStopReasonUnspecified             TrajectoryStateUpdateStopReason = "STOP_REASON_UNSPECIFIED"
	TrajectoryStateUpdateStopReasonMaxModelCallsExceeded   TrajectoryStateUpdateStopReason = "STOP_REASON_MAX_MODEL_CALLS_EXCEEDED"
	TrajectoryStateUpdateStopReasonMaxToolCallsExceeded    TrajectoryStateUpdateStopReason = "STOP_REASON_MAX_TOOL_CALLS_EXCEEDED"
	TrajectoryStateUpdateStopReasonMaxInputTokensExceeded  TrajectoryStateUpdateStopReason = "STOP_REASON_MAX_INPUT_TOKENS_EXCEEDED"
	TrajectoryStateUpdateStopReasonMaxOutputTokensExceeded TrajectoryStateUpdateStopReason = "STOP_REASON_MAX_OUTPUT_TOKENS_EXCEEDED"
	TrajectoryStateUpdateStopReasonMaxTotalTokensExceeded  TrajectoryStateUpdateStopReason = "STOP_REASON_MAX_TOTAL_TOKENS_EXCEEDED"
	TrajectoryStateUpdateStopReasonQuotaExhausted          TrajectoryStateUpdateStopReason = "STOP_REASON_QUOTA_EXHAUSTED"
)

var trajectoryStateUpdateStopReasonNames = map[int32]string{0: "STOP_REASON_UNSPECIFIED", 1: "STOP_REASON_MAX_MODEL_CALLS_EXCEEDED", 2: "STOP_REASON_MAX_TOOL_CALLS_EXCEEDED", 3: "STOP_REASON_MAX_INPUT_TOKENS_EXCEEDED", 4: "STOP_REASON_MAX_OUTPUT_TOKENS_EXCEEDED", 5: "STOP_REASON_MAX_TOTAL_TOKENS_EXCEEDED", 6: "STOP_REASON_QUOTA_EXHAUSTED"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e TrajectoryStateUpdateStopReason) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *TrajectoryStateUpdateStopReason) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), trajectoryStateUpdateStopReasonNames)
}

// Modality mirrors the antigravity.localharness.Modality enum.
type Modality string

// Modality values.
const (
	ModalityUnspecified Modality = "MODALITY_UNSPECIFIED"
	ModalityText        Modality = "TEXT"
	ModalityImage       Modality = "IMAGE"
	ModalityVideo       Modality = "VIDEO"
	ModalityAudio       Modality = "AUDIO"
	ModalityDocument    Modality = "DOCUMENT"
)

var modalityNames = map[int32]string{0: "MODALITY_UNSPECIFIED", 1: "TEXT", 2: "IMAGE", 3: "VIDEO", 4: "AUDIO", 5: "DOCUMENT"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e Modality) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *Modality) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), modalityNames)
}

// InputEvent mirrors the antigravity.localharness.InputEvent message.
// At most one of the event oneof fields (UserInput, ToolConfirmation, ToolResponse, QuestionResponse, HaltRequest, AutomatedTrigger, CallHookResponse, SessionEndRequest, PolicyDecisionResponse) is set.
type InputEvent struct {
	ToolConfirmation       *ToolConfirmation       `json:"toolConfirmation,omitempty"`       // oneof event
	ToolResponse           *ToolResponse           `json:"toolResponse,omitempty"`           // oneof event
	QuestionResponse       *UserQuestionsResponse  `json:"questionResponse,omitempty"`       // oneof event
	HaltRequest            *bool                   `json:"haltRequest,omitempty"`            // oneof event
	AutomatedTrigger       *string                 `json:"automatedTrigger,omitempty"`       // oneof event
	UserInput              *UserInput              `json:"userInput,omitempty"`              // oneof event
	CallHookResponse       *CallHookResponse       `json:"callHookResponse,omitempty"`       // oneof event
	SessionEndRequest      *bool                   `json:"sessionEndRequest,omitempty"`      // oneof event
	PolicyDecisionResponse *PolicyDecisionResponse `json:"policyDecisionResponse,omitempty"` // oneof event
}

// GetToolConfirmation returns ToolConfirmation, or nil when x is nil.
func (x *InputEvent) GetToolConfirmation() *ToolConfirmation {
	if x != nil {
		return x.ToolConfirmation
	}
	return nil
}

// GetToolResponse returns ToolResponse, or nil when x is nil.
func (x *InputEvent) GetToolResponse() *ToolResponse {
	if x != nil {
		return x.ToolResponse
	}
	return nil
}

// GetQuestionResponse returns QuestionResponse, or nil when x is nil.
func (x *InputEvent) GetQuestionResponse() *UserQuestionsResponse {
	if x != nil {
		return x.QuestionResponse
	}
	return nil
}

// GetHaltRequest returns HaltRequest, or the zero value when unset.
func (x *InputEvent) GetHaltRequest() bool {
	if x != nil && x.HaltRequest != nil {
		return *x.HaltRequest
	}
	return false
}

// GetAutomatedTrigger returns AutomatedTrigger, or the zero value when unset.
func (x *InputEvent) GetAutomatedTrigger() string {
	if x != nil && x.AutomatedTrigger != nil {
		return *x.AutomatedTrigger
	}
	return ""
}

// GetUserInput returns UserInput, or nil when x is nil.
func (x *InputEvent) GetUserInput() *UserInput {
	if x != nil {
		return x.UserInput
	}
	return nil
}

// GetCallHookResponse returns CallHookResponse, or nil when x is nil.
func (x *InputEvent) GetCallHookResponse() *CallHookResponse {
	if x != nil {
		return x.CallHookResponse
	}
	return nil
}

// GetSessionEndRequest returns SessionEndRequest, or the zero value when unset.
func (x *InputEvent) GetSessionEndRequest() bool {
	if x != nil && x.SessionEndRequest != nil {
		return *x.SessionEndRequest
	}
	return false
}

// GetPolicyDecisionResponse returns PolicyDecisionResponse, or nil when x is nil.
func (x *InputEvent) GetPolicyDecisionResponse() *PolicyDecisionResponse {
	if x != nil {
		return x.PolicyDecisionResponse
	}
	return nil
}

// UserInput mirrors the antigravity.localharness.UserInput message.
type UserInput struct {
	Parts []*UserInputPart `json:"parts,omitempty"`
}

// GetParts returns Parts, or nil when x is nil.
func (x *UserInput) GetParts() []*UserInputPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

// UserInputPart mirrors the antigravity.localharness.UserInput.Part message.
// At most one of the part oneof fields (Text, Media, SlashCommand) is set.
type UserInputPart struct {
	Text         *string                `json:"text,omitempty"`         // oneof part
	Media        *UserInputMedia        `json:"media,omitempty"`        // oneof part
	SlashCommand *UserInputSlashCommand `json:"slashCommand,omitempty"` // oneof part
}

// GetText returns Text, or the zero value when unset.
func (x *UserInputPart) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

// GetMedia returns Media, or nil when x is nil.
func (x *UserInputPart) GetMedia() *UserInputMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

// GetSlashCommand returns SlashCommand, or nil when x is nil.
func (x *UserInputPart) GetSlashCommand() *UserInputSlashCommand {
	if x != nil {
		return x.SlashCommand
	}
	return nil
}

// UserInputMedia mirrors the antigravity.localharness.UserInput.Media message.
type UserInputMedia struct {
	MimeType    *string `json:"mimeType,omitempty"`
	Description *string `json:"description,omitempty"`
	Data        []byte  `json:"data,omitzero"`
}

// GetMimeType returns MimeType, or the zero value when unset.
func (x *UserInputMedia) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

// GetDescription returns Description, or the zero value when unset.
func (x *UserInputMedia) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// GetData returns Data, or nil when x is nil.
func (x *UserInputMedia) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UserInputSlashCommand mirrors the antigravity.localharness.UserInput.SlashCommand message.
type UserInputSlashCommand struct {
	Name *string `json:"name,omitempty"`
}

// GetName returns Name, or the zero value when unset.
func (x *UserInputSlashCommand) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// ToolConfirmation mirrors the antigravity.localharness.ToolConfirmation message.
type ToolConfirmation struct {
	TrajectoryID *string `json:"trajectoryId,omitempty"`
	StepIndex    *uint32 `json:"stepIndex,omitempty"`
	Accepted     *bool   `json:"accepted,omitempty"`
}

// GetTrajectoryID returns TrajectoryID, or the zero value when unset.
func (x *ToolConfirmation) GetTrajectoryID() string {
	if x != nil && x.TrajectoryID != nil {
		return *x.TrajectoryID
	}
	return ""
}

// GetStepIndex returns StepIndex, or the zero value when unset.
func (x *ToolConfirmation) GetStepIndex() uint32 {
	if x != nil && x.StepIndex != nil {
		return *x.StepIndex
	}
	return 0
}

// GetAccepted returns Accepted, or the zero value when unset.
func (x *ToolConfirmation) GetAccepted() bool {
	if x != nil && x.Accepted != nil {
		return *x.Accepted
	}
	return false
}

// ToolResponse mirrors the antigravity.localharness.ToolResponse message.
type ToolResponse struct {
	ID                *string  `json:"id,omitempty"`
	ResponseJSON      *string  `json:"responseJson,omitempty"`
	SupplementalMedia []*Media `json:"supplementalMedia,omitempty"`
	Response          *Struct  `json:"response,omitempty"`
	ErrorMessage      *string  `json:"errorMessage,omitempty"`
}

// GetID returns ID, or the zero value when unset.
func (x *ToolResponse) GetID() string {
	if x != nil && x.ID != nil {
		return *x.ID
	}
	return ""
}

// GetResponseJSON returns ResponseJSON, or the zero value when unset.
func (x *ToolResponse) GetResponseJSON() string {
	if x != nil && x.ResponseJSON != nil {
		return *x.ResponseJSON
	}
	return ""
}

// GetSupplementalMedia returns SupplementalMedia, or nil when x is nil.
func (x *ToolResponse) GetSupplementalMedia() []*Media {
	if x != nil {
		return x.SupplementalMedia
	}
	return nil
}

// GetResponse returns Response, or nil when x is nil.
func (x *ToolResponse) GetResponse() *Struct {
	if x != nil {
		return x.Response
	}
	return nil
}

// GetErrorMessage returns ErrorMessage, or the zero value when unset.
func (x *ToolResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// Media mirrors the antigravity.localharness.Media message.
type Media struct {
	MimeType    *string `json:"mimeType,omitempty"`
	Description *string `json:"description,omitempty"`
	Data        []byte  `json:"data,omitzero"`
}

// GetMimeType returns MimeType, or the zero value when unset.
func (x *Media) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

// GetDescription returns Description, or the zero value when unset.
func (x *Media) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// GetData returns Data, or nil when x is nil.
func (x *Media) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UserQuestionsResponse mirrors the antigravity.localharness.UserQuestionsResponse message.
// At most one of the result oneof fields (Cancelled, Response) is set.
type UserQuestionsResponse struct {
	TrajectoryID *string                                 `json:"trajectoryId,omitempty"`
	StepIndex    *uint32                                 `json:"stepIndex,omitempty"`
	Cancelled    *bool                                   `json:"cancelled,omitempty"` // oneof result
	Response     *UserQuestionsResponseQuestionsResponse `json:"response,omitempty"`  // oneof result
}

// GetTrajectoryID returns TrajectoryID, or the zero value when unset.
func (x *UserQuestionsResponse) GetTrajectoryID() string {
	if x != nil && x.TrajectoryID != nil {
		return *x.TrajectoryID
	}
	return ""
}

// GetStepIndex returns StepIndex, or the zero value when unset.
func (x *UserQuestionsResponse) GetStepIndex() uint32 {
	if x != nil && x.StepIndex != nil {
		return *x.StepIndex
	}
	return 0
}

// GetCancelled returns Cancelled, or the zero value when unset.
func (x *UserQuestionsResponse) GetCancelled() bool {
	if x != nil && x.Cancelled != nil {
		return *x.Cancelled
	}
	return false
}

// GetResponse returns Response, or nil when x is nil.
func (x *UserQuestionsResponse) GetResponse() *UserQuestionsResponseQuestionsResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

// UserQuestionsResponseQuestionsResponse mirrors the antigravity.localharness.UserQuestionsResponse.QuestionsResponse message.
type UserQuestionsResponseQuestionsResponse struct {
	Answers []*UserQuestionAnswer `json:"answers,omitempty"`
}

// GetAnswers returns Answers, or nil when x is nil.
func (x *UserQuestionsResponseQuestionsResponse) GetAnswers() []*UserQuestionAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

// UserQuestionAnswer mirrors the antigravity.localharness.UserQuestionAnswer message.
// At most one of the answer oneof fields (Unanswered, MultipleChoiceAnswer) is set.
type UserQuestionAnswer struct {
	Unanswered           *bool                 `json:"unanswered,omitempty"`           // oneof answer
	MultipleChoiceAnswer *MultipleChoiceAnswer `json:"multipleChoiceAnswer,omitempty"` // oneof answer
}

// GetUnanswered returns Unanswered, or the zero value when unset.
func (x *UserQuestionAnswer) GetUnanswered() bool {
	if x != nil && x.Unanswered != nil {
		return *x.Unanswered
	}
	return false
}

// GetMultipleChoiceAnswer returns MultipleChoiceAnswer, or nil when x is nil.
func (x *UserQuestionAnswer) GetMultipleChoiceAnswer() *MultipleChoiceAnswer {
	if x != nil {
		return x.MultipleChoiceAnswer
	}
	return nil
}

// MultipleChoiceAnswer mirrors the antigravity.localharness.MultipleChoiceAnswer message.
type MultipleChoiceAnswer struct {
	SelectedChoiceIndices []int32 `json:"selectedChoiceIndices,omitempty"`
	FreeformResponse      *string `json:"freeformResponse,omitempty"`
}

// GetSelectedChoiceIndices returns SelectedChoiceIndices, or nil when x is nil.
func (x *MultipleChoiceAnswer) GetSelectedChoiceIndices() []int32 {
	if x != nil {
		return x.SelectedChoiceIndices
	}
	return nil
}

// GetFreeformResponse returns FreeformResponse, or the zero value when unset.
func (x *MultipleChoiceAnswer) GetFreeformResponse() string {
	if x != nil && x.FreeformResponse != nil {
		return *x.FreeformResponse
	}
	return ""
}

// OutputEvent mirrors the antigravity.localharness.OutputEvent message.
// At most one of the event oneof fields (StepUpdate, TrajectoryStateUpdate, ToolCall, InitializeConversationResponse, CallHookRequest, SessionEndResponse, PolicyDecisionRequest, UsageUpdate) is set.
type OutputEvent struct {
	SeqNum                         *Int64                          `json:"seqNum,omitempty"`
	TimestampMicros                *Int64                          `json:"timestampMicros,omitempty"`
	StepUpdate                     *StepUpdate                     `json:"stepUpdate,omitempty"`                     // oneof event
	TrajectoryStateUpdate          *TrajectoryStateUpdate          `json:"trajectoryStateUpdate,omitempty"`          // oneof event
	ToolCall                       *ToolCall                       `json:"toolCall,omitempty"`                       // oneof event
	InitializeConversationResponse *InitializeConversationResponse `json:"initializeConversationResponse,omitempty"` // oneof event
	CallHookRequest                *CallHookRequest                `json:"callHookRequest,omitempty"`                // oneof event
	SessionEndResponse             *bool                           `json:"sessionEndResponse,omitempty"`             // oneof event
	PolicyDecisionRequest          *PolicyDecisionRequest          `json:"policyDecisionRequest,omitempty"`          // oneof event
	UsageUpdate                    *UsageUpdate                    `json:"usageUpdate,omitempty"`                    // oneof event
}

// GetSeqNum returns SeqNum, or the zero value when unset.
func (x *OutputEvent) GetSeqNum() int64 {
	if x != nil && x.SeqNum != nil {
		return int64(*x.SeqNum)
	}
	return 0
}

// GetTimestampMicros returns TimestampMicros, or the zero value when unset.
func (x *OutputEvent) GetTimestampMicros() int64 {
	if x != nil && x.TimestampMicros != nil {
		return int64(*x.TimestampMicros)
	}
	return 0
}

// GetStepUpdate returns StepUpdate, or nil when x is nil.
func (x *OutputEvent) GetStepUpdate() *StepUpdate {
	if x != nil {
		return x.StepUpdate
	}
	return nil
}

// GetTrajectoryStateUpdate returns TrajectoryStateUpdate, or nil when x is nil.
func (x *OutputEvent) GetTrajectoryStateUpdate() *TrajectoryStateUpdate {
	if x != nil {
		return x.TrajectoryStateUpdate
	}
	return nil
}

// GetToolCall returns ToolCall, or nil when x is nil.
func (x *OutputEvent) GetToolCall() *ToolCall {
	if x != nil {
		return x.ToolCall
	}
	return nil
}

// GetInitializeConversationResponse returns InitializeConversationResponse, or nil when x is nil.
func (x *OutputEvent) GetInitializeConversationResponse() *InitializeConversationResponse {
	if x != nil {
		return x.InitializeConversationResponse
	}
	return nil
}

// GetCallHookRequest returns CallHookRequest, or nil when x is nil.
func (x *OutputEvent) GetCallHookRequest() *CallHookRequest {
	if x != nil {
		return x.CallHookRequest
	}
	return nil
}

// GetSessionEndResponse returns SessionEndResponse, or the zero value when unset.
func (x *OutputEvent) GetSessionEndResponse() bool {
	if x != nil && x.SessionEndResponse != nil {
		return *x.SessionEndResponse
	}
	return false
}

// GetPolicyDecisionRequest returns PolicyDecisionRequest, or nil when x is nil.
func (x *OutputEvent) GetPolicyDecisionRequest() *PolicyDecisionRequest {
	if x != nil {
		return x.PolicyDecisionRequest
	}
	return nil
}

// GetUsageUpdate returns UsageUpdate, or nil when x is nil.
func (x *OutputEvent) GetUsageUpdate() *UsageUpdate {
	if x != nil {
		return x.UsageUpdate
	}
	return nil
}

// ToolCall mirrors the antigravity.localharness.ToolCall message.
type ToolCall struct {
	ID            *string `json:"id,omitempty"`
	Name          *string `json:"name,omitempty"`
	ArgumentsJSON *string `json:"argumentsJson,omitempty"`
	Arguments     *Struct `json:"arguments,omitempty"`
	TrajectoryID  *string `json:"trajectoryId,omitempty"`
}

// GetID returns ID, or the zero value when unset.
func (x *ToolCall) GetID() string {
	if x != nil && x.ID != nil {
		return *x.ID
	}
	return ""
}

// GetName returns Name, or the zero value when unset.
func (x *ToolCall) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetArgumentsJSON returns ArgumentsJSON, or the zero value when unset.
func (x *ToolCall) GetArgumentsJSON() string {
	if x != nil && x.ArgumentsJSON != nil {
		return *x.ArgumentsJSON
	}
	return ""
}

// GetArguments returns Arguments, or nil when x is nil.
func (x *ToolCall) GetArguments() *Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// GetTrajectoryID returns TrajectoryID, or the zero value when unset.
func (x *ToolCall) GetTrajectoryID() string {
	if x != nil && x.TrajectoryID != nil {
		return *x.TrajectoryID
	}
	return ""
}

// TrajectoryStateUpdate mirrors the antigravity.localharness.TrajectoryStateUpdate message.
type TrajectoryStateUpdate struct {
	TrajectoryID       *string                          `json:"trajectoryId,omitempty"`
	State              *TrajectoryStateUpdateState      `json:"state,omitempty"`
	Error              *string                          `json:"error,omitempty"`
	StopReason         *TrajectoryStateUpdateStopReason `json:"stopReason,omitempty"`
	ParentTrajectoryID *string                          `json:"parentTrajectoryId,omitempty"`
	Depth              *int32                           `json:"depth,omitempty"`
	ErrorCode          *string                          `json:"errorCode,omitempty"`
}

// GetTrajectoryID returns TrajectoryID, or the zero value when unset.
func (x *TrajectoryStateUpdate) GetTrajectoryID() string {
	if x != nil && x.TrajectoryID != nil {
		return *x.TrajectoryID
	}
	return ""
}

// GetState returns State, or the zero value when unset.
func (x *TrajectoryStateUpdate) GetState() TrajectoryStateUpdateState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

// GetError returns Error, or the zero value when unset.
func (x *TrajectoryStateUpdate) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// GetStopReason returns StopReason, or the zero value when unset.
func (x *TrajectoryStateUpdate) GetStopReason() TrajectoryStateUpdateStopReason {
	if x != nil && x.StopReason != nil {
		return *x.StopReason
	}
	return ""
}

// GetParentTrajectoryID returns ParentTrajectoryID, or the zero value when unset.
func (x *TrajectoryStateUpdate) GetParentTrajectoryID() string {
	if x != nil && x.ParentTrajectoryID != nil {
		return *x.ParentTrajectoryID
	}
	return ""
}

// GetDepth returns Depth, or the zero value when unset.
func (x *TrajectoryStateUpdate) GetDepth() int32 {
	if x != nil && x.Depth != nil {
		return *x.Depth
	}
	return 0
}

// GetErrorCode returns ErrorCode, or the zero value when unset.
func (x *TrajectoryStateUpdate) GetErrorCode() string {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return ""
}

// InitializeConversationResponse mirrors the antigravity.localharness.InitializeConversationResponse message.
type InitializeConversationResponse struct {
	CascadeID       *string                 `json:"cascadeId,omitempty"`
	History         []*StepUpdate           `json:"history,omitempty"`
	CumulativeUsage *UsageMetadata          `json:"cumulativeUsage,omitempty"`
	TrajectoryUsage []*TrajectoryUsageEntry `json:"trajectoryUsage,omitempty"`
	SandboxStatus   *SandboxStatus          `json:"sandboxStatus,omitempty"`
}

// GetCascadeID returns CascadeID, or the zero value when unset.
func (x *InitializeConversationResponse) GetCascadeID() string {
	if x != nil && x.CascadeID != nil {
		return *x.CascadeID
	}
	return ""
}

// GetHistory returns History, or nil when x is nil.
func (x *InitializeConversationResponse) GetHistory() []*StepUpdate {
	if x != nil {
		return x.History
	}
	return nil
}

// GetCumulativeUsage returns CumulativeUsage, or nil when x is nil.
func (x *InitializeConversationResponse) GetCumulativeUsage() *UsageMetadata {
	if x != nil {
		return x.CumulativeUsage
	}
	return nil
}

// GetTrajectoryUsage returns TrajectoryUsage, or nil when x is nil.
func (x *InitializeConversationResponse) GetTrajectoryUsage() []*TrajectoryUsageEntry {
	if x != nil {
		return x.TrajectoryUsage
	}
	return nil
}

// GetSandboxStatus returns SandboxStatus, or nil when x is nil.
func (x *InitializeConversationResponse) GetSandboxStatus() *SandboxStatus {
	if x != nil {
		return x.SandboxStatus
	}
	return nil
}

// UsageMetadata mirrors the antigravity.localharness.UsageMetadata message.
type UsageMetadata struct {
	PromptTokenCount           *Uint64               `json:"promptTokenCount,omitempty"`
	CandidatesTokenCount       *Uint64               `json:"candidatesTokenCount,omitempty"`
	TotalTokenCount            *Uint64               `json:"totalTokenCount,omitempty"`
	ThoughtsTokenCount         *Uint64               `json:"thoughtsTokenCount,omitempty"`
	CachedContentTokenCount    *Uint64               `json:"cachedContentTokenCount,omitempty"`
	ServiceTier                *string               `json:"serviceTier,omitempty"`
	PromptTokensDetails        []*ModalityTokenCount `json:"promptTokensDetails,omitempty"`
	CacheTokensDetails         []*ModalityTokenCount `json:"cacheTokensDetails,omitempty"`
	CandidatesTokensDetails    []*ModalityTokenCount `json:"candidatesTokensDetails,omitempty"`
	ToolUsePromptTokensDetails []*ModalityTokenCount `json:"toolUsePromptTokensDetails,omitempty"`
}

// GetPromptTokenCount returns PromptTokenCount, or the zero value when unset.
func (x *UsageMetadata) GetPromptTokenCount() uint64 {
	if x != nil && x.PromptTokenCount != nil {
		return uint64(*x.PromptTokenCount)
	}
	return 0
}

// GetCandidatesTokenCount returns CandidatesTokenCount, or the zero value when unset.
func (x *UsageMetadata) GetCandidatesTokenCount() uint64 {
	if x != nil && x.CandidatesTokenCount != nil {
		return uint64(*x.CandidatesTokenCount)
	}
	return 0
}

// GetTotalTokenCount returns TotalTokenCount, or the zero value when unset.
func (x *UsageMetadata) GetTotalTokenCount() uint64 {
	if x != nil && x.TotalTokenCount != nil {
		return uint64(*x.TotalTokenCount)
	}
	return 0
}

// GetThoughtsTokenCount returns ThoughtsTokenCount, or the zero value when unset.
func (x *UsageMetadata) GetThoughtsTokenCount() uint64 {
	if x != nil && x.ThoughtsTokenCount != nil {
		return uint64(*x.ThoughtsTokenCount)
	}
	return 0
}

// GetCachedContentTokenCount returns CachedContentTokenCount, or the zero value when unset.
func (x *UsageMetadata) GetCachedContentTokenCount() uint64 {
	if x != nil && x.CachedContentTokenCount != nil {
		return uint64(*x.CachedContentTokenCount)
	}
	return 0
}

// GetServiceTier returns ServiceTier, or the zero value when unset.
func (x *UsageMetadata) GetServiceTier() string {
	if x != nil && x.ServiceTier != nil {
		return *x.ServiceTier
	}
	return ""
}

// GetPromptTokensDetails returns PromptTokensDetails, or nil when x is nil.
func (x *UsageMetadata) GetPromptTokensDetails() []*ModalityTokenCount {
	if x != nil {
		return x.PromptTokensDetails
	}
	return nil
}

// GetCacheTokensDetails returns CacheTokensDetails, or nil when x is nil.
func (x *UsageMetadata) GetCacheTokensDetails() []*ModalityTokenCount {
	if x != nil {
		return x.CacheTokensDetails
	}
	return nil
}

// GetCandidatesTokensDetails returns CandidatesTokensDetails, or nil when x is nil.
func (x *UsageMetadata) GetCandidatesTokensDetails() []*ModalityTokenCount {
	if x != nil {
		return x.CandidatesTokensDetails
	}
	return nil
}

// GetToolUsePromptTokensDetails returns ToolUsePromptTokensDetails, or nil when x is nil.
func (x *UsageMetadata) GetToolUsePromptTokensDetails() []*ModalityTokenCount {
	if x != nil {
		return x.ToolUsePromptTokensDetails
	}
	return nil
}

// ModalityTokenCount mirrors the antigravity.localharness.ModalityTokenCount message.
type ModalityTokenCount struct {
	Modality   *Modality `json:"modality,omitempty"`
	TokenCount *Uint64   `json:"tokenCount,omitempty"`
}

// GetModality returns Modality, or the zero value when unset.
func (x *ModalityTokenCount) GetModality() Modality {
	if x != nil && x.Modality != nil {
		return *x.Modality
	}
	return ""
}

// GetTokenCount returns TokenCount, or the zero value when unset.
func (x *ModalityTokenCount) GetTokenCount() uint64 {
	if x != nil && x.TokenCount != nil {
		return uint64(*x.TokenCount)
	}
	return 0
}

// TrajectoryUsageEntry mirrors the antigravity.localharness.TrajectoryUsageEntry message.
type TrajectoryUsageEntry struct {
	TrajectoryID *string        `json:"trajectoryId,omitempty"`
	Usage        *UsageMetadata `json:"usage,omitempty"`
}

// GetTrajectoryID returns TrajectoryID, or the zero value when unset.
func (x *TrajectoryUsageEntry) GetTrajectoryID() string {
	if x != nil && x.TrajectoryID != nil {
		return *x.TrajectoryID
	}
	return ""
}

// GetUsage returns Usage, or nil when x is nil.
func (x *TrajectoryUsageEntry) GetUsage() *UsageMetadata {
	if x != nil {
		return x.Usage
	}
	return nil
}

// SandboxStatus mirrors the antigravity.localharness.SandboxStatus message.
type SandboxStatus struct {
	Available         *bool   `json:"available,omitempty"`
	UnavailableReason *string `json:"unavailableReason,omitempty"`
}

// GetAvailable returns Available, or the zero value when unset.
func (x *SandboxStatus) GetAvailable() bool {
	if x != nil && x.Available != nil {
		return *x.Available
	}
	return false
}

// GetUnavailableReason returns UnavailableReason, or the zero value when unset.
func (x *SandboxStatus) GetUnavailableReason() string {
	if x != nil && x.UnavailableReason != nil {
		return *x.UnavailableReason
	}
	return ""
}

// UsageUpdate mirrors the antigravity.localharness.UsageUpdate message.
type UsageUpdate struct {
	Agents []*TrajectoryUsageEntry `json:"agents,omitempty"`
	Total  *UsageMetadata          `json:"total,omitempty"`
}

// GetAgents returns Agents, or nil when x is nil.
func (x *UsageUpdate) GetAgents() []*TrajectoryUsageEntry {
	if x != nil {
		return x.Agents
	}
	return nil
}

// GetTotal returns Total, or nil when x is nil.
func (x *UsageUpdate) GetTotal() *UsageMetadata {
	if x != nil {
		return x.Total
	}
	return nil
}
