// Code generated by testdata/gen_types.py from the google-antigravity v0.1.20
// proto definitions (google/antigravity/proto/localharness.proto). DO NOT EDIT.

package wire

// StepUpdateState mirrors the antigravity.localharness.StepUpdate.State enum.
type StepUpdateState string

// StepUpdateState values.
const (
	StepUpdateStateUnspecified    StepUpdateState = "STATE_UNSPECIFIED"
	StepUpdateStateActive         StepUpdateState = "STATE_ACTIVE"
	StepUpdateStateDone           StepUpdateState = "STATE_DONE"
	StepUpdateStateWaitingForUser StepUpdateState = "STATE_WAITING_FOR_USER"
	StepUpdateStateError          StepUpdateState = "STATE_ERROR"
)

var stepUpdateStateNames = map[int32]string{0: "STATE_UNSPECIFIED", 1: "STATE_ACTIVE", 2: "STATE_DONE", 3: "STATE_WAITING_FOR_USER", 4: "STATE_ERROR"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e StepUpdateState) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *StepUpdateState) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), stepUpdateStateNames)
}

// StepUpdateSource mirrors the antigravity.localharness.StepUpdate.Source enum.
type StepUpdateSource string

// StepUpdateSource values.
const (
	StepUpdateSourceUnspecified StepUpdateSource = "SOURCE_UNSPECIFIED"
	StepUpdateSourceSystem      StepUpdateSource = "SOURCE_SYSTEM"
	StepUpdateSourceUser        StepUpdateSource = "SOURCE_USER"
	StepUpdateSourceModel       StepUpdateSource = "SOURCE_MODEL"
)

var stepUpdateSourceNames = map[int32]string{0: "SOURCE_UNSPECIFIED", 1: "SOURCE_SYSTEM", 2: "SOURCE_USER", 3: "SOURCE_MODEL"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e StepUpdateSource) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *StepUpdateSource) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), stepUpdateSourceNames)
}

// StepUpdateTarget mirrors the antigravity.localharness.StepUpdate.Target enum.
type StepUpdateTarget string

// StepUpdateTarget values.
const (
	StepUpdateTargetUnspecified StepUpdateTarget = "TARGET_UNSPECIFIED"
	StepUpdateTargetUser        StepUpdateTarget = "TARGET_USER"
	StepUpdateTargetModel       StepUpdateTarget = "TARGET_MODEL"
	StepUpdateTargetEnvironment StepUpdateTarget = "TARGET_ENVIRONMENT"
)

var stepUpdateTargetNames = map[int32]string{0: "TARGET_UNSPECIFIED", 1: "TARGET_USER", 2: "TARGET_MODEL", 3: "TARGET_ENVIRONMENT"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e StepUpdateTarget) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *StepUpdateTarget) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), stepUpdateTargetNames)
}

// ActionEditFileDiffLineLineAction mirrors the antigravity.localharness.ActionEditFile.DiffLine.LineAction enum.
type ActionEditFileDiffLineLineAction string

// ActionEditFileDiffLineLineAction values.
const (
	ActionEditFileDiffLineLineActionUnspecified ActionEditFileDiffLineLineAction = "LINE_ACTION_UNSPECIFIED"
	ActionEditFileDiffLineLineActionInsert      ActionEditFileDiffLineLineAction = "LINE_ACTION_INSERT"
	ActionEditFileDiffLineLineActionDelete      ActionEditFileDiffLineLineAction = "LINE_ACTION_DELETE"
	ActionEditFileDiffLineLineActionNone        ActionEditFileDiffLineLineAction = "LINE_ACTION_NONE"
)

var actionEditFileDiffLineLineActionNames = map[int32]string{0: "LINE_ACTION_UNSPECIFIED", 1: "LINE_ACTION_INSERT", 2: "LINE_ACTION_DELETE", 3: "LINE_ACTION_NONE"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e ActionEditFileDiffLineLineAction) MarshalJSON() ([]byte, error) {
	return marshalEnum(string(e))
}

// UnmarshalJSON accepts the value name or its number.
func (e *ActionEditFileDiffLineLineAction) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), actionEditFileDiffLineLineActionNames)
}

// ActionSkillLookupOperation mirrors the antigravity.localharness.ActionSkillLookup.Operation enum.
type ActionSkillLookupOperation string

// ActionSkillLookupOperation values.
const (
	ActionSkillLookupOperationUnspecified       ActionSkillLookupOperation = "OPERATION_UNSPECIFIED"
	ActionSkillLookupOperationListSkills        ActionSkillLookupOperation = "OPERATION_LIST_SKILLS"
	ActionSkillLookupOperationLookupSkills      ActionSkillLookupOperation = "OPERATION_LOOKUP_SKILLS"
	ActionSkillLookupOperationGetSkillResources ActionSkillLookupOperation = "OPERATION_GET_SKILL_RESOURCES"
)

var actionSkillLookupOperationNames = map[int32]string{0: "OPERATION_UNSPECIFIED", 1: "OPERATION_LIST_SKILLS", 2: "OPERATION_LOOKUP_SKILLS", 3: "OPERATION_GET_SKILL_RESOURCES"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e ActionSkillLookupOperation) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *ActionSkillLookupOperation) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), actionSkillLookupOperationNames)
}

// StepUpdate mirrors the antigravity.localharness.StepUpdate message.
type StepUpdate struct {
	CascadeID               *string                  `json:"cascadeId,omitempty"`
	TrajectoryID            *string                  `json:"trajectoryId,omitempty"`
	StepIndex               *uint32                  `json:"stepIndex,omitempty"`
	State                   *StepUpdateState         `json:"state,omitempty"`
	Source                  *StepUpdateSource        `json:"source,omitempty"`
	Target                  *StepUpdateTarget        `json:"target,omitempty"`
	ErrorMessage            *string                  `json:"errorMessage,omitempty"`
	Thinking                *string                  `json:"thinking,omitempty"`
	TextDelta               *string                  `json:"textDelta,omitempty"`
	ThinkingDelta           *string                  `json:"thinkingDelta,omitempty"`
	Text                    *string                  `json:"text,omitempty"`
	ListDirectory           *ActionListDirectory     `json:"listDirectory,omitempty"`
	FindFile                *ActionFindFile          `json:"findFile,omitempty"`
	SearchDirectory         *ActionSearchDirectory   `json:"searchDirectory,omitempty"`
	ViewFile                *ActionViewFile          `json:"viewFile,omitempty"`
	CreateFile              *ActionCreateFile        `json:"createFile,omitempty"`
	EditFile                *ActionEditFile          `json:"editFile,omitempty"`
	RunCommand              *ActionRunCommand        `json:"runCommand,omitempty"`
	Compaction              *ActionCompaction        `json:"compaction,omitempty"`
	InvokeSubagent          *ActionInvokeSubagent    `json:"invokeSubagent,omitempty"`
	GenerateImage           *ActionGenerateImage     `json:"generateImage,omitempty"`
	Finish                  *ActionFinish            `json:"finish,omitempty"`
	Error                   *ActionError             `json:"error,omitempty"`
	MCPTool                 *ActionMCPTool           `json:"mcpTool,omitempty"`
	SearchWeb               *ActionSearchWeb         `json:"searchWeb,omitempty"`
	ReadURLContent          *ActionReadURLContent    `json:"readUrlContent,omitempty"`
	CustomTool              *ActionCustomTool        `json:"customTool,omitempty"`
	SkillLookup             *ActionSkillLookup       `json:"skillLookup,omitempty"`
	ParentTrajectoryID      *string                  `json:"parentTrajectoryId,omitempty"`
	RequestText             *string                  `json:"requestText,omitempty"`
	ToolConfirmationRequest *ToolConfirmationRequest `json:"toolConfirmationRequest,omitempty"`
	QuestionsRequest        *UserQuestionsRequest    `json:"questionsRequest,omitempty"`
}

// GetCascadeID returns CascadeID, or the zero value when unset.
func (x *StepUpdate) GetCascadeID() string {
	if x != nil && x.CascadeID != nil {
		return *x.CascadeID
	}
	return ""
}

// GetTrajectoryID returns TrajectoryID, or the zero value when unset.
func (x *StepUpdate) GetTrajectoryID() string {
	if x != nil && x.TrajectoryID != nil {
		return *x.TrajectoryID
	}
	return ""
}

// GetStepIndex returns StepIndex, or the zero value when unset.
func (x *StepUpdate) GetStepIndex() uint32 {
	if x != nil && x.StepIndex != nil {
		return *x.StepIndex
	}
	return 0
}

// GetState returns State, or the zero value when unset.
func (x *StepUpdate) GetState() StepUpdateState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

// GetSource returns Source, or the zero value when unset.
func (x *StepUpdate) GetSource() StepUpdateSource {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

// GetTarget returns Target, or the zero value when unset.
func (x *StepUpdate) GetTarget() StepUpdateTarget {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

// GetErrorMessage returns ErrorMessage, or the zero value when unset.
func (x *StepUpdate) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// GetThinking returns Thinking, or the zero value when unset.
func (x *StepUpdate) GetThinking() string {
	if x != nil && x.Thinking != nil {
		return *x.Thinking
	}
	return ""
}

// GetTextDelta returns TextDelta, or the zero value when unset.
func (x *StepUpdate) GetTextDelta() string {
	if x != nil && x.TextDelta != nil {
		return *x.TextDelta
	}
	return ""
}

// GetThinkingDelta returns ThinkingDelta, or the zero value when unset.
func (x *StepUpdate) GetThinkingDelta() string {
	if x != nil && x.ThinkingDelta != nil {
		return *x.ThinkingDelta
	}
	return ""
}

// GetText returns Text, or the zero value when unset.
func (x *StepUpdate) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

// GetListDirectory returns ListDirectory, or nil when x is nil.
func (x *StepUpdate) GetListDirectory() *ActionListDirectory {
	if x != nil {
		return x.ListDirectory
	}
	return nil
}

// GetFindFile returns FindFile, or nil when x is nil.
func (x *StepUpdate) GetFindFile() *ActionFindFile {
	if x != nil {
		return x.FindFile
	}
	return nil
}

// GetSearchDirectory returns SearchDirectory, or nil when x is nil.
func (x *StepUpdate) GetSearchDirectory() *ActionSearchDirectory {
	if x != nil {
		return x.SearchDirectory
	}
	return nil
}

// GetViewFile returns ViewFile, or nil when x is nil.
func (x *StepUpdate) GetViewFile() *ActionViewFile {
	if x != nil {
		return x.ViewFile
	}
	return nil
}

// GetCreateFile returns CreateFile, or nil when x is nil.
func (x *StepUpdate) GetCreateFile() *ActionCreateFile {
	if x != nil {
		return x.CreateFile
	}
	return nil
}

// GetEditFile returns EditFile, or nil when x is nil.
func (x *StepUpdate) GetEditFile() *ActionEditFile {
	if x != nil {
		return x.EditFile
	}
	return nil
}

// GetRunCommand returns RunCommand, or nil when x is nil.
func (x *StepUpdate) GetRunCommand() *ActionRunCommand {
	if x != nil {
		return x.RunCommand
	}
	return nil
}

// GetCompaction returns Compaction, or nil when x is nil.
func (x *StepUpdate) GetCompaction() *ActionCompaction {
	if x != nil {
		return x.Compaction
	}
	return nil
}

// GetInvokeSubagent returns InvokeSubagent, or nil when x is nil.
func (x *StepUpdate) GetInvokeSubagent() *ActionInvokeSubagent {
	if x != nil {
		return x.InvokeSubagent
	}
	return nil
}

// GetGenerateImage returns GenerateImage, or nil when x is nil.
func (x *StepUpdate) GetGenerateImage() *ActionGenerateImage {
	if x != nil {
		return x.GenerateImage
	}
	return nil
}

// GetFinish returns Finish, or nil when x is nil.
func (x *StepUpdate) GetFinish() *ActionFinish {
	if x != nil {
		return x.Finish
	}
	return nil
}

// GetError returns Error, or nil when x is nil.
func (x *StepUpdate) GetError() *ActionError {
	if x != nil {
		return x.Error
	}
	return nil
}

// GetMCPTool returns MCPTool, or nil when x is nil.
func (x *StepUpdate) GetMCPTool() *ActionMCPTool {
	if x != nil {
		return x.MCPTool
	}
	return nil
}

// GetSearchWeb returns SearchWeb, or nil when x is nil.
func (x *StepUpdate) GetSearchWeb() *ActionSearchWeb {
	if x != nil {
		return x.SearchWeb
	}
	return nil
}

// GetReadURLContent returns ReadURLContent, or nil when x is nil.
func (x *StepUpdate) GetReadURLContent() *ActionReadURLContent {
	if x != nil {
		return x.ReadURLContent
	}
	return nil
}

// GetCustomTool returns CustomTool, or nil when x is nil.
func (x *StepUpdate) GetCustomTool() *ActionCustomTool {
	if x != nil {
		return x.CustomTool
	}
	return nil
}

// GetSkillLookup returns SkillLookup, or nil when x is nil.
func (x *StepUpdate) GetSkillLookup() *ActionSkillLookup {
	if x != nil {
		return x.SkillLookup
	}
	return nil
}

// GetParentTrajectoryID returns ParentTrajectoryID, or the zero value when unset.
func (x *StepUpdate) GetParentTrajectoryID() string {
	if x != nil && x.ParentTrajectoryID != nil {
		return *x.ParentTrajectoryID
	}
	return ""
}

// GetRequestText returns RequestText, or the zero value when unset.
func (x *StepUpdate) GetRequestText() string {
	if x != nil && x.RequestText != nil {
		return *x.RequestText
	}
	return ""
}

// GetToolConfirmationRequest returns ToolConfirmationRequest, or nil when x is nil.
func (x *StepUpdate) GetToolConfirmationRequest() *ToolConfirmationRequest {
	if x != nil {
		return x.ToolConfirmationRequest
	}
	return nil
}

// GetQuestionsRequest returns QuestionsRequest, or nil when x is nil.
func (x *StepUpdate) GetQuestionsRequest() *UserQuestionsRequest {
	if x != nil {
		return x.QuestionsRequest
	}
	return nil
}

// ActionListDirectory mirrors the antigravity.localharness.ActionListDirectory message.
type ActionListDirectory struct {
	DirectoryPath *string                      `json:"directoryPath,omitempty"`
	Results       []*ActionListDirectoryResult `json:"results,omitempty"`
}

// GetDirectoryPath returns DirectoryPath, or the zero value when unset.
func (x *ActionListDirectory) GetDirectoryPath() string {
	if x != nil && x.DirectoryPath != nil {
		return *x.DirectoryPath
	}
	return ""
}

// GetResults returns Results, or nil when x is nil.
func (x *ActionListDirectory) GetResults() []*ActionListDirectoryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// ActionListDirectoryResult mirrors the antigravity.localharness.ActionListDirectory.Result message.
// At most one of the info oneof fields (IsDirectory, FileSize) is set.
type ActionListDirectoryResult struct {
	Name        *string `json:"name,omitempty"`
	IsDirectory *bool   `json:"isDirectory,omitempty"` // oneof info
	FileSize    *Uint64 `json:"fileSize,omitempty"`    // oneof info
}

// GetName returns Name, or the zero value when unset.
func (x *ActionListDirectoryResult) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetIsDirectory returns IsDirectory, or the zero value when unset.
func (x *ActionListDirectoryResult) GetIsDirectory() bool {
	if x != nil && x.IsDirectory != nil {
		return *x.IsDirectory
	}
	return false
}

// GetFileSize returns FileSize, or the zero value when unset.
func (x *ActionListDirectoryResult) GetFileSize() uint64 {
	if x != nil && x.FileSize != nil {
		return uint64(*x.FileSize)
	}
	return 0
}

// ActionFindFile mirrors the antigravity.localharness.ActionFindFile message.
type ActionFindFile struct {
	DirectoryPath *string `json:"directoryPath,omitempty"`
	Query         *string `json:"query,omitempty"`
	Output        *string `json:"output,omitempty"`
}

// GetDirectoryPath returns DirectoryPath, or the zero value when unset.
func (x *ActionFindFile) GetDirectoryPath() string {
	if x != nil && x.DirectoryPath != nil {
		return *x.DirectoryPath
	}
	return ""
}

// GetQuery returns Query, or the zero value when unset.
func (x *ActionFindFile) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

// GetOutput returns Output, or the zero value when unset.
func (x *ActionFindFile) GetOutput() string {
	if x != nil && x.Output != nil {
		return *x.Output
	}
	return ""
}

// ActionSearchDirectory mirrors the antigravity.localharness.ActionSearchDirectory message.
type ActionSearchDirectory struct {
	DirectoryPath *string `json:"directoryPath,omitempty"`
	Query         *string `json:"query,omitempty"`
	NumResults    *int32  `json:"numResults,omitempty"`
}

// GetDirectoryPath returns DirectoryPath, or the zero value when unset.
func (x *ActionSearchDirectory) GetDirectoryPath() string {
	if x != nil && x.DirectoryPath != nil {
		return *x.DirectoryPath
	}
	return ""
}

// GetQuery returns Query, or the zero value when unset.
func (x *ActionSearchDirectory) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

// GetNumResults returns NumResults, or the zero value when unset.
func (x *ActionSearchDirectory) GetNumResults() int32 {
	if x != nil && x.NumResults != nil {
		return *x.NumResults
	}
	return 0
}

// ActionViewFile mirrors the antigravity.localharness.ActionViewFile message.
type ActionViewFile struct {
	FilePath      *string `json:"filePath,omitempty"`
	StartLine     *uint32 `json:"startLine,omitempty"`
	EndLine       *uint32 `json:"endLine,omitempty"`
	ContentOffset *int32  `json:"contentOffset,omitempty"`
}

// GetFilePath returns FilePath, or the zero value when unset.
func (x *ActionViewFile) GetFilePath() string {
	if x != nil && x.FilePath != nil {
		return *x.FilePath
	}
	return ""
}

// GetStartLine returns StartLine, or the zero value when unset.
func (x *ActionViewFile) GetStartLine() uint32 {
	if x != nil && x.StartLine != nil {
		return *x.StartLine
	}
	return 0
}

// GetEndLine returns EndLine, or the zero value when unset.
func (x *ActionViewFile) GetEndLine() uint32 {
	if x != nil && x.EndLine != nil {
		return *x.EndLine
	}
	return 0
}

// GetContentOffset returns ContentOffset, or the zero value when unset.
func (x *ActionViewFile) GetContentOffset() int32 {
	if x != nil && x.ContentOffset != nil {
		return *x.ContentOffset
	}
	return 0
}

// ActionCreateFile mirrors the antigravity.localharness.ActionCreateFile message.
type ActionCreateFile struct {
	FilePath *string `json:"filePath,omitempty"`
	Contents *string `json:"contents,omitempty"`
}

// GetFilePath returns FilePath, or the zero value when unset.
func (x *ActionCreateFile) GetFilePath() string {
	if x != nil && x.FilePath != nil {
		return *x.FilePath
	}
	return ""
}

// GetContents returns Contents, or the zero value when unset.
func (x *ActionCreateFile) GetContents() string {
	if x != nil && x.Contents != nil {
		return *x.Contents
	}
	return ""
}

// ActionEditFile mirrors the antigravity.localharness.ActionEditFile message.
type ActionEditFile struct {
	FilePath  *string                    `json:"filePath,omitempty"`
	DiffBlock []*ActionEditFileDiffBlock `json:"diffBlock,omitempty"`
}

// GetFilePath returns FilePath, or the zero value when unset.
func (x *ActionEditFile) GetFilePath() string {
	if x != nil && x.FilePath != nil {
		return *x.FilePath
	}
	return ""
}

// GetDiffBlock returns DiffBlock, or nil when x is nil.
func (x *ActionEditFile) GetDiffBlock() []*ActionEditFileDiffBlock {
	if x != nil {
		return x.DiffBlock
	}
	return nil
}

// ActionEditFileDiffBlock mirrors the antigravity.localharness.ActionEditFile.DiffBlock message.
type ActionEditFileDiffBlock struct {
	StartLine *int32                    `json:"startLine,omitempty"`
	EndLine   *int32                    `json:"endLine,omitempty"`
	Lines     []*ActionEditFileDiffLine `json:"lines,omitempty"`
}

// GetStartLine returns StartLine, or the zero value when unset.
func (x *ActionEditFileDiffBlock) GetStartLine() int32 {
	if x != nil && x.StartLine != nil {
		return *x.StartLine
	}
	return 0
}

// GetEndLine returns EndLine, or the zero value when unset.
func (x *ActionEditFileDiffBlock) GetEndLine() int32 {
	if x != nil && x.EndLine != nil {
		return *x.EndLine
	}
	return 0
}

// GetLines returns Lines, or nil when x is nil.
func (x *ActionEditFileDiffBlock) GetLines() []*ActionEditFileDiffLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

// ActionEditFileDiffLine mirrors the antigravity.localharness.ActionEditFile.DiffLine message.
type ActionEditFileDiffLine struct {
	Text   *string                           `json:"text,omitempty"`
	Action *ActionEditFileDiffLineLineAction `json:"action,omitempty"`
}

// GetText returns Text, or the zero value when unset.
func (x *ActionEditFileDiffLine) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

// GetAction returns Action, or the zero value when unset.
func (x *ActionEditFileDiffLine) GetAction() ActionEditFileDiffLineLineAction {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return ""
}

// ActionRunCommand mirrors the antigravity.localharness.ActionRunCommand message.
type ActionRunCommand struct {
	CommandLine    *string `json:"commandLine,omitempty"`
	WorkingDir     *string `json:"workingDir,omitempty"`
	ExitCode       *int32  `json:"exitCode,omitempty"`
	CombinedOutput *string `json:"combinedOutput,omitempty"`
}

// GetCommandLine returns CommandLine, or the zero value when unset.
func (x *ActionRunCommand) GetCommandLine() string {
	if x != nil && x.CommandLine != nil {
		return *x.CommandLine
	}
	return ""
}

// GetWorkingDir returns WorkingDir, or the zero value when unset.
func (x *ActionRunCommand) GetWorkingDir() string {
	if x != nil && x.WorkingDir != nil {
		return *x.WorkingDir
	}
	return ""
}

// GetExitCode returns ExitCode, or the zero value when unset.
func (x *ActionRunCommand) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

// GetCombinedOutput returns CombinedOutput, or the zero value when unset.
func (x *ActionRunCommand) GetCombinedOutput() string {
	if x != nil && x.CombinedOutput != nil {
		return *x.CombinedOutput
	}
	return ""
}

// ActionCompaction mirrors the antigravity.localharness.ActionCompaction message.
type ActionCompaction struct {
}

// ActionInvokeSubagent mirrors the antigravity.localharness.ActionInvokeSubagent message.
type ActionInvokeSubagent struct {
}

// ActionGenerateImage mirrors the antigravity.localharness.ActionGenerateImage message.
type ActionGenerateImage struct {
	Prompt      *string  `json:"prompt,omitempty"`
	ImagePaths  []string `json:"imagePaths,omitempty"`
	ImageName   *string  `json:"imageName,omitempty"`
	AspectRatio *string  `json:"aspectRatio,omitempty"`
	OutputPath  *string  `json:"outputPath,omitempty"`
}

// GetPrompt returns Prompt, or the zero value when unset.
func (x *ActionGenerateImage) GetPrompt() string {
	if x != nil && x.Prompt != nil {
		return *x.Prompt
	}
	return ""
}

// GetImagePaths returns ImagePaths, or nil when x is nil.
func (x *ActionGenerateImage) GetImagePaths() []string {
	if x != nil {
		return x.ImagePaths
	}
	return nil
}

// GetImageName returns ImageName, or the zero value when unset.
func (x *ActionGenerateImage) GetImageName() string {
	if x != nil && x.ImageName != nil {
		return *x.ImageName
	}
	return ""
}

// GetAspectRatio returns AspectRatio, or the zero value when unset.
func (x *ActionGenerateImage) GetAspectRatio() string {
	if x != nil && x.AspectRatio != nil {
		return *x.AspectRatio
	}
	return ""
}

// GetOutputPath returns OutputPath, or the zero value when unset.
func (x *ActionGenerateImage) GetOutputPath() string {
	if x != nil && x.OutputPath != nil {
		return *x.OutputPath
	}
	return ""
}

// ActionFinish mirrors the antigravity.localharness.ActionFinish message.
type ActionFinish struct {
	OutputString *string `json:"outputString,omitempty"`
}

// GetOutputString returns OutputString, or the zero value when unset.
func (x *ActionFinish) GetOutputString() string {
	if x != nil && x.OutputString != nil {
		return *x.OutputString
	}
	return ""
}

// ActionError mirrors the antigravity.localharness.ActionError message.
type ActionError struct {
	ErrorMessage *string `json:"errorMessage,omitempty"`
	HTTPCode     *uint32 `json:"httpCode,omitempty"`
}

// GetErrorMessage returns ErrorMessage, or the zero value when unset.
func (x *ActionError) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// GetHTTPCode returns HTTPCode, or the zero value when unset.
func (x *ActionError) GetHTTPCode() uint32 {
	if x != nil && x.HTTPCode != nil {
		return *x.HTTPCode
	}
	return 0
}

// ActionMCPTool mirrors the antigravity.localharness.ActionMcpTool message.
type ActionMCPTool struct {
	ServerName    *string `json:"serverName,omitempty"`
	ToolName      *string `json:"toolName,omitempty"`
	ArgumentsJSON *string `json:"argumentsJson,omitempty"`
}

// GetServerName returns ServerName, or the zero value when unset.
func (x *ActionMCPTool) GetServerName() string {
	if x != nil && x.ServerName != nil {
		return *x.ServerName
	}
	return ""
}

// GetToolName returns ToolName, or the zero value when unset.
func (x *ActionMCPTool) GetToolName() string {
	if x != nil && x.ToolName != nil {
		return *x.ToolName
	}
	return ""
}

// GetArgumentsJSON returns ArgumentsJSON, or the zero value when unset.
func (x *ActionMCPTool) GetArgumentsJSON() string {
	if x != nil && x.ArgumentsJSON != nil {
		return *x.ArgumentsJSON
	}
	return ""
}

// ActionSearchWeb mirrors the antigravity.localharness.ActionSearchWeb message.
type ActionSearchWeb struct {
	Query   *string `json:"query,omitempty"`
	Domain  *string `json:"domain,omitempty"`
	Summary *string `json:"summary,omitempty"`
}

// GetQuery returns Query, or the zero value when unset.
func (x *ActionSearchWeb) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

// GetDomain returns Domain, or the zero value when unset.
func (x *ActionSearchWeb) GetDomain() string {
	if x != nil && x.Domain != nil {
		return *x.Domain
	}
	return ""
}

// GetSummary returns Summary, or the zero value when unset.
func (x *ActionSearchWeb) GetSummary() string {
	if x != nil && x.Summary != nil {
		return *x.Summary
	}
	return ""
}

// ActionReadURLContent mirrors the antigravity.localharness.ActionReadUrlContent message.
type ActionReadURLContent struct {
	URL         *string `json:"url,omitempty"`
	Title       *string `json:"title,omitempty"`
	Summary     *string `json:"summary,omitempty"`
	ContentPath *string `json:"contentPath,omitempty"`
}

// GetURL returns URL, or the zero value when unset.
func (x *ActionReadURLContent) GetURL() string {
	if x != nil && x.URL != nil {
		return *x.URL
	}
	return ""
}

// GetTitle returns Title, or the zero value when unset.
func (x *ActionReadURLContent) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

// GetSummary returns Summary, or the zero value when unset.
func (x *ActionReadURLContent) GetSummary() string {
	if x != nil && x.Summary != nil {
		return *x.Summary
	}
	return ""
}

// GetContentPath returns ContentPath, or the zero value when unset.
func (x *ActionReadURLContent) GetContentPath() string {
	if x != nil && x.ContentPath != nil {
		return *x.ContentPath
	}
	return ""
}

// ActionCustomTool mirrors the antigravity.localharness.ActionCustomTool message.
type ActionCustomTool struct {
	ToolCall     *ToolCall     `json:"toolCall,omitempty"`
	ToolResponse *ToolResponse `json:"toolResponse,omitempty"`
}

// GetToolCall returns ToolCall, or nil when x is nil.
func (x *ActionCustomTool) GetToolCall() *ToolCall {
	if x != nil {
		return x.ToolCall
	}
	return nil
}

// GetToolResponse returns ToolResponse, or nil when x is nil.
func (x *ActionCustomTool) GetToolResponse() *ToolResponse {
	if x != nil {
		return x.ToolResponse
	}
	return nil
}

// ActionSkillLookup mirrors the antigravity.localharness.ActionSkillLookup message.
type ActionSkillLookup struct {
	Operation           *ActionSkillLookupOperation `json:"operation,omitempty"`
	RequestedSkillNames []string                    `json:"requestedSkillNames,omitempty"`
	ResolvedSkillNames  []string                    `json:"resolvedSkillNames,omitempty"`
	ErrorMessage        *string                     `json:"errorMessage,omitempty"`
}

// GetOperation returns Operation, or the zero value when unset.
func (x *ActionSkillLookup) GetOperation() ActionSkillLookupOperation {
	if x != nil && x.Operation != nil {
		return *x.Operation
	}
	return ""
}

// GetRequestedSkillNames returns RequestedSkillNames, or nil when x is nil.
func (x *ActionSkillLookup) GetRequestedSkillNames() []string {
	if x != nil {
		return x.RequestedSkillNames
	}
	return nil
}

// GetResolvedSkillNames returns ResolvedSkillNames, or nil when x is nil.
func (x *ActionSkillLookup) GetResolvedSkillNames() []string {
	if x != nil {
		return x.ResolvedSkillNames
	}
	return nil
}

// GetErrorMessage returns ErrorMessage, or the zero value when unset.
func (x *ActionSkillLookup) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// ToolConfirmationRequest mirrors the antigravity.localharness.ToolConfirmationRequest message.
type ToolConfirmationRequest struct {
}

// UserQuestionsRequest mirrors the antigravity.localharness.UserQuestionsRequest message.
type UserQuestionsRequest struct {
	Questions []*UserQuestion `json:"questions,omitempty"`
}

// GetQuestions returns Questions, or nil when x is nil.
func (x *UserQuestionsRequest) GetQuestions() []*UserQuestion {
	if x != nil {
		return x.Questions
	}
	return nil
}

// UserQuestion mirrors the antigravity.localharness.UserQuestion message.
// At most one of the question_type oneof fields (MultipleChoice) is set.
type UserQuestion struct {
	MultipleChoice *MultipleChoice `json:"multipleChoice,omitempty"` // oneof question_type
}

// GetMultipleChoice returns MultipleChoice, or nil when x is nil.
func (x *UserQuestion) GetMultipleChoice() *MultipleChoice {
	if x != nil {
		return x.MultipleChoice
	}
	return nil
}

// MultipleChoice mirrors the antigravity.localharness.MultipleChoice message.
type MultipleChoice struct {
	Question      *string  `json:"question,omitempty"`
	Choices       []string `json:"choices,omitempty"`
	IsMultiSelect *bool    `json:"isMultiSelect,omitempty"`
}

// GetQuestion returns Question, or the zero value when unset.
func (x *MultipleChoice) GetQuestion() string {
	if x != nil && x.Question != nil {
		return *x.Question
	}
	return ""
}

// GetChoices returns Choices, or nil when x is nil.
func (x *MultipleChoice) GetChoices() []string {
	if x != nil {
		return x.Choices
	}
	return nil
}

// GetIsMultiSelect returns IsMultiSelect, or the zero value when unset.
func (x *MultipleChoice) GetIsMultiSelect() bool {
	if x != nil && x.IsMultiSelect != nil {
		return *x.IsMultiSelect
	}
	return false
}
