// Code generated by testdata/gen_types.py from the google-antigravity v0.1.20
// proto definitions (google/antigravity/proto/localharness.proto). DO NOT EDIT.

package wire

// HarnessConfigSessionContinuationMode mirrors the antigravity.localharness.HarnessConfig.SessionContinuationMode enum.
type HarnessConfigSessionContinuationMode string

// HarnessConfigSessionContinuationMode values.
const (
	HarnessConfigSessionContinuationModeUnspecified    HarnessConfigSessionContinuationMode = "SESSION_CONTINUATION_MODE_UNSPECIFIED"
	HarnessConfigSessionContinuationModeResume         HarnessConfigSessionContinuationMode = "RESUME"
	HarnessConfigSessionContinuationModeCreateOrResume HarnessConfigSessionContinuationMode = "CREATE_OR_RESUME"
	HarnessConfigSessionContinuationModeCreateOnly     HarnessConfigSessionContinuationMode = "CREATE_ONLY"
)

var harnessConfigSessionContinuationModeNames = map[int32]string{0: "SESSION_CONTINUATION_MODE_UNSPECIFIED", 1: "RESUME", 2: "CREATE_OR_RESUME", 3: "CREATE_ONLY"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e HarnessConfigSessionContinuationMode) MarshalJSON() ([]byte, error) {
	return marshalEnum(string(e))
}

// UnmarshalJSON accepts the value name or its number.
func (e *HarnessConfigSessionContinuationMode) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), harnessConfigSessionContinuationModeNames)
}

// ToolExecutionMode mirrors the antigravity.localharness.ToolExecutionMode enum.
type ToolExecutionMode string

// ToolExecutionMode values.
const (
	ToolExecutionModeUnspecified ToolExecutionMode = "TOOL_EXECUTION_MODE_UNSPECIFIED"
	ToolExecutionModeSync        ToolExecutionMode = "TOOL_EXECUTION_MODE_SYNC"
	ToolExecutionModeAsync       ToolExecutionMode = "TOOL_EXECUTION_MODE_ASYNC"
)

var toolExecutionModeNames = map[int32]string{0: "TOOL_EXECUTION_MODE_UNSPECIFIED", 1: "TOOL_EXECUTION_MODE_SYNC", 2: "TOOL_EXECUTION_MODE_ASYNC"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e ToolExecutionMode) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *ToolExecutionMode) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), toolExecutionModeNames)
}

// MCPServerConfigAuthProviderType mirrors the antigravity.localharness.McpServerConfig.AuthProviderType enum.
type MCPServerConfigAuthProviderType string

// MCPServerConfigAuthProviderType values.
const (
	MCPServerConfigAuthProviderTypeUnspecified       MCPServerConfigAuthProviderType = "AUTH_PROVIDER_TYPE_UNSPECIFIED"
	MCPServerConfigAuthProviderTypeGoogleCredentials MCPServerConfigAuthProviderType = "AUTH_PROVIDER_TYPE_GOOGLE_CREDENTIALS"
)

var mCPServerConfigAuthProviderTypeNames = map[int32]string{0: "AUTH_PROVIDER_TYPE_UNSPECIFIED", 1: "AUTH_PROVIDER_TYPE_GOOGLE_CREDENTIALS"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e MCPServerConfigAuthProviderType) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *MCPServerConfigAuthProviderType) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), mCPServerConfigAuthProviderTypeNames)
}

// ModelType mirrors the antigravity.localharness.ModelType enum.
type ModelType string

// ModelType values.
const (
	ModelTypeUnspecified ModelType = "MODEL_TYPE_UNSPECIFIED"
	ModelTypeText        ModelType = "MODEL_TYPE_TEXT"
	ModelTypeImage       ModelType = "MODEL_TYPE_IMAGE"
)

var modelTypeNames = map[int32]string{0: "MODEL_TYPE_UNSPECIFIED", 1: "MODEL_TYPE_TEXT", 2: "MODEL_TYPE_IMAGE"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e ModelType) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *ModelType) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), modelTypeNames)
}

// AgentBehavior mirrors the antigravity.localharness.AgentBehavior enum.
type AgentBehavior string

// AgentBehavior values.
const (
	AgentBehaviorUnspecified AgentBehavior = "AGENT_BEHAVIOR_UNSPECIFIED"
	AgentBehaviorAutonomous  AgentBehavior = "AGENT_BEHAVIOR_AUTONOMOUS"
	AgentBehaviorInteractive AgentBehavior = "AGENT_BEHAVIOR_INTERACTIVE"
	AgentBehaviorMinimal     AgentBehavior = "AGENT_BEHAVIOR_MINIMAL"
)

var agentBehaviorNames = map[int32]string{0: "AGENT_BEHAVIOR_UNSPECIFIED", 1: "AGENT_BEHAVIOR_AUTONOMOUS", 2: "AGENT_BEHAVIOR_INTERACTIVE", 3: "AGENT_BEHAVIOR_MINIMAL"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e AgentBehavior) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *AgentBehavior) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), agentBehaviorNames)
}

// PolicyDecision mirrors the antigravity.localharness.PolicyDecision enum.
type PolicyDecision string

// PolicyDecision values.
const (
	PolicyDecisionUnspecified PolicyDecision = "POLICY_DECISION_UNSPECIFIED"
	PolicyDecisionAllow       PolicyDecision = "POLICY_DECISION_ALLOW"
	PolicyDecisionDeny        PolicyDecision = "POLICY_DECISION_DENY"
	PolicyDecisionAskUser     PolicyDecision = "POLICY_DECISION_ASK_USER"
)

var policyDecisionNames = map[int32]string{0: "POLICY_DECISION_UNSPECIFIED", 1: "POLICY_DECISION_ALLOW", 2: "POLICY_DECISION_DENY", 3: "POLICY_DECISION_ASK_USER"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e PolicyDecision) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *PolicyDecision) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), policyDecisionNames)
}

// PolicyConfigWorkspaceContainment mirrors the antigravity.localharness.PolicyConfig.WorkspaceContainment enum.
type PolicyConfigWorkspaceContainment string

// PolicyConfigWorkspaceContainment values.
const (
	PolicyConfigWorkspaceContainmentUnspecified PolicyConfigWorkspaceContainment = "WORKSPACE_CONTAINMENT_UNSPECIFIED"
	PolicyConfigWorkspaceContainmentEnabled     PolicyConfigWorkspaceContainment = "WORKSPACE_CONTAINMENT_ENABLED"
	PolicyConfigWorkspaceContainmentDisabled    PolicyConfigWorkspaceContainment = "WORKSPACE_CONTAINMENT_DISABLED"
)

var policyConfigWorkspaceContainmentNames = map[int32]string{0: "WORKSPACE_CONTAINMENT_UNSPECIFIED", 1: "WORKSPACE_CONTAINMENT_ENABLED", 2: "WORKSPACE_CONTAINMENT_DISABLED"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e PolicyConfigWorkspaceContainment) MarshalJSON() ([]byte, error) {
	return marshalEnum(string(e))
}

// UnmarshalJSON accepts the value name or its number.
func (e *PolicyConfigWorkspaceContainment) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), policyConfigWorkspaceContainmentNames)
}

// BudgetConfigBudgetScope mirrors the antigravity.localharness.BudgetConfig.BudgetScope enum.
type BudgetConfigBudgetScope string

// BudgetConfigBudgetScope values.
const (
	BudgetConfigBudgetScopeUnspecified    BudgetConfigBudgetScope = "BUDGET_SCOPE_UNSPECIFIED"
	BudgetConfigBudgetScopeLifetime       BudgetConfigBudgetScope = "BUDGET_SCOPE_LIFETIME"
	BudgetConfigBudgetScopeForwardLooking BudgetConfigBudgetScope = "BUDGET_SCOPE_FORWARD_LOOKING"
)

var budgetConfigBudgetScopeNames = map[int32]string{0: "BUDGET_SCOPE_UNSPECIFIED", 1: "BUDGET_SCOPE_LIFETIME", 2: "BUDGET_SCOPE_FORWARD_LOOKING"}

// MarshalJSON encodes the value name; a numeric value outside the known set
// encodes as a JSON number, as protobuf JSON does for open enums.
func (e BudgetConfigBudgetScope) MarshalJSON() ([]byte, error) { return marshalEnum(string(e)) }

// UnmarshalJSON accepts the value name or its number.
func (e *BudgetConfigBudgetScope) UnmarshalJSON(b []byte) error {
	return unmarshalEnum(b, (*string)(e), budgetConfigBudgetScopeNames)
}

// InputConfig mirrors the antigravity.localharness.InputConfig message.
type InputConfig struct {
	StorageDirectory   *string           `json:"storageDirectory,omitempty"`
	Port               *uint32           `json:"port,omitempty"`
	BindAddress        *string           `json:"bindAddress,omitempty"`
	ClientInfo         *ClientInfo       `json:"clientInfo,omitempty"`
	Env                map[string]string `json:"env,omitempty"`
	UseInteractionsAPI *bool             `json:"useInteractionsApi,omitempty"`
}

// GetStorageDirectory returns StorageDirectory, or the zero value when unset.
func (x *InputConfig) GetStorageDirectory() string {
	if x != nil && x.StorageDirectory != nil {
		return *x.StorageDirectory
	}
	return ""
}

// GetPort returns Port, or the zero value when unset.
func (x *InputConfig) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

// GetBindAddress returns BindAddress, or the proto default "localhost" when unset.
func (x *InputConfig) GetBindAddress() string {
	if x != nil && x.BindAddress != nil {
		return *x.BindAddress
	}
	return "localhost"
}

// GetClientInfo returns ClientInfo, or nil when x is nil.
func (x *InputConfig) GetClientInfo() *ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

// GetEnv returns Env, or nil when x is nil.
func (x *InputConfig) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// GetUseInteractionsAPI returns UseInteractionsAPI, or the zero value when unset.
func (x *InputConfig) GetUseInteractionsAPI() bool {
	if x != nil && x.UseInteractionsAPI != nil {
		return *x.UseInteractionsAPI
	}
	return false
}

// ClientInfo mirrors the antigravity.localharness.ClientInfo message.
type ClientInfo struct {
	Language        *string `json:"language,omitempty"`
	Version         *string `json:"version,omitempty"`
	LanguageVersion *string `json:"languageVersion,omitempty"`
	OS              *string `json:"os,omitempty"`
	OSVersion       *string `json:"osVersion,omitempty"`
}

// GetLanguage returns Language, or the zero value when unset.
func (x *ClientInfo) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

// GetVersion returns Version, or the zero value when unset.
func (x *ClientInfo) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

// GetLanguageVersion returns LanguageVersion, or the zero value when unset.
func (x *ClientInfo) GetLanguageVersion() string {
	if x != nil && x.LanguageVersion != nil {
		return *x.LanguageVersion
	}
	return ""
}

// GetOS returns OS, or the zero value when unset.
func (x *ClientInfo) GetOS() string {
	if x != nil && x.OS != nil {
		return *x.OS
	}
	return ""
}

// GetOSVersion returns OSVersion, or the zero value when unset.
func (x *ClientInfo) GetOSVersion() string {
	if x != nil && x.OSVersion != nil {
		return *x.OSVersion
	}
	return ""
}

// OutputConfig mirrors the antigravity.localharness.OutputConfig message.
type OutputConfig struct {
	Port   *int32  `json:"port,omitempty"`
	APIKey *string `json:"apiKey,omitempty"`
}

// GetPort returns Port, or the zero value when unset.
func (x *OutputConfig) GetPort() int32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

// GetAPIKey returns APIKey, or the zero value when unset.
func (x *OutputConfig) GetAPIKey() string {
	if x != nil && x.APIKey != nil {
		return *x.APIKey
	}
	return ""
}

// InitializeConversationEvent mirrors the antigravity.localharness.InitializeConversationEvent message.
type InitializeConversationEvent struct {
	Config *HarnessConfig `json:"config,omitempty"`
}

// GetConfig returns Config, or nil when x is nil.
func (x *InitializeConversationEvent) GetConfig() *HarnessConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// HarnessConfig mirrors the antigravity.localharness.HarnessConfig message.
type HarnessConfig struct {
	CascadeID               *string                               `json:"cascadeId,omitempty"`
	SystemInstructions      *SystemInstructions                   `json:"systemInstructions,omitempty"`
	Tools                   []*Tool                               `json:"tools,omitempty"`
	HarnessSideTools        *HarnessSideTools                     `json:"harnessSideTools,omitempty"`
	CompactionThreshold     *uint32                               `json:"compactionThreshold,omitempty"`
	Workspaces              []*Workspace                          `json:"workspaces,omitempty"`
	SkillsPaths             []string                              `json:"skillsPaths,omitempty"`
	FinishToolSchemaJSON    *string                               `json:"finishToolSchemaJson,omitempty"`
	InitialTrajectory       []byte                                `json:"initialTrajectory,omitzero"`
	AppDataDir              *string                               `json:"appDataDir,omitempty"`
	MCPServers              []*MCPServerConfig                    `json:"mcpServers,omitempty"`
	Models                  []*ModelConfig                        `json:"models,omitempty"`
	EnabledHooks            []LifecycleHook                       `json:"enabledHooks,omitempty"`
	CustomSubagents         []*CustomAgent                        `json:"customSubagents,omitempty"`
	ToolOutputTruncation    *ToolOutputTruncation                 `json:"toolOutputTruncation,omitempty"`
	SessionContinuationMode *HarnessConfigSessionContinuationMode `json:"sessionContinuationMode,omitempty"`
	RetryConfig             *RetryConfig                          `json:"retryConfig,omitempty"`
	PolicyConfig            *PolicyConfig                         `json:"policyConfig,omitempty"`
	AgentBehavior           *AgentBehavior                        `json:"agentBehavior,omitempty"`
	BudgetConfig            *BudgetConfig                         `json:"budgetConfig,omitempty"`
	CompactionConfig        *CompactionConfig                     `json:"compactionConfig,omitempty"`
	SkillsConfig            *SkillsConfig                         `json:"skillsConfig,omitempty"`
	RulesConfig             *RulesConfig                          `json:"rulesConfig,omitempty"`
}

// GetCascadeID returns CascadeID, or the zero value when unset.
func (x *HarnessConfig) GetCascadeID() string {
	if x != nil && x.CascadeID != nil {
		return *x.CascadeID
	}
	return ""
}

// GetSystemInstructions returns SystemInstructions, or nil when x is nil.
func (x *HarnessConfig) GetSystemInstructions() *SystemInstructions {
	if x != nil {
		return x.SystemInstructions
	}
	return nil
}

// GetTools returns Tools, or nil when x is nil.
func (x *HarnessConfig) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

// GetHarnessSideTools returns HarnessSideTools, or nil when x is nil.
func (x *HarnessConfig) GetHarnessSideTools() *HarnessSideTools {
	if x != nil {
		return x.HarnessSideTools
	}
	return nil
}

// GetCompactionThreshold returns CompactionThreshold, or the zero value when unset.
func (x *HarnessConfig) GetCompactionThreshold() uint32 {
	if x != nil && x.CompactionThreshold != nil {
		return *x.CompactionThreshold
	}
	return 0
}

// GetWorkspaces returns Workspaces, or nil when x is nil.
func (x *HarnessConfig) GetWorkspaces() []*Workspace {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

// GetSkillsPaths returns SkillsPaths, or nil when x is nil.
func (x *HarnessConfig) GetSkillsPaths() []string {
	if x != nil {
		return x.SkillsPaths
	}
	return nil
}

// GetFinishToolSchemaJSON returns FinishToolSchemaJSON, or the zero value when unset.
func (x *HarnessConfig) GetFinishToolSchemaJSON() string {
	if x != nil && x.FinishToolSchemaJSON != nil {
		return *x.FinishToolSchemaJSON
	}
	return ""
}

// GetInitialTrajectory returns InitialTrajectory, or nil when x is nil.
func (x *HarnessConfig) GetInitialTrajectory() []byte {
	if x != nil {
		return x.InitialTrajectory
	}
	return nil
}

// GetAppDataDir returns AppDataDir, or the zero value when unset.
func (x *HarnessConfig) GetAppDataDir() string {
	if x != nil && x.AppDataDir != nil {
		return *x.AppDataDir
	}
	return ""
}

// GetMCPServers returns MCPServers, or nil when x is nil.
func (x *HarnessConfig) GetMCPServers() []*MCPServerConfig {
	if x != nil {
		return x.MCPServers
	}
	return nil
}

// GetModels returns Models, or nil when x is nil.
func (x *HarnessConfig) GetModels() []*ModelConfig {
	if x != nil {
		return x.Models
	}
	return nil
}

// GetEnabledHooks returns EnabledHooks, or nil when x is nil.
func (x *HarnessConfig) GetEnabledHooks() []LifecycleHook {
	if x != nil {
		return x.EnabledHooks
	}
	return nil
}

// GetCustomSubagents returns CustomSubagents, or nil when x is nil.
func (x *HarnessConfig) GetCustomSubagents() []*CustomAgent {
	if x != nil {
		return x.CustomSubagents
	}
	return nil
}

// GetToolOutputTruncation returns ToolOutputTruncation, or nil when x is nil.
func (x *HarnessConfig) GetToolOutputTruncation() *ToolOutputTruncation {
	if x != nil {
		return x.ToolOutputTruncation
	}
	return nil
}

// GetSessionContinuationMode returns SessionContinuationMode, or the zero value when unset.
func (x *HarnessConfig) GetSessionContinuationMode() HarnessConfigSessionContinuationMode {
	if x != nil && x.SessionContinuationMode != nil {
		return *x.SessionContinuationMode
	}
	return ""
}

// GetRetryConfig returns RetryConfig, or nil when x is nil.
func (x *HarnessConfig) GetRetryConfig() *RetryConfig {
	if x != nil {
		return x.RetryConfig
	}
	return nil
}

// GetPolicyConfig returns PolicyConfig, or nil when x is nil.
func (x *HarnessConfig) GetPolicyConfig() *PolicyConfig {
	if x != nil {
		return x.PolicyConfig
	}
	return nil
}

// GetAgentBehavior returns AgentBehavior, or the zero value when unset.
func (x *HarnessConfig) GetAgentBehavior() AgentBehavior {
	if x != nil && x.AgentBehavior != nil {
		return *x.AgentBehavior
	}
	return ""
}

// GetBudgetConfig returns BudgetConfig, or nil when x is nil.
func (x *HarnessConfig) GetBudgetConfig() *BudgetConfig {
	if x != nil {
		return x.BudgetConfig
	}
	return nil
}

// GetCompactionConfig returns CompactionConfig, or nil when x is nil.
func (x *HarnessConfig) GetCompactionConfig() *CompactionConfig {
	if x != nil {
		return x.CompactionConfig
	}
	return nil
}

// GetSkillsConfig returns SkillsConfig, or nil when x is nil.
func (x *HarnessConfig) GetSkillsConfig() *SkillsConfig {
	if x != nil {
		return x.SkillsConfig
	}
	return nil
}

// GetRulesConfig returns RulesConfig, or nil when x is nil.
func (x *HarnessConfig) GetRulesConfig() *RulesConfig {
	if x != nil {
		return x.RulesConfig
	}
	return nil
}

// SystemInstructions mirrors the antigravity.localharness.SystemInstructions message.
// At most one of the type oneof fields (Custom, Appended) is set.
type SystemInstructions struct {
	Custom   *CustomSystemInstructions   `json:"custom,omitempty"`   // oneof type
	Appended *AppendedSystemInstructions `json:"appended,omitempty"` // oneof type
}

// GetCustom returns Custom, or nil when x is nil.
func (x *SystemInstructions) GetCustom() *CustomSystemInstructions {
	if x != nil {
		return x.Custom
	}
	return nil
}

// GetAppended returns Appended, or nil when x is nil.
func (x *SystemInstructions) GetAppended() *AppendedSystemInstructions {
	if x != nil {
		return x.Appended
	}
	return nil
}

// CustomSystemInstructions mirrors the antigravity.localharness.CustomSystemInstructions message.
type CustomSystemInstructions struct {
	Part []*CustomSystemInstructionsPart `json:"part,omitempty"`
}

// GetPart returns Part, or nil when x is nil.
func (x *CustomSystemInstructions) GetPart() []*CustomSystemInstructionsPart {
	if x != nil {
		return x.Part
	}
	return nil
}

// CustomSystemInstructionsPart mirrors the antigravity.localharness.CustomSystemInstructions.Part message.
// At most one of the part oneof fields (Text, Template, BuiltinSection) is set.
type CustomSystemInstructionsPart struct {
	Text           *string                    `json:"text,omitempty"`           // oneof part
	Template       *SystemInstructionTemplate `json:"template,omitempty"`       // oneof part
	BuiltinSection *string                    `json:"builtinSection,omitempty"` // oneof part
}

// GetText returns Text, or the zero value when unset.
func (x *CustomSystemInstructionsPart) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

// GetTemplate returns Template, or nil when x is nil.
func (x *CustomSystemInstructionsPart) GetTemplate() *SystemInstructionTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

// GetBuiltinSection returns BuiltinSection, or the zero value when unset.
func (x *CustomSystemInstructionsPart) GetBuiltinSection() string {
	if x != nil && x.BuiltinSection != nil {
		return *x.BuiltinSection
	}
	return ""
}

// SystemInstructionTemplate mirrors the antigravity.localharness.SystemInstructionTemplate message.
type SystemInstructionTemplate struct {
	Name *string                         `json:"name,omitempty"`
	Args []*SystemInstructionTemplateArg `json:"args,omitempty"`
}

// GetName returns Name, or the zero value when unset.
func (x *SystemInstructionTemplate) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetArgs returns Args, or nil when x is nil.
func (x *SystemInstructionTemplate) GetArgs() []*SystemInstructionTemplateArg {
	if x != nil {
		return x.Args
	}
	return nil
}

// SystemInstructionTemplateArg mirrors the antigravity.localharness.SystemInstructionTemplate.Arg message.
type SystemInstructionTemplateArg struct {
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

// GetName returns Name, or the zero value when unset.
func (x *SystemInstructionTemplateArg) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetValue returns Value, or the zero value when unset.
func (x *SystemInstructionTemplateArg) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

// AppendedSystemInstructions mirrors the antigravity.localharness.AppendedSystemInstructions message.
type AppendedSystemInstructions struct {
	CustomIdentity   *string                              `json:"customIdentity,omitempty"`
	AppendedSections []*AppendedSystemInstructionsSection `json:"appendedSections,omitempty"`
}

// GetCustomIdentity returns CustomIdentity, or the zero value when unset.
func (x *AppendedSystemInstructions) GetCustomIdentity() string {
	if x != nil && x.CustomIdentity != nil {
		return *x.CustomIdentity
	}
	return ""
}

// GetAppendedSections returns AppendedSections, or nil when x is nil.
func (x *AppendedSystemInstructions) GetAppendedSections() []*AppendedSystemInstructionsSection {
	if x != nil {
		return x.AppendedSections
	}
	return nil
}

// AppendedSystemInstructionsSection mirrors the antigravity.localharness.AppendedSystemInstructions.Section message.
type AppendedSystemInstructionsSection struct {
	Title   *string `json:"title,omitempty"`
	Content *string `json:"content,omitempty"`
}

// GetTitle returns Title, or the zero value when unset.
func (x *AppendedSystemInstructionsSection) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

// GetContent returns Content, or the zero value when unset.
func (x *AppendedSystemInstructionsSection) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

// Tool mirrors the antigravity.localharness.Tool message.
type Tool struct {
	Name                 *string `json:"name,omitempty"`
	Description          *string `json:"description,omitempty"`
	ParametersJSONSchema *string `json:"parametersJsonSchema,omitempty"`
	ResponseJSONSchema   *string `json:"responseJsonSchema,omitempty"`
	DeferLoading         *bool   `json:"deferLoading,omitempty"`
}

// GetName returns Name, or the zero value when unset.
func (x *Tool) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetDescription returns Description, or the zero value when unset.
func (x *Tool) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// GetParametersJSONSchema returns ParametersJSONSchema, or the zero value when unset.
func (x *Tool) GetParametersJSONSchema() string {
	if x != nil && x.ParametersJSONSchema != nil {
		return *x.ParametersJSONSchema
	}
	return ""
}

// GetResponseJSONSchema returns ResponseJSONSchema, or the zero value when unset.
func (x *Tool) GetResponseJSONSchema() string {
	if x != nil && x.ResponseJSONSchema != nil {
		return *x.ResponseJSONSchema
	}
	return ""
}

// GetDeferLoading returns DeferLoading, or the zero value when unset.
func (x *Tool) GetDeferLoading() bool {
	if x != nil && x.DeferLoading != nil {
		return *x.DeferLoading
	}
	return false
}

// HarnessSideTools mirrors the antigravity.localharness.HarnessSideTools message.
type HarnessSideTools struct {
	Find             *FindToolConfig           `json:"find,omitempty"`
	RunCommand       *RunCommandToolConfig     `json:"runCommand,omitempty"`
	Subagents        *SubagentsConfig          `json:"subagents,omitempty"`
	UserQuestions    *UserQuestionsConfig      `json:"userQuestions,omitempty"`
	FileEdit         *FileEditToolConfig       `json:"fileEdit,omitempty"`
	ViewFile         *ViewFileToolConfig       `json:"viewFile,omitempty"`
	WriteToFile      *WriteToFileToolConfig    `json:"writeToFile,omitempty"`
	GrepSearch       *GrepSearchToolConfig     `json:"grepSearch,omitempty"`
	ListDir          *ListDirToolConfig        `json:"listDir,omitempty"`
	Permissions      *PermissionsConfig        `json:"permissions,omitempty"`
	GenerateImage    *GenerateImageToolConfig  `json:"generateImage,omitempty"`
	SearchWeb        *SearchWebToolConfig      `json:"searchWeb,omitempty"`
	ReadURLContent   *ReadURLContentToolConfig `json:"readUrlContent,omitempty"`
	ToolSearchConfig *ToolSearchConfig         `json:"toolSearchConfig,omitempty"`
	ManageTask       *ManageTaskToolConfig     `json:"manageTask,omitempty"`
	Schedule         *ScheduleToolConfig       `json:"schedule,omitempty"`
}

// GetFind returns Find, or nil when x is nil.
func (x *HarnessSideTools) GetFind() *FindToolConfig {
	if x != nil {
		return x.Find
	}
	return nil
}

// GetRunCommand returns RunCommand, or nil when x is nil.
func (x *HarnessSideTools) GetRunCommand() *RunCommandToolConfig {
	if x != nil {
		return x.RunCommand
	}
	return nil
}

// GetSubagents returns Subagents, or nil when x is nil.
func (x *HarnessSideTools) GetSubagents() *SubagentsConfig {
	if x != nil {
		return x.Subagents
	}
	return nil
}

// GetUserQuestions returns UserQuestions, or nil when x is nil.
func (x *HarnessSideTools) GetUserQuestions() *UserQuestionsConfig {
	if x != nil {
		return x.UserQuestions
	}
	return nil
}

// GetFileEdit returns FileEdit, or nil when x is nil.
func (x *HarnessSideTools) GetFileEdit() *FileEditToolConfig {
	if x != nil {
		return x.FileEdit
	}
	return nil
}

// GetViewFile returns ViewFile, or nil when x is nil.
func (x *HarnessSideTools) GetViewFile() *ViewFileToolConfig {
	if x != nil {
		return x.ViewFile
	}
	return nil
}

// GetWriteToFile returns WriteToFile, or nil when x is nil.
func (x *HarnessSideTools) GetWriteToFile() *WriteToFileToolConfig {
	if x != nil {
		return x.WriteToFile
	}
	return nil
}

// GetGrepSearch returns GrepSearch, or nil when x is nil.
func (x *HarnessSideTools) GetGrepSearch() *GrepSearchToolConfig {
	if x != nil {
		return x.GrepSearch
	}
	return nil
}

// GetListDir returns ListDir, or nil when x is nil.
func (x *HarnessSideTools) GetListDir() *ListDirToolConfig {
	if x != nil {
		return x.ListDir
	}
	return nil
}

// GetPermissions returns Permissions, or nil when x is nil.
func (x *HarnessSideTools) GetPermissions() *PermissionsConfig {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// GetGenerateImage returns GenerateImage, or nil when x is nil.
func (x *HarnessSideTools) GetGenerateImage() *GenerateImageToolConfig {
	if x != nil {
		return x.GenerateImage
	}
	return nil
}

// GetSearchWeb returns SearchWeb, or nil when x is nil.
func (x *HarnessSideTools) GetSearchWeb() *SearchWebToolConfig {
	if x != nil {
		return x.SearchWeb
	}
	return nil
}

// GetReadURLContent returns ReadURLContent, or nil when x is nil.
func (x *HarnessSideTools) GetReadURLContent() *ReadURLContentToolConfig {
	if x != nil {
		return x.ReadURLContent
	}
	return nil
}

// GetToolSearchConfig returns ToolSearchConfig, or nil when x is nil.
func (x *HarnessSideTools) GetToolSearchConfig() *ToolSearchConfig {
	if x != nil {
		return x.ToolSearchConfig
	}
	return nil
}

// GetManageTask returns ManageTask, or nil when x is nil.
func (x *HarnessSideTools) GetManageTask() *ManageTaskToolConfig {
	if x != nil {
		return x.ManageTask
	}
	return nil
}

// GetSchedule returns Schedule, or nil when x is nil.
func (x *HarnessSideTools) GetSchedule() *ScheduleToolConfig {
	if x != nil {
		return x.Schedule
	}
	return nil
}

// FindToolConfig mirrors the antigravity.localharness.FindToolConfig message.
type FindToolConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// GetEnabled returns Enabled, or the zero value when unset.
func (x *FindToolConfig) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// RunCommandToolConfig mirrors the antigravity.localharness.RunCommandToolConfig message.
type RunCommandToolConfig struct {
	Enabled              *bool              `json:"enabled,omitempty"`
	MaxTimeoutMs         *uint32            `json:"maxTimeoutMs,omitempty"`
	EnableDaemonCommands *bool              `json:"enableDaemonCommands,omitempty"`
	EnableSandbox        *bool              `json:"enableSandbox,omitempty"`
	ExecutionMode        *ToolExecutionMode `json:"executionMode,omitempty"`
}

// GetEnabled returns Enabled, or the zero value when unset.
func (x *RunCommandToolConfig) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// GetMaxTimeoutMs returns MaxTimeoutMs, or the zero value when unset.
func (x *RunCommandToolConfig) GetMaxTimeoutMs() uint32 {
	if x != nil && x.MaxTimeoutMs != nil {
		return *x.MaxTimeoutMs
	}
	return 0
}

// GetEnableDaemonCommands returns EnableDaemonCommands, or the zero value when unset.
func (x *RunCommandToolConfig) GetEnableDaemonCommands() bool {
	if x != nil && x.EnableDaemonCommands != nil {
		return *x.EnableDaemonCommands
	}
	return false
}

// GetEnableSandbox returns EnableSandbox, or the zero value when unset.
func (x *RunCommandToolConfig) GetEnableSandbox() bool {
	if x != nil && x.EnableSandbox != nil {
		return *x.EnableSandbox
	}
	return false
}

// GetExecutionMode returns ExecutionMode, or the zero value when unset.
func (x *RunCommandToolConfig) GetExecutionMode() ToolExecutionMode {
	if x != nil && x.ExecutionMode != nil {
		return *x.ExecutionMode
	}
	return ""
}

// SubagentsConfig mirrors the antigravity.localharness.SubagentsConfig message.
type SubagentsConfig struct {
	Enabled          *bool    `json:"enabled,omitempty"`
	MaxNestingDepth  *int32   `json:"maxNestingDepth,omitempty"`
	AllowedSubagents []string `json:"allowedSubagents,omitempty"`
}

// GetEnabled returns Enabled, or the zero value when unset.
func (x *SubagentsConfig) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// GetMaxNestingDepth returns MaxNestingDepth, or the proto default 1 when unset.
func (x *SubagentsConfig) GetMaxNestingDepth() int32 {
	if x != nil && x.MaxNestingDepth != nil {
		return *x.MaxNestingDepth
	}
	return 1
}

// GetAllowedSubagents returns AllowedSubagents, or nil when x is nil.
func (x *SubagentsConfig) GetAllowedSubagents() []string {
	if x != nil {
		return x.AllowedSubagents
	}
	return nil
}

// UserQuestionsConfig mirrors the antigravity.localharness.UserQuestionsConfig message.
type UserQuestionsConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// GetEnabled returns Enabled, or the zero value when unset.
func (x *UserQuestionsConfig) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// FileEditToolConfig mirrors the antigravity.localharness.FileEditToolConfig message.
type FileEditToolConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// GetEnabled returns Enabled, or the zero value when unset.
func (x *FileEditToolConfig) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// ViewFileToolConfig mirrors the antigravity.localharness.ViewFileToolConfig message.
type ViewFileToolConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// GetEnabled returns Enabled, or the zero value when unset.
func (x *ViewFileToolConfig) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// WriteToFileToolConfig mirrors the antigravity.localharness.WriteToFileToolConfig message.
type WriteToFileToolConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// GetEnabled returns Enabled, or the zero value when unset.
func (x *WriteToFileToolConfig) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// GrepSearchToolConfig mirrors the antigravity.localharness.GrepSearchToolConfig message.
type GrepSearchToolConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// GetEnabled returns Enabled, or the zero value when unset.
func (x *GrepSearchToolConfig) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// ListDirToolConfig mirrors the antigravity.localharness.ListDirToolConfig message.
type ListDirToolConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// GetEnabled returns Enabled, or the zero value when unset.
func (x *ListDirToolConfig) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// PermissionsConfig mirrors the antigravity.localharness.PermissionsConfig message.
type PermissionsConfig struct {
	EnforceWorkspaceValidation *bool `json:"enforceWorkspaceValidation,omitempty"`
}

// GetEnforceWorkspaceValidation returns EnforceWorkspaceValidation, or the zero value when unset.
func (x *PermissionsConfig) GetEnforceWorkspaceValidation() bool {
	if x != nil && x.EnforceWorkspaceValidation != nil {
		return *x.EnforceWorkspaceValidation
	}
	return false
}

// GenerateImageToolConfig mirrors the antigravity.localharness.GenerateImageToolConfig message.
type GenerateImageToolConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// GetEnabled returns Enabled, or the zero value when unset.
func (x *GenerateImageToolConfig) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// SearchWebToolConfig mirrors the antigravity.localharness.SearchWebToolConfig message.
type SearchWebToolConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// GetEnabled returns Enabled, or the zero value when unset.
func (x *SearchWebToolConfig) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// ReadURLContentToolConfig mirrors the antigravity.localharness.ReadUrlContentToolConfig message.
type ReadURLContentToolConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// GetEnabled returns Enabled, or the zero value when unset.
func (x *ReadURLContentToolConfig) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// ToolSearchConfig mirrors the antigravity.localharness.ToolSearchConfig message.
type ToolSearchConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// GetEnabled returns Enabled, or the zero value when unset.
func (x *ToolSearchConfig) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// ManageTaskToolConfig mirrors the antigravity.localharness.ManageTaskToolConfig message.
type ManageTaskToolConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// GetEnabled returns Enabled, or the zero value when unset.
func (x *ManageTaskToolConfig) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// ScheduleToolConfig mirrors the antigravity.localharness.ScheduleToolConfig message.
type ScheduleToolConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// GetEnabled returns Enabled, or the zero value when unset.
func (x *ScheduleToolConfig) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// Workspace mirrors the antigravity.localharness.Workspace message.
// At most one of the workspace_type oneof fields (FilesystemWorkspace) is set.
type Workspace struct {
	FilesystemWorkspace *FilesystemWorkspace `json:"filesystemWorkspace,omitempty"` // oneof workspace_type
}

// GetFilesystemWorkspace returns FilesystemWorkspace, or nil when x is nil.
func (x *Workspace) GetFilesystemWorkspace() *FilesystemWorkspace {
	if x != nil {
		return x.FilesystemWorkspace
	}
	return nil
}

// FilesystemWorkspace mirrors the antigravity.localharness.FilesystemWorkspace message.
type FilesystemWorkspace struct {
	Directory *string `json:"directory,omitempty"`
}

// GetDirectory returns Directory, or the zero value when unset.
func (x *FilesystemWorkspace) GetDirectory() string {
	if x != nil && x.Directory != nil {
		return *x.Directory
	}
	return ""
}

// MCPServerConfig mirrors the antigravity.localharness.McpServerConfig message.
// At most one of the transport oneof fields (Stdio, HTTP) is set.
type MCPServerConfig struct {
	Name             *string                          `json:"name,omitempty"`
	Stdio            *MCPStdioTransport               `json:"stdio,omitempty"` // oneof transport
	HTTP             *MCPHTTPTransport                `json:"http,omitempty"`  // oneof transport
	EnabledTools     []string                         `json:"enabledTools,omitempty"`
	DisabledTools    []string                         `json:"disabledTools,omitempty"`
	AuthProviderType *MCPServerConfigAuthProviderType `json:"authProviderType,omitempty"`
	TimeoutSeconds   *int32                           `json:"timeoutSeconds,omitempty"`
}

// GetName returns Name, or the zero value when unset.
func (x *MCPServerConfig) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetStdio returns Stdio, or nil when x is nil.
func (x *MCPServerConfig) GetStdio() *MCPStdioTransport {
	if x != nil {
		return x.Stdio
	}
	return nil
}

// GetHTTP returns HTTP, or nil when x is nil.
func (x *MCPServerConfig) GetHTTP() *MCPHTTPTransport {
	if x != nil {
		return x.HTTP
	}
	return nil
}

// GetEnabledTools returns EnabledTools, or nil when x is nil.
func (x *MCPServerConfig) GetEnabledTools() []string {
	if x != nil {
		return x.EnabledTools
	}
	return nil
}

// GetDisabledTools returns DisabledTools, or nil when x is nil.
func (x *MCPServerConfig) GetDisabledTools() []string {
	if x != nil {
		return x.DisabledTools
	}
	return nil
}

// GetAuthProviderType returns AuthProviderType, or the zero value when unset.
func (x *MCPServerConfig) GetAuthProviderType() MCPServerConfigAuthProviderType {
	if x != nil && x.AuthProviderType != nil {
		return *x.AuthProviderType
	}
	return ""
}

// GetTimeoutSeconds returns TimeoutSeconds, or the zero value when unset.
func (x *MCPServerConfig) GetTimeoutSeconds() int32 {
	if x != nil && x.TimeoutSeconds != nil {
		return *x.TimeoutSeconds
	}
	return 0
}

// MCPStdioTransport mirrors the antigravity.localharness.McpStdioTransport message.
type MCPStdioTransport struct {
	Command *string           `json:"command,omitempty"`
	Args    []string          `json:"args,omitempty"`
	Env     map[string]string `json:"env,omitempty"`
}

// GetCommand returns Command, or the zero value when unset.
func (x *MCPStdioTransport) GetCommand() string {
	if x != nil && x.Command != nil {
		return *x.Command
	}
	return ""
}

// GetArgs returns Args, or nil when x is nil.
func (x *MCPStdioTransport) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// GetEnv returns Env, or nil when x is nil.
func (x *MCPStdioTransport) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// MCPHTTPTransport mirrors the antigravity.localharness.McpHttpTransport message.
type MCPHTTPTransport struct {
	URL     *string           `json:"url,omitempty"`
	Headers map[string]string `json:"headers,omitempty"`
}

// GetURL returns URL, or the zero value when unset.
func (x *MCPHTTPTransport) GetURL() string {
	if x != nil && x.URL != nil {
		return *x.URL
	}
	return ""
}

// GetHeaders returns Headers, or nil when x is nil.
func (x *MCPHTTPTransport) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// ModelConfig mirrors the antigravity.localharness.ModelConfig message.
// At most one of the endpoint oneof fields (GeminiAPIEndpoint, VertexEndpoint, GemmaEndpoint, CustomEndpoint) is set.
type ModelConfig struct {
	Name              *string            `json:"name,omitempty"`
	Types             []ModelType        `json:"types,omitempty"`
	GeminiAPIEndpoint *GeminiAPIEndpoint `json:"geminiApiEndpoint,omitempty"` // oneof endpoint
	VertexEndpoint    *VertexEndpoint    `json:"vertexEndpoint,omitempty"`    // oneof endpoint
	GemmaEndpoint     *GemmaEndpoint     `json:"gemmaEndpoint,omitempty"`     // oneof endpoint
	CustomEndpoint    *CustomEndpoint    `json:"customEndpoint,omitempty"`    // oneof endpoint
}

// GetName returns Name, or the zero value when unset.
func (x *ModelConfig) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetTypes returns Types, or nil when x is nil.
func (x *ModelConfig) GetTypes() []ModelType {
	if x != nil {
		return x.Types
	}
	return nil
}

// GetGeminiAPIEndpoint returns GeminiAPIEndpoint, or nil when x is nil.
func (x *ModelConfig) GetGeminiAPIEndpoint() *GeminiAPIEndpoint {
	if x != nil {
		return x.GeminiAPIEndpoint
	}
	return nil
}

// GetVertexEndpoint returns VertexEndpoint, or nil when x is nil.
func (x *ModelConfig) GetVertexEndpoint() *VertexEndpoint {
	if x != nil {
		return x.VertexEndpoint
	}
	return nil
}

// GetGemmaEndpoint returns GemmaEndpoint, or nil when x is nil.
func (x *ModelConfig) GetGemmaEndpoint() *GemmaEndpoint {
	if x != nil {
		return x.GemmaEndpoint
	}
	return nil
}

// GetCustomEndpoint returns CustomEndpoint, or nil when x is nil.
func (x *ModelConfig) GetCustomEndpoint() *CustomEndpoint {
	if x != nil {
		return x.CustomEndpoint
	}
	return nil
}

// GeminiAPIEndpoint mirrors the antigravity.localharness.GeminiAPIEndpoint message.
type GeminiAPIEndpoint struct {
	BaseURL     *string             `json:"baseUrl,omitempty"`
	HTTPHeaders map[string]string   `json:"httpHeaders,omitempty"`
	APIKey      *string             `json:"apiKey,omitempty"`
	Options     *GeminiModelOptions `json:"options,omitempty"`
}

// GetBaseURL returns BaseURL, or the zero value when unset.
func (x *GeminiAPIEndpoint) GetBaseURL() string {
	if x != nil && x.BaseURL != nil {
		return *x.BaseURL
	}
	return ""
}

// GetHTTPHeaders returns HTTPHeaders, or nil when x is nil.
func (x *GeminiAPIEndpoint) GetHTTPHeaders() map[string]string {
	if x != nil {
		return x.HTTPHeaders
	}
	return nil
}

// GetAPIKey returns APIKey, or the zero value when unset.
func (x *GeminiAPIEndpoint) GetAPIKey() string {
	if x != nil && x.APIKey != nil {
		return *x.APIKey
	}
	return ""
}

// GetOptions returns Options, or nil when x is nil.
func (x *GeminiAPIEndpoint) GetOptions() *GeminiModelOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// GeminiModelOptions mirrors the antigravity.localharness.GeminiModelOptions message.
type GeminiModelOptions struct {
	ThinkingLevel *string `json:"thinkingLevel,omitempty"`
	ServiceTier   *string `json:"serviceTier,omitempty"`
}

// GetThinkingLevel returns ThinkingLevel, or the zero value when unset.
func (x *GeminiModelOptions) GetThinkingLevel() string {
	if x != nil && x.ThinkingLevel != nil {
		return *x.ThinkingLevel
	}
	return ""
}

// GetServiceTier returns ServiceTier, or the zero value when unset.
func (x *GeminiModelOptions) GetServiceTier() string {
	if x != nil && x.ServiceTier != nil {
		return *x.ServiceTier
	}
	return ""
}

// VertexEndpoint mirrors the antigravity.localharness.VertexEndpoint message.
type VertexEndpoint struct {
	BaseURL     *string             `json:"baseUrl,omitempty"`
	HTTPHeaders map[string]string   `json:"httpHeaders,omitempty"`
	Project     *string             `json:"project,omitempty"`
	Location    *string             `json:"location,omitempty"`
	Options     *GeminiModelOptions `json:"options,omitempty"`
	APIKey      *string             `json:"apiKey,omitempty"`
}

// GetBaseURL returns BaseURL, or the zero value when unset.
func (x *VertexEndpoint) GetBaseURL() string {
	if x != nil && x.BaseURL != nil {
		return *x.BaseURL
	}
	return ""
}

// GetHTTPHeaders returns HTTPHeaders, or nil when x is nil.
func (x *VertexEndpoint) GetHTTPHeaders() map[string]string {
	if x != nil {
		return x.HTTPHeaders
	}
	return nil
}

// GetProject returns Project, or the zero value when unset.
func (x *VertexEndpoint) GetProject() string {
	if x != nil && x.Project != nil {
		return *x.Project
	}
	return ""
}

// GetLocation returns Location, or the zero value when unset.
func (x *VertexEndpoint) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

// GetOptions returns Options, or nil when x is nil.
func (x *VertexEndpoint) GetOptions() *GeminiModelOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// GetAPIKey returns APIKey, or the zero value when unset.
func (x *VertexEndpoint) GetAPIKey() string {
	if x != nil && x.APIKey != nil {
		return *x.APIKey
	}
	return ""
}

// GemmaEndpoint mirrors the antigravity.localharness.GemmaEndpoint message.
type GemmaEndpoint struct {
	BaseURL *string `json:"baseUrl,omitempty"`
}

// GetBaseURL returns BaseURL, or the zero value when unset.
func (x *GemmaEndpoint) GetBaseURL() string {
	if x != nil && x.BaseURL != nil {
		return *x.BaseURL
	}
	return ""
}

// CustomEndpoint mirrors the antigravity.localharness.CustomEndpoint message.
type CustomEndpoint struct {
	BackendType *string `json:"backendType,omitempty"`
	ConfigJSON  *string `json:"configJson,omitempty"`
}

// GetBackendType returns BackendType, or the zero value when unset.
func (x *CustomEndpoint) GetBackendType() string {
	if x != nil && x.BackendType != nil {
		return *x.BackendType
	}
	return ""
}

// GetConfigJSON returns ConfigJSON, or the zero value when unset.
func (x *CustomEndpoint) GetConfigJSON() string {
	if x != nil && x.ConfigJSON != nil {
		return *x.ConfigJSON
	}
	return ""
}

// CustomAgent mirrors the antigravity.localharness.CustomAgent message.
type CustomAgent struct {
	Name               *string               `json:"name,omitempty"`
	Description        *string               `json:"description,omitempty"`
	SystemInstructions *SystemInstructions   `json:"systemInstructions,omitempty"`
	HarnessSideTools   *HarnessSideTools     `json:"harnessSideTools,omitempty"`
	Tools              []*Tool               `json:"tools,omitempty"`
	SkillsConfig       *SubagentSkillsConfig `json:"skillsConfig,omitempty"`
	AgentBehavior      *AgentBehavior        `json:"agentBehavior,omitempty"`
	Model              *ModelConfig          `json:"model,omitempty"`
}

// GetName returns Name, or the zero value when unset.
func (x *CustomAgent) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetDescription returns Description, or the zero value when unset.
func (x *CustomAgent) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// GetSystemInstructions returns SystemInstructions, or nil when x is nil.
func (x *CustomAgent) GetSystemInstructions() *SystemInstructions {
	if x != nil {
		return x.SystemInstructions
	}
	return nil
}

// GetHarnessSideTools returns HarnessSideTools, or nil when x is nil.
func (x *CustomAgent) GetHarnessSideTools() *HarnessSideTools {
	if x != nil {
		return x.HarnessSideTools
	}
	return nil
}

// GetTools returns Tools, or nil when x is nil.
func (x *CustomAgent) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

// GetSkillsConfig returns SkillsConfig, or nil when x is nil.
func (x *CustomAgent) GetSkillsConfig() *SubagentSkillsConfig {
	if x != nil {
		return x.SkillsConfig
	}
	return nil
}

// GetAgentBehavior returns AgentBehavior, or the zero value when unset.
func (x *CustomAgent) GetAgentBehavior() AgentBehavior {
	if x != nil && x.AgentBehavior != nil {
		return *x.AgentBehavior
	}
	return ""
}

// GetModel returns Model, or nil when x is nil.
func (x *CustomAgent) GetModel() *ModelConfig {
	if x != nil {
		return x.Model
	}
	return nil
}

// SubagentSkillsConfig mirrors the antigravity.localharness.SubagentSkillsConfig message.
// At most one of the mode oneof fields (InheritConfig, NoneConfig, OverrideConfig) is set.
type SubagentSkillsConfig struct {
	InheritConfig  *SubagentSkillsConfigInheritConfig  `json:"inheritConfig,omitempty"`  // oneof mode
	NoneConfig     *SubagentSkillsConfigNoneConfig     `json:"noneConfig,omitempty"`     // oneof mode
	OverrideConfig *SubagentSkillsConfigOverrideConfig `json:"overrideConfig,omitempty"` // oneof mode
}

// GetInheritConfig returns InheritConfig, or nil when x is nil.
func (x *SubagentSkillsConfig) GetInheritConfig() *SubagentSkillsConfigInheritConfig {
	if x != nil {
		return x.InheritConfig
	}
	return nil
}

// GetNoneConfig returns NoneConfig, or nil when x is nil.
func (x *SubagentSkillsConfig) GetNoneConfig() *SubagentSkillsConfigNoneConfig {
	if x != nil {
		return x.NoneConfig
	}
	return nil
}

// GetOverrideConfig returns OverrideConfig, or nil when x is nil.
func (x *SubagentSkillsConfig) GetOverrideConfig() *SubagentSkillsConfigOverrideConfig {
	if x != nil {
		return x.OverrideConfig
	}
	return nil
}

// SubagentSkillsConfigInheritConfig mirrors the antigravity.localharness.SubagentSkillsConfig.InheritConfig message.
type SubagentSkillsConfigInheritConfig struct {
	ExtraSkillsPaths []string `json:"extraSkillsPaths,omitempty"`
	SkillNames       []string `json:"skillNames,omitempty"`
}

// GetExtraSkillsPaths returns ExtraSkillsPaths, or nil when x is nil.
func (x *SubagentSkillsConfigInheritConfig) GetExtraSkillsPaths() []string {
	if x != nil {
		return x.ExtraSkillsPaths
	}
	return nil
}

// GetSkillNames returns SkillNames, or nil when x is nil.
func (x *SubagentSkillsConfigInheritConfig) GetSkillNames() []string {
	if x != nil {
		return x.SkillNames
	}
	return nil
}

// SubagentSkillsConfigNoneConfig mirrors the antigravity.localharness.SubagentSkillsConfig.NoneConfig message.
type SubagentSkillsConfigNoneConfig struct {
}

// SubagentSkillsConfigOverrideConfig mirrors the antigravity.localharness.SubagentSkillsConfig.OverrideConfig message.
type SubagentSkillsConfigOverrideConfig struct {
	SkillsPaths []string `json:"skillsPaths,omitempty"`
}

// GetSkillsPaths returns SkillsPaths, or nil when x is nil.
func (x *SubagentSkillsConfigOverrideConfig) GetSkillsPaths() []string {
	if x != nil {
		return x.SkillsPaths
	}
	return nil
}

// ToolOutputTruncation mirrors the antigravity.localharness.ToolOutputTruncation message.
// At most one of the strategy oneof fields (Truncate, Error) is set.
type ToolOutputTruncation struct {
	Truncate *ToolOutputTruncationTruncateStrategy `json:"truncate,omitempty"` // oneof strategy
	Error    *ToolOutputTruncationErrorStrategy    `json:"error,omitempty"`    // oneof strategy
}

// GetTruncate returns Truncate, or nil when x is nil.
func (x *ToolOutputTruncation) GetTruncate() *ToolOutputTruncationTruncateStrategy {
	if x != nil {
		return x.Truncate
	}
	return nil
}

// GetError returns Error, or nil when x is nil.
func (x *ToolOutputTruncation) GetError() *ToolOutputTruncationErrorStrategy {
	if x != nil {
		return x.Error
	}
	return nil
}

// ToolOutputTruncationTruncateStrategy mirrors the antigravity.localharness.ToolOutputTruncation.TruncateStrategy message.
type ToolOutputTruncationTruncateStrategy struct {
	MaxTokens *int32 `json:"maxTokens,omitempty"`
}

// GetMaxTokens returns MaxTokens, or the zero value when unset.
func (x *ToolOutputTruncationTruncateStrategy) GetMaxTokens() int32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

// ToolOutputTruncationErrorStrategy mirrors the antigravity.localharness.ToolOutputTruncation.ErrorStrategy message.
type ToolOutputTruncationErrorStrategy struct {
	MaxTokens    *int32  `json:"maxTokens,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
}

// GetMaxTokens returns MaxTokens, or the zero value when unset.
func (x *ToolOutputTruncationErrorStrategy) GetMaxTokens() int32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

// GetErrorMessage returns ErrorMessage, or the zero value when unset.
func (x *ToolOutputTruncationErrorStrategy) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// RetryConfig mirrors the antigravity.localharness.RetryConfig message.
type RetryConfig struct {
	APIRetry         *ModelAPIRetryConfig    `json:"apiRetry,omitempty"`
	ModelOutputRetry *ModelOutputRetryConfig `json:"modelOutputRetry,omitempty"`
}

// GetAPIRetry returns APIRetry, or nil when x is nil.
func (x *RetryConfig) GetAPIRetry() *ModelAPIRetryConfig {
	if x != nil {
		return x.APIRetry
	}
	return nil
}

// GetModelOutputRetry returns ModelOutputRetry, or nil when x is nil.
func (x *RetryConfig) GetModelOutputRetry() *ModelOutputRetryConfig {
	if x != nil {
		return x.ModelOutputRetry
	}
	return nil
}

// ModelAPIRetryConfig mirrors the antigravity.localharness.ModelAPIRetryConfig message.
type ModelAPIRetryConfig struct {
	MaxRetries             *uint32  `json:"maxRetries,omitempty"`
	InitialSleepDurationMs *uint32  `json:"initialSleepDurationMs,omitempty"`
	ExponentialMultiplier  *float64 `json:"exponentialMultiplier,omitempty"`
	JitterRange            *float64 `json:"jitterRange,omitempty"`
}

// GetMaxRetries returns MaxRetries, or the zero value when unset.
func (x *ModelAPIRetryConfig) GetMaxRetries() uint32 {
	if x != nil && x.MaxRetries != nil {
		return *x.MaxRetries
	}
	return 0
}

// GetInitialSleepDurationMs returns InitialSleepDurationMs, or the zero value when unset.
func (x *ModelAPIRetryConfig) GetInitialSleepDurationMs() uint32 {
	if x != nil && x.InitialSleepDurationMs != nil {
		return *x.InitialSleepDurationMs
	}
	return 0
}

// GetExponentialMultiplier returns ExponentialMultiplier, or the zero value when unset.
func (x *ModelAPIRetryConfig) GetExponentialMultiplier() float64 {
	if x != nil && x.ExponentialMultiplier != nil {
		return *x.ExponentialMultiplier
	}
	return 0
}

// GetJitterRange returns JitterRange, or the zero value when unset.
func (x *ModelAPIRetryConfig) GetJitterRange() float64 {
	if x != nil && x.JitterRange != nil {
		return *x.JitterRange
	}
	return 0
}

// ModelOutputRetryConfig mirrors the antigravity.localharness.ModelOutputRetryConfig message.
type ModelOutputRetryConfig struct {
	MaxRetries *uint32 `json:"maxRetries,omitempty"`
}

// GetMaxRetries returns MaxRetries, or the zero value when unset.
func (x *ModelOutputRetryConfig) GetMaxRetries() uint32 {
	if x != nil && x.MaxRetries != nil {
		return *x.MaxRetries
	}
	return 0
}

// PolicyConfig mirrors the antigravity.localharness.PolicyConfig message.
type PolicyConfig struct {
	Rules                []*PolicyRule                     `json:"rules,omitempty"`
	WorkspaceContainment *PolicyConfigWorkspaceContainment `json:"workspaceContainment,omitempty"`
	AutoConfig           *AutoPolicyConfig                 `json:"autoConfig,omitempty"`
}

// GetRules returns Rules, or nil when x is nil.
func (x *PolicyConfig) GetRules() []*PolicyRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// GetWorkspaceContainment returns WorkspaceContainment, or the zero value when unset.
func (x *PolicyConfig) GetWorkspaceContainment() PolicyConfigWorkspaceContainment {
	if x != nil && x.WorkspaceContainment != nil {
		return *x.WorkspaceContainment
	}
	return ""
}

// GetAutoConfig returns AutoConfig, or nil when x is nil.
func (x *PolicyConfig) GetAutoConfig() *AutoPolicyConfig {
	if x != nil {
		return x.AutoConfig
	}
	return nil
}

// PolicyRule mirrors the antigravity.localharness.PolicyRule message.
type PolicyRule struct {
	Tool       *string         `json:"tool,omitempty"`
	ServerName *string         `json:"serverName,omitempty"`
	Name       *string         `json:"name,omitempty"`
	Decision   *PolicyDecision `json:"decision,omitempty"`
	DenyReason *string         `json:"denyReason,omitempty"`
	IsDynamic  *bool           `json:"isDynamic,omitempty"`
	RuleID     *string         `json:"ruleId,omitempty"`
}

// GetTool returns Tool, or the zero value when unset.
func (x *PolicyRule) GetTool() string {
	if x != nil && x.Tool != nil {
		return *x.Tool
	}
	return ""
}

// GetServerName returns ServerName, or the zero value when unset.
func (x *PolicyRule) GetServerName() string {
	if x != nil && x.ServerName != nil {
		return *x.ServerName
	}
	return ""
}

// GetName returns Name, or the zero value when unset.
func (x *PolicyRule) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// GetDecision returns Decision, or the zero value when unset.
func (x *PolicyRule) GetDecision() PolicyDecision {
	if x != nil && x.Decision != nil {
		return *x.Decision
	}
	return ""
}

// GetDenyReason returns DenyReason, or the zero value when unset.
func (x *PolicyRule) GetDenyReason() string {
	if x != nil && x.DenyReason != nil {
		return *x.DenyReason
	}
	return ""
}

// GetIsDynamic returns IsDynamic, or the zero value when unset.
func (x *PolicyRule) GetIsDynamic() bool {
	if x != nil && x.IsDynamic != nil {
		return *x.IsDynamic
	}
	return false
}

// GetRuleID returns RuleID, or the zero value when unset.
func (x *PolicyRule) GetRuleID() string {
	if x != nil && x.RuleID != nil {
		return *x.RuleID
	}
	return ""
}

// AutoPolicyConfig mirrors the antigravity.localharness.AutoPolicyConfig message.
type AutoPolicyConfig struct {
	Enabled *bool   `json:"enabled,omitempty"`
	Model   *string `json:"model,omitempty"`
}

// GetEnabled returns Enabled, or the zero value when unset.
func (x *AutoPolicyConfig) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

// GetModel returns Model, or the zero value when unset.
func (x *AutoPolicyConfig) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

// BudgetConfig mirrors the antigravity.localharness.BudgetConfig message.
type BudgetConfig struct {
	MaxModelCalls   *int32                   `json:"maxModelCalls,omitempty"`
	MaxToolCalls    *int32                   `json:"maxToolCalls,omitempty"`
	MaxInputTokens  *Int64                   `json:"maxInputTokens,omitempty"`
	MaxOutputTokens *Int64                   `json:"maxOutputTokens,omitempty"`
	MaxTotalTokens  *Int64                   `json:"maxTotalTokens,omitempty"`
	Scope           *BudgetConfigBudgetScope `json:"scope,omitempty"`
}

// GetMaxModelCalls returns MaxModelCalls, or the zero value when unset.
func (x *BudgetConfig) GetMaxModelCalls() int32 {
	if x != nil && x.MaxModelCalls != nil {
		return *x.MaxModelCalls
	}
	return 0
}

// GetMaxToolCalls returns MaxToolCalls, or the zero value when unset.
func (x *BudgetConfig) GetMaxToolCalls() int32 {
	if x != nil && x.MaxToolCalls != nil {
		return *x.MaxToolCalls
	}
	return 0
}

// GetMaxInputTokens returns MaxInputTokens, or the zero value when unset.
func (x *BudgetConfig) GetMaxInputTokens() int64 {
	if x != nil && x.MaxInputTokens != nil {
		return int64(*x.MaxInputTokens)
	}
	return 0
}

// GetMaxOutputTokens returns MaxOutputTokens, or the zero value when unset.
func (x *BudgetConfig) GetMaxOutputTokens() int64 {
	if x != nil && x.MaxOutputTokens != nil {
		return int64(*x.MaxOutputTokens)
	}
	return 0
}

// GetMaxTotalTokens returns MaxTotalTokens, or the zero value when unset.
func (x *BudgetConfig) GetMaxTotalTokens() int64 {
	if x != nil && x.MaxTotalTokens != nil {
		return int64(*x.MaxTotalTokens)
	}
	return 0
}

// GetScope returns Scope, or the zero value when unset.
func (x *BudgetConfig) GetScope() BudgetConfigBudgetScope {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return ""
}

// CompactionConfig mirrors the antigravity.localharness.CompactionConfig message.
type CompactionConfig struct {
	TokenThreshold           *uint32 `json:"tokenThreshold,omitempty"`
	CheckpointIntervalTokens *uint32 `json:"checkpointIntervalTokens,omitempty"`
	MaxContextTokens         *uint32 `json:"maxContextTokens,omitempty"`
}

// GetTokenThreshold returns TokenThreshold, or the zero value when unset.
func (x *CompactionConfig) GetTokenThreshold() uint32 {
	if x != nil && x.TokenThreshold != nil {
		return *x.TokenThreshold
	}
	return 0
}

// GetCheckpointIntervalTokens returns CheckpointIntervalTokens, or the zero value when unset.
func (x *CompactionConfig) GetCheckpointIntervalTokens() uint32 {
	if x != nil && x.CheckpointIntervalTokens != nil {
		return *x.CheckpointIntervalTokens
	}
	return 0
}

// GetMaxContextTokens returns MaxContextTokens, or the zero value when unset.
func (x *CompactionConfig) GetMaxContextTokens() uint32 {
	if x != nil && x.MaxContextTokens != nil {
		return *x.MaxContextTokens
	}
	return 0
}

// SkillsConfig mirrors the antigravity.localharness.SkillsConfig message.
type SkillsConfig struct {
	Enabled *bool          `json:"enabled,omitempty"`
	Skills  []*SkillSource `json:"skills,omitempty"`
}

// GetEnabled returns Enabled, or the proto default true when unset.
func (x *SkillsConfig) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return true
}

// GetSkills returns Skills, or nil when x is nil.
func (x *SkillsConfig) GetSkills() []*SkillSource {
	if x != nil {
		return x.Skills
	}
	return nil
}

// SkillSource mirrors the antigravity.localharness.SkillSource message.
type SkillSource struct {
	DirectoryPath *string `json:"directoryPath,omitempty"`
}

// GetDirectoryPath returns DirectoryPath, or the zero value when unset.
func (x *SkillSource) GetDirectoryPath() string {
	if x != nil && x.DirectoryPath != nil {
		return *x.DirectoryPath
	}
	return ""
}

// RulesConfig mirrors the antigravity.localharness.RulesConfig message.
type RulesConfig struct {
	Filenames []string `json:"filenames,omitempty"`
}

// GetFilenames returns Filenames, or nil when x is nil.
func (x *RulesConfig) GetFilenames() []string {
	if x != nil {
		return x.Filenames
	}
	return nil
}
